<?php
// echo $this->headLink(array(
// 		'rel' => 'shortcut icon',
// 		'type' => 'image/vnd.microsoft.icon',
// 		'href' => $this->basePath() . '/image/icons/favicon.ico'
// 		))
// 		->prependStylesheet($this->basePath() . '/css/style.css')
// 		->prependStylesheet($this->basePath() . '/css/login.css')
// 		->prependStylesheet($this->basePath() . '/css/bootstrap.css')
// 		->appendStylesheet($this->basePath() . '/css/jquery-ui-1.8.16.custom.css')
// 		->appendStylesheet($this->basePath() . '/css/fullcalendar.css')
// 		->appendStylesheet($this->basePath() . '/css/chosen.css')
// 		->appendStylesheet($this->basePath() . '/css/glisse.css?1.css')
// 		->appendStylesheet($this->basePath() . '/css/jquery.jgrowl.css')
// 		->appendStylesheet($this->basePath() . '/css/demo_table.css')
// 		->appendStylesheet($this->basePath() . '/css/jquery.fancybox.css?v=2.1.4')
// 		->appendStylesheet($this->basePath() . '/css/icon/font-awesome.css')
// 		->appendStylesheet($this->basePath() . '/css/bootstrap-responsive.css')
// 		;
?>

<!-- Le styles -->
<!--<link href="/css/style.css" rel="stylesheet">-->
<link href="/css/bootstrap.css" rel="stylesheet"> 

<link rel="stylesheet" href="/css/jquery-ui-1.8.16.custom.css" media="screen">
<link rel="stylesheet" href="/css/fullcalendar.css" media="screen">
<link rel="stylesheet" href="/css/chosen.css" media="screen">
<link rel="stylesheet" href="/css/glisse.css?1.css">
<link rel="stylesheet" href="/css/jquery.jgrowl.css">
<link rel="stylesheet" href="/css/demo_table.css">
<link rel="stylesheet" href="/css/jquery.fancybox.css?v=2.1.4" media="screen">

<link rel="stylesheet" href="/css/front/style.css">  
<link rel="stylesheet" href="/css/front/responsive.css">

<link rel="alternate stylesheet" type="text/css" media="screen" title="green-theme" href="/css/color/green.css">
<link rel="alternate stylesheet" type="text/css" media="screen" title="red-theme" href="/css/color/red.css">
<link rel="alternate stylesheet" type="text/css" media="screen" title="blue-theme" href="/css/color/blue.css">
<link rel="alternate stylesheet" type="text/css" media="screen" title="orange-theme" href="/css/color/orange.css">
<link rel="alternate stylesheet" type="text/css" media="screen" title="purple-theme" href="/css/color/purple.css">
<link rel="stylesheet" href="/css/default.css" type="text/css">
<link rel="stylesheet" href="/css/base.css">
<link rel="stylesheet" href="/css/jquery-ui-1.10.4.css">

<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<script src="/js/jquery.min.js"></script>

<script src="/js/moderniz.js"></script>
<script src="/js/main.js"></script>

<script src="/js/front/common.js"></script>
<script src="/js/front/html5.js"></script>
<script src="/js/front/jquery.cbpNTAccordion.js"></script>
<script src="/js/front/jquery.cbpNTAccordion.min.js"></script>
<script src="/js/front/jquery.dd.js"></script>

<script language="JavaScript">
    Firefox = navigator.userAgent.indexOf("Firefox") >= 0;
    if (Firefox)
        document.write("<link rel='stylesheet' href='/css/moz.css' type='text/css'>");
</script>

<!-- Le fav and touch icons -->
<link rel="shortcut icon" href="favicon.ico">



<script type="text/javascript" src="/js/ckeditor/ckeditor.js"></script>
<script type="text/javascript" src="/js/ckeditor/config.js?t=D3NA"></script>
<script type="text/javascript" src="/js/zebra_datepicker.js"></script>

    <script src="/js/jquery-ui.min.js"></script>
   
    <script src="/js/bootstrap.min.js"></script>
    <script src="/js/google-code-prettify/prettify.js"></script>
   
<!--    <script src="/js/jquery.flot.js"></script>
    <script src="/js/jquery.flot.pie.js"></script>
    <script src="/js/jquery.flot.orderBars.js"></script>
    <script src="/js/jquery.flot.resize.js"></script>
    <script src="/js/jquery.flot.categories.js"></script>-->
    <script src="/js/graphtable.js"></script>
    <script src="/js/fullcalendar.min.js"></script>
    <script src="/js/chosen.jquery.min.js"></script>
    <script src="/js/autoresize.jquery.min.js"></script>
    <script src="/js/jquery.autotab.js"></script>
    <script src="/js/jquery.jgrowl_minimized.js"></script>
    <script src="/js/jquery.dataTables.min.js"></script>
    <script src="/js/jquery.stepy.min.js"></script>
    <script src="/js/jquery.validate.min.js"></script>
    <script src="/js/raphael.2.1.0.min.js"></script>
    <script src="/js/justgage.1.0.1.min.js"></script>
	  <script src="/js/glisse.js"></script>
	  <script src="/js/styleswitcher.js"></script>
	  
    <script src="/js/jquery.sparkline.min.js"></script>
    <script src="/js/slidernav-min.js"></script>
    <script type="text/javascript" src="/js/jquery.fancybox.js?v=2.1.4"></script>
    
	<script>
    Modernizr.load([
        {
         load: [
                '/js/main.js'
            ],
            complete: function()
            {
                $.fn.ready(function()
                {
                    window.App.init();
                });
            }
        }
    ]);
    </script>
	<script src="/js/application.js"></script>
    
    <!--settings infobox charts-->
<!--    <script src="/js/float.settings.infobox.js"></script>-->
    <script src="/js/base.js"></script>
