<div class="footer">
    <div class="left">Copyright &copy <?php echo date('Y'); ?></div>
    <div class="right">
        <a href="javascript:void(0)">AVP</a>
    </div>
    <div class="clearfix"></div>
</div>

<!-- JavaScript Confirm Modal using Bootstrap -->
<script>
    $(document).ready(function() {
        $('a[data-confirm]').click(function(ev) {
            var href = $(this).attr('href');
            if (!$('#dataConfirmModal').length) {
                $('body').append('<div id="dataConfirmModal" class="modal" style="width: 300px; margin: auto;" role="dialog" aria-labelledby="dataConfirmLabel" aria-hidden="true"><div class="modal-header"><button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button><h3 id="dataConfirmLabel">Please Confirm</h3></div><div class="modal-body"></div><div class="modal-footer"><button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button><a class="btn btn-primary" id="dataConfirmOK">OK</a></div></div>');
            }
            $('#dataConfirmModal').find('.modal-body').text($(this).attr('data-confirm'));
            $('#dataConfirmOK').attr('href', href);
            $('#dataConfirmModal').modal({show: true});
            return false;
        });
    });

</script>

<script>
// Make sure the DOM elements are loaded and accounted for

    $(document).ready(function() {
        $('a[data-toggle="modal"]').click(function() {
            var remote_content = $(this).attr('href');
            //console.log(remote_content);
            
            var modal = $('.bs-example-modal-lg');
            
            var modalBody = $('.bs-example-modal-lg .modal-body');

            
            $.get(remote_content, {}, function(data) {
                modalBody.html(data);
                modal.modal();
            });
            
            return false;
        });
    });

</script>
