<head>
    
    <meta charset="utf-8">
    <?php echo $this->headTitle('Login '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>
    
    <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    
    <meta name="description" content="">
    <meta name="author" content="">
<!-- Le styles -->
        <?php echo $this->partial('layout/components/base/css.phtml');?>
        
        <!--[if lt IE 9]>
      		<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    	<![endif]-->
        
       
        
</head>

