<?php 
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url(
		'inventory-promos-edit', array('id' => $form->get('id')->getValue())
));
$form->setAttribute('method', 'post');
$form->setAttribute('enctype', 'multipart/form-data');
if($form->get('dateFrom')->getValue() instanceof DateTime)
	$form->get('dateFrom')->setValue($form->get('dateFrom')->getValue()->format('Y-m-d')); // DateTime to str fix;
if($form->get('dateTo')->getValue() instanceof DateTime)
	$form->get('dateTo')->setValue($form->get('dateTo')->getValue()->format('Y-m-d')); // DateTime to str fix;
?>
<div class="grid">
	<div class="grid-title">
		<div class="pull-left">
			<div class="icon-title">
				<i class="icon-plus"></i>
			</div>
			<span>Edit Promo</span>
			<div class="clearfix"></div>
		</div>
		<div class="clearfix"></div>
	</div>
	<?php echo $this->form()->openTag($form); ?>
	<div class="grid-content">
            <?php echo $this->formElement($form->get('id')); ?>
            <div class="formRow control-group">
                    <?php echo $this->formLabel($form->get('promoNames')); ?>
                    <div class="formRight">
                            <?php echo $this->formElement($form->get('promoNames')->setAttribute('class', 'span input')); ?>
                    <?php echo $this->formElementErrors($form->get('promoNames'), array('class' => 'help-inline')); ?>
                    </div>
            </div>  
            <div class="formRow control-group">
                    <?php echo $this->formLabel($form->get('linkedTo')); ?>
                    <div class="formRight">
                            <?php echo $this->formElement($form->get('linkedTo')->setAttribute('class', 'chzn-select chosen_select width-100')); ?>
                    <?php echo $this->formElementErrors($form->get('linkedTo'), array('class' => 'help-inline')); ?>
                    </div>
            </div>
            <div id="ajax-data" class="formRow control-group">
                
                <div class="formRight multicheckbox">
                    <?php echo $this->formElement($form->get('ids')->setAttribute('class', 'span input')); ?>
                </div>
            </div>
            <div class="formRow control-group">
                    <?php echo $this->formLabel($form->get('isActive')); ?>
                    <div class="formRight">
                            <?php echo $this->formElement($form->get('isActive')->setAttribute('class', 'chzn-select chosen_select width-100')); ?>
                    <?php echo $this->formElementErrors($form->get('isActive'), array('class' => 'help-inline')); ?>
                    </div>
            </div> 
            <div class="formRow control-group">
                    <?php echo $this->formLabel($form->get('dateFrom')); ?>
                    <div class="formRight">
                            <?php echo $this->formElement($form->get('dateFrom')->setAttribute('class', 'span input')); ?>
                    <?php echo $this->formElementErrors($form->get('dateFrom'), array('class' => 'help-inline')); ?>
                    </div>
            </div>
            <div class="formRow control-group">
                    <?php echo $this->formLabel($form->get('dateTo')); ?>
                    <div class="formRight">
                            <?php echo $this->formElement($form->get('dateTo')->setAttribute('class', 'span input')); ?>
                    <?php echo $this->formElementErrors($form->get('dateTo'), array('class' => 'help-inline')); ?>
                    </div>
            </div>
            <div class="formRow control-group">
                    <?php echo $this->formLabel($form->get('discountType')); ?>
                    <div class="formRight">
                            <?php echo $this->formElement($form->get('discountType')->setAttribute('class', 'chzn-select chosen_select width-100')); ?>
                    <?php echo $this->formElementErrors($form->get('discountType'), array('class' => 'help-inline')); ?>
                    </div>
            </div>
            <div class="formRow control-group">
                    <?php echo $this->formLabel($form->get('discount')); ?>
                    <div class="formRight">
                            <?php echo $this->formElement($form->get('discount')->setAttribute('class', 'span input')); ?>
                    <?php echo $this->formElementErrors($form->get('discount'), array('class' => 'help-inline')); ?>
                    </div>
            </div> 
            <div class="formRow control-group">
                    <?php echo $this->formLabel($form->get('image')); ?>
                    <div class="formRight">
                            <?php echo $this->formElement($form->get('image')->setAttribute('class', 'span input')); ?>
                    <?php echo $this->formElementErrors($form->get('image'), array('class' => 'help-inline')); ?>
                    </div>
            </div>
            <div class="formRow control-group">
                    <?php echo $this->formLabel($form->get('promoCode')); ?>
                    <div class="formRight">
                            <?php echo $this->formElement($form->get('promoCode')->setAttribute('class', 'span input')); ?>
                    <?php echo $this->formElementErrors($form->get('promoCode'), array('class' => 'help-inline')); ?>
                    </div>
            </div>
            <div class="formRow control-group">
                    <?php echo $this->formLabel($form->get('description')); ?>
                    <div class="formRight">
                            <?php echo $this->formElement($form->get('description')->setAttribute('class', 'span input same-height-1')->setAttribute('rows', '3')); ?>
                    <?php echo $this->formElementErrors($form->get('description'), array('class' => 'help-inline')); ?>
                    </div>
            </div>              
            <div class="formRow control-group">
                    <?php echo $this->formSubmit( $form->get('submit')->setAttribute('class', 'btn btn-info')) ?>
                    <input id="resetbutton" class="btn btn-info" type="reset" value="Reset" name="reset"></input>
            </div>
            <div class="clearfix"></div>

	</div>
	<?php echo $this->form()->closeTag() ?>
</div>

<script>
$(function(){
    $('.grid-content .formRow ul.help-inline').parents('.formRow').addClass('error');
    $('.error input').keyup(function(){
                            $(this).parents('.formRow').removeClass('error');
                            $(this).next('ul.help-inline').remove();
    });

    $('#linkedTo').change(function(){  
        var typeCode = $(this).val(); 
        $.post('/admin/inventory/ajax/promo/linkedto/'+typeCode,{id:typeCode}, function(data){            
                    $('#ajax-data').html(data);                        
        });
    });    
});				
</script>


