<?php
if (!is_null($this->message)):
    if ($this->message):
        ?>		
        <div class="alert alert-dismissable alert-<?php echo $this->message[0]['type']; ?>">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <ul>
                <li><?php echo $this->message[0]['message']; ?></li>        
            </ul>
        </div>
        <?php
    endif;
endif;
?>
<div class="grid">
    <div class="grid-title">
        <div class="pull-left">
            <div class="icon-title">
                <i class="icon-list"></i>
            </div>
            <span>Tours</span>
            <div class="clearfix"></div>
        </div>
        <div class="pull-right">
            <div class="icon-title">
             <!--   <a href="<?php //echo $this->url('inventory-promos-add'); ?>"><i class="icon-plus-sign"></i></a> -->
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="grid-content overflow">
        <table class="table table-bordered table-mod-2" id="datatable_3">
            <thead>
                <tr>
                       
                    <th class="hidden-mobile">Tour Name</th>
                    <th class="hidden-mobile">Tour Location</th>
                    <th class="hidden-mobile">Total Hotels</th>
                    <th class="hidden-mobile">Total Rooms</th>
                    <th class="hidden-mobile">Total Sold</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <?php $i = 1;
                foreach ($this->collection as $item): //$items=$item['tour'];?>
                    <tr>
                                           
                        <td class="hidden-mobile"><?php echo $item['tour']->getTitle(); ?></td>                        
                        <td class="hidden-mobile"><?php echo $item['locationcount']; ?></td>
                        <td class="hidden-mobile"><?php echo  $item['resortcount']; ?></td>
                        <td class="hidden-mobile"><?php echo $item['resortroomscount']; ?></td>
                        <td class="hidden-mobile"><?php echo '-';//$item->getDiscountType() ? '' : '$'; echo $item->getDiscount(); echo $item->getDiscountType() ? '%' : ''; ?></td>
                                              
                        <td class="action-table">                            
                            <a href="<?php echo $this->url('tour-location', array('id' => $item['id'])); ?>">
                                Location
                            </a>
                           
                        </td>
                    </tr>
                    <?php $i++; ?>
                <?php endforeach; ?>
            </tbody>
        </table>
        <div class="clearfix"></div>
    </div>
</div>