<?php
//d($this->collection);
if (!is_null($this->message)):
    if ($this->message):
        ?>		
        <div class="alert alert-dismissable alert-<?php echo $this->message[0]['type']; ?>">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <ul>
                <li><?php echo $this->message[0]['message']; ?></li>        
            </ul>
        </div>
        <?php
    endif;
endif;
?>
<div class="grid">
    <div class="grid-title">
        <div class="pull-left">
            <div class="icon-title">
                <i class="icon-list"></i>
            </div>
            <span>Tour Resort Rooms  <?php //echo $this->collection[0]->getTourId()->getTitle();?></span>
            <div class="clearfix"></div>
        </div>
        <div class="pull-right">
            <div class="icon-title">
                <a href="<?php echo $this->url('tour-location-resort-rooms-add', array('locationid'=>$this->locationid,'id' => $this->id)); ?>"><i class="icon-plus-sign"></i></a>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="grid-content overflow">
        <table class="table table-bordered table-mod-2" id="datatable_3">
            <thead>
                <tr>
                    <th class="hidden-mobile">Room Name</th>
                    <th class="hidden-mobile">Resort Name</th>
                
                    <th class="hidden-mobile">Status</th>

                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <?php
                $i = 1;
                foreach ($this->collection as $item): 
                    $status=$item->getStatus();
                    if($item->getStatus()==1){ $statusinfo='Active'; }else { $statusinfo='Inactive' ;}
                   // $statusinfo = $item->getStatus()==0 ? 'Enabled' :'Disabled';  
                    ?>
                    <tr>
                        <td class="hidden-mobile"><?php echo $item->getRoomId()->getTitle() ?></td>   
                        <td class="hidden-mobile"><?php echo $item->getResortId()->getTitle() ?></td>                        
                         <td class="hidden-mobile"><?php echo $statusinfo; ?></td>                        
                      
                        <td class="action-table">                            
                           
                            <a href="<?php echo $this->url('tour-location-resort-rooms-edit', array('id' => $item->getId())); ?>">
                                Edit
                            </a>

                           <?php if($status==1){ ?>
                             <a href="<?php echo $this->url('tour-location-resort-rooms-inactive', array('id' => $item->getId())); ?>">
                               Inactive
                            </a>
                            <?php      }else{ ?>
                            
                            <a href="<?php echo $this->url('tour-location-resort-rooms-active', array('id' => $item->getId())); ?>">
                                Active
                            </a>
                            <?php } ?>
                            
                            <a href="<?php echo $this->url('tour-location-resort-rooms-delete', array('id' => $item->getId())); ?>" data-confirm="Are you sure?">
                                Delete
                            </a>

                        </td>
                    </tr>
                    <?php $i++; ?>
                <?php endforeach; ?>
            </tbody>
        </table>
        <div class="clearfix"></div>
    </div>
</div>