<?php
$form = $this->form;

$form->prepare();
$form->setAttribute('action', $this->url(
                'tour-location-resort-rooms-add', array('locationid' => $this->locationid, 'id' => $this->id)
));

$form->setAttribute('method', 'post');
//d($this->data);
?>
<div class="grid">

    <?php echo $this->form()->openTag($form); ?>
    <div class="grid-content">

        <input type="hidden" value="<?php echo $this->locationid; ?>" name="locationId">
        <input type="hidden" value="<?php echo $this->id; ?>" name="resortId">

        <div class="formRow control-group">			
            <label for="resort-option" class="required">Room Type</label>
            <div class="formRight">
                <div name="resort-option" class="distance distance-2">
                    <p>
                        <input type="radio" id="ex" class="click-resort" name="type" checked="checked" value="1" >
                        <label for="ex"><span></span>Existing</label>
                    </p>
                    <p>
                        <input type="radio" id="new" class="click-resort" name="type" value="2" >
                        <label for="new"><span></span>New</label>
                    </p>
                </div>
            </div>
        </div>
        <div id="exsisting_detail">
            <div class="formRow control-group">
                <label for="roomId" class="required">Room</label>                    
                <div class="formRight">    
                    <select name="roomId" class="chzn-select chosen_select width-100 roomId">        
                        <option value="">please select room...</option>
                        <?php foreach ($this->data as $item): ?>

                            <option value="<?php echo $item->getId(); ?>"><?php echo $item->getTitle(); ?></option>
                        <?php endforeach; ?>    
                    </select> 
                </div>
            </div>    
        </div>   


        <div id="new_detail" style="display:none;">
            <div class="formRow control-group">
                <?php echo $this->formLabel($form->get('title')); ?>
                <div class="formRight">
                    <?php echo $this->formElement($form->get('title')->setAttribute('class', 'span input')); ?>
                    <?php echo $this->formElementErrors($form->get('title'), array('class' => 'help-inline')); ?>
                </div>
            </div>


            <div class="formRow control-group">
                <?php echo $this->formLabel($form->get('description')); ?>
                <div class="formRight">
                    <?php echo $this->formElement($form->get('description')->setAttribute('class', 'ckeditor')); ?>
                    <?php echo $this->formElementErrors($form->get('description'), array('class' => 'help-inline')); ?>
                </div>
            </div>

            <div class="formRow control-group">
                <?php echo $this->formLabel($form->get('image')); ?>
                <div class="formRight">
                    <?php echo $this->formElement($form->get('image')); //->setAttribute('required', 'required')); ?>
                    <?php echo $this->formElementErrors($form->get('image'), array('class' => 'help-inline')); ?>
                </div>
            </div>




        </div>


        <div class="formRow control-group">			
            <label for="board">Board</label>
            <div class="formRight">
                <div name="board" class="distance distance-2">
                    <p>
                        <input type="radio" id="all-inclusive" class="load-entity" name="board" checked="checked" value="1" data-resource="all-inclusive">
                        <label for="all-inclusive"><span></span>All Inclusive</label>
                    </p>
                    <p>
                        <input type="radio" id="breakfast-included" class="load-entity" name="board" value="2" data-resource="breakfast-included">
                        <label for="breakfast-included"><span></span>Breakfast Included</label>
                    </p>
                    <p>
                        <input type="radio" id="room-only" class="load-entity" name="board" value="2" data-resource="room-only">
                        <label for="room-only"><span></span>Room Only</label>
                    </p>
                </div>
            </div>
        </div>    



        <div class="formRow control-group">
            <?php echo $this->formLabel($form->get('netPrice')); ?>
            <div class="formRight">
                <?php echo $this->formElement($form->get('netPrice')->setAttribute('class', 'span input')); ?>
                <?php echo $this->formElementErrors($form->get('netPrice'), array('class' => 'help-inline')); ?>
            </div>
        </div>            
        <div class="formRow control-group">
            <?php echo $this->formLabel($form->get('grossPrice')); ?>
            <div class="formRight">
                <?php echo $this->formElement($form->get('grossPrice')->setAttribute('class', 'span input')); ?>
                <?php echo $this->formElementErrors($form->get('grossPrice'), array('class' => 'help-inline')); ?>
            </div>
        </div>   





        <!-- new fieds added as mockups -->

        <div class="formRow control-group">			
            <label for="pricePer">Price Per</label>
            <div class="formRight">
                <div name="pricePer" class="distance distance-2">
                    <p>
                        <input type="radio" id="person" class="load-entity" name="pricePer" checked="checked" value="1" data-resource="person">
                        <label for="person"><span></span>Person</label>
                    </p>
                    <p>
                        <input type="radio" id="room" class="load-entity" name="pricePer" value="2" data-resource="room">
                        <label for="room"><span></span>Room</label>
                    </p>
                </div>
            </div>
        </div>



        <div class="formRow control-group">			
            <label for="doubleOccupancy"> Double Occupancy Rate</label>
            <div class="formRight">
                <div name="double-occupancy-rate" class="distance distance-2">
                    <p>
                        <input type="radio" id="double-yes" class="load-entity" name="doubleOccupancyRate"  value="1" data-resource="double-yes">
                        <label for="double-yes"><span></span>Yes</label>
                    </p>
                    <p>
                        <input type="radio" id="double-no" class="load-entity" name="doubleOccupancyRate" checked="checked" value="0" data-resource="double-no">
                        <label for="double-no"><span></span>No</label>
                    </p>
                </div>
            </div>
        </div>


        <div class="formRow control-group">
            <?php echo $this->formLabel($form->get('femalesCount')); ?>
            <div class="formRight">
                <?php echo $this->formElement($form->get('femalesCount')->setAttribute('class', 'span input')); ?>
                <?php echo $this->formElementErrors($form->get('femalesCount'), array('class' => 'help-inline')); ?>
            </div>
        </div>

        <div class="formRow control-group">
            <?php echo $this->formLabel($form->get('malesCount')); ?>
            <div class="formRight">
                <?php echo $this->formElement($form->get('malesCount')->setAttribute('class', 'span input')); ?>
                <?php echo $this->formElementErrors($form->get('malesCount'), array('class' => 'help-inline')); ?>
            </div>
        </div>






        <div class="formRow control-group">			
            <label for="tripleOccupancyAllowed">Does this room allows triple Occupancy</label>
            <div class="formRight">
                <div name="pricePer" class="distance distance-2">
                    <p>
                        <input type="radio" id="yes" class="load-entity" name="tripleOccupancyAllowed"  value="1" data-resource="yes">
                        <label for="yes"><span></span>Yes</label>
                    </p>
                    <p>
                        <input type="radio" id="no" class="load-entity" name="tripleOccupancyAllowed" checked="checked" value="0" data-resource="no">
                        <label for="no"><span></span>No</label>
                    </p>
                </div>
            </div>
        </div>

        <div id="triple_event">
            <div class="formRow control-group">
                <?php echo $this->formLabel($form->get('triplePriceFemaleGross')); ?>
                <div class="formRight">
                    <?php echo $this->formElement($form->get('triplePriceFemaleNet')->setAttribute('class', 'span')); ?>
                    <?php echo $this->formElement($form->get('triplePriceFemaleGross')->setAttribute('class', 'span')); ?>
                    <input type="checkbox" id="tripleFemaleNa" name="tripleFemaleNa" value="1">
                    <label for="tripleFemaleNa"><span> </span> NA </label>


                    <?php echo $this->formElementErrors($form->get('triplePriceFemaleNet'), array('class' => 'help-inline')); ?>
                    <?php echo $this->formElementErrors($form->get('triplePriceFemaleGross'), array('class' => 'help-inline')); ?>

                    <?php echo $this->formElementErrors($form->get('triplePriceFemaleNet'), array('class' => 'help-inline')); ?>
                    <?php echo $this->formElementErrors($form->get('triplePriceFemaleGross'), array('class' => 'help-inline')); ?>


                </div>
            </div>      


            <div class="formRow control-group">
                <?php echo $this->formLabel($form->get('triplePriceMaleGross')); ?>
                <div class="formRight">
                    <?php echo $this->formElement($form->get('triplePriceMaleNet')->setAttribute('class', 'span')); ?>
                    <?php echo $this->formElement($form->get('triplePriceMaleGross')->setAttribute('class', 'span')); ?>

                    <input type="checkbox" id="tripleMaleNa" name="tripleMaleNa" value="1">
                    <label for="tripleMaleNa"><span> </span> NA </label>

                    <?php echo $this->formElementErrors($form->get('triplePriceMaleNet'), array('class' => 'help-inline')); ?>
                    <?php echo $this->formElementErrors($form->get('triplePriceMaleGross'), array('class' => 'help-inline')); ?>
                </div>
            </div>  






        </div>



        <div class="formRow control-group">			
            <label for="quadOccupancy">Quad Occupancy Allowed</label>
            <div class="formRight">
                <div name="quadOccupancy" class="distance distance-2">
                    <p>
                        <input type="radio" id="quad-yes" class="load-entity" name="quadOccupancy"  value="1" data-resource="quad-yes">
                        <label for="quad-yes"><span></span>Yes</label>
                    </p>
                    <p>
                        <input type="radio" id="quad-no" class="load-entity" name="quadOccupancy" checked="checked" value="0" data-resource="quad-no">
                        <label for="quad-no"><span></span>No</label>
                    </p>
                </div>
            </div>
        </div>


    <div class="formRow control-group">			
        <label for="singlePremiumOccupancy">Premium  for single Occupancy</label>
        <div class="formRight">
            <div name="singlePremiumOccupancy" class="distance distance-2">
                <p>
                    <input type="radio" id="single-yes" class="load-entity" name="singlePremiumOccupancy"  value="1" data-resource="single-yes">
                    <label for="single-yes"><span></span>Yes</label>
                </p>
                <p>
                    <input type="radio" id="single-no" class="load-entity" name="singlePremiumOccupancy" checked="checked" value="0" data-resource="single-no">
                    <label for="single-no"><span></span>No</label>
                </p>
            </div>
        </div>
    </div>

    <div id="single-price">
        <div class="formRow control-group">
            <?php echo $this->formLabel($form->get('singlePriceNet')); ?>
            <div class="formRight">
                <?php
                echo $this->formElement($form->get('singlePriceNet')->setAttribute('class', 'span input')
                                ->setAttribute('id', 'singlePriceNet'));
                ?>
                <?php echo $this->formElementErrors($form->get('singlePriceNet'), array('class' => 'help-inline')); ?>
            </div>
        </div>      

        <div class="formRow control-group">
            <?php echo $this->formLabel($form->get('singlePriceGross')); ?>
            <div class="formRight">
                <?php
                echo $this->formElement($form->get('singlePriceGross')->setAttribute('class', 'span input')
                                ->setAttribute('id', 'singlePriceGross'));
                ?>
                <?php echo $this->formElementErrors($form->get('singlePriceGross'), array('class' => 'help-inline')); ?>
            </div>
        </div>
    </div>

    <div class="formRow control-group">			
        <label for="singleShare">Allow single to Share</label>
        <div class="formRight">
            <div name="singleShare" class="distance distance-2">
                <p>
                    <input type="radio" id="single-share-yes" class="load-entity" name="singleShare"  value="1" data-resource="single-share-yes">
                    <label for="single-share-yes"><span></span>Yes</label>
                </p>
                <p>
                    <input type="radio" id="single-share-no" class="load-entity" name="singleShare" checked="checked" value="0" data-resource="single-share-no">
                    <label for="single-share-no"><span></span>No</label>
                </p>
            </div>
        </div>
    </div>


    <div class="formRow control-group">
        <?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-info')) ?>
        <input id="resetbutton" class="btn btn-info" type="reset" value="Reset" name="reset"></input>
    </div>
    <div class="clearfix"></div>

</div>
<?php echo $this->form()->closeTag() ?>
</div>

<script>


    $(function() {
        $('.grid-content .formRow ul.help-inline').parents('.formRow').addClass('error');
        $('.error input').keyup(function() {
            $(this).parents('.formRow').removeClass('error');
            $(this).next('ul.help-inline').remove();
        });
        $('.click-resort').click(function() {
            var type = $(this).val();
            $('input[name="title"]').attr('required');
            if (type == 2) {
                $("#new_detail").show();
                $("#exsisting_detail").hide();
                $('input[name="title"]').removeAttr('required');
            } else {
                $('input[name="roomId"]').removeAttr('required');
                 $('input[name="title"]').attr('required');
                $("#new_detail").hide();
                $("#exsisting_detail").show();
            }
        });


        $("#triple_event").css("display", "none");
        $("#single-price").css("display", "none");
        $("#quad").css("display", "none");

    });
    $('#hotels').change(function() {
        var id = $(this).val();
        $.post('/admin/inventory/ajax/resort/rooms/' + id, {id: id}, function(data) {
            $('#rooms').html(data);
        });
    });




    $("input:radio[name=tripleOccupancyAllowed]").click(function() {
        var value = $(this).val();
        if (value == 1) {
            $("#triple_event").css("display", "block");
        } else {
            $("#triple_event").css("display", "none");
        }
    });

    $("input:radio[name=singlePremiumOccupancy]").click(function() {
        var value = $(this).val();
        if (value == 1) {
            $("#single-price").css("display", "block");
        } else {
            $("#single-price").css("display", "none");
        }
    });

  
</script>


