<?php
if (!is_null($this->message)):
    if ($this->message):
        ?>		
        <div class="alert alert-dismissable alert-<?php echo $this->message[0]['type']; ?>">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <ul>
                <li><?php echo $this->message[0]['message']; ?></li>        
            </ul>
        </div>
        <?php
    endif;
endif;
?>
<div class="grid">
    <div class="grid-title">
        <div class="pull-left">
            <div class="icon-title">
                <i class="icon-list"></i>
            </div>
            <span>Tour Locations</span>
            <div class="clearfix"></div>
        </div>
        <div class="pull-right">
            <div class="icon-title">
                <a href="<?php echo $this->url('tour-location-add', array('id' => $this->id)); ?>"><i class="icon-plus-sign"></i></a>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="grid-content overflow">
        <table class="table table-bordered table-mod-2" id="datatable_3">
            <thead>
                <tr>

                    <th class="hidden-mobile">Country</th>
                    <th class="hidden-mobile">City</th>
                    <th class="hidden-mobile">Start Date</th>
                    <th class="hidden-mobile">End Date</th>

                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <?php
                $i = 1;
                foreach ($this->collection as $item): //$items=$item['tour'];
                    ?>
                    <tr>

                        <td class="hidden-mobile"><?php echo $item->getCountryId()->getCountryName() ?></td>                        
                        <td class="hidden-mobile"><?php echo $item->getCity(); ?></td>
                        <td class="hidden-mobile"><?php echo $item->getFromDate()->Format('M jS Y'); ?></td>
                        <td class="hidden-mobile"><?php echo $item->getToDate()->Format('M jS Y'); ?></td>

                        <td class="action-table">                            
                           <a href="<?php echo $this->url('tour-location-resorts', array('id' => $item->getId()));    ?>">
                                Accomodation
                            </a>


                            <a href="<?php echo $this->url('tour-location-edit', array('id' => $item->getId())); ?>">
                                Edit
                            </a>

                            <a href="<?php echo $this->url('tour-location-delete', array('id' => $item->getId())); ?>" data-confirm="Are you sure?">
                                Delete
                            </a>

                        </td>
                    </tr>
                    <?php $i++; ?>
                <?php endforeach; ?>
            </tbody>
        </table>
        <div class="clearfix"></div>
    </div>
</div>