<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Sendmail\Module'                        => __DIR__ . '/Module.php',
    'Sendmail\Controller\SendmailController' => __DIR__ . '/src/Sendmail/Controller/SendmailController.php',
    'SendmailTest\Framework\TestCase'        => __DIR__ . '/tests/Sendmail/Framework/TestCase.php',
    'SendmailTest\SampleTest'                => __DIR__ . '/tests/Sendmail/SampleTest.php',
);
