<?php

namespace DoctrineORMModule\Proxy\__CG__\Base\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Reservation extends \Base\Entity\Reservation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }



    /**
     * {@inheritDoc}
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', array($name, $value));

        return parent::__set($name, $value);
    }



    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'type', 'roomId', 'flight', 'departureFrom', 'departureTo', 'returnFrom', 'returnTo', 'totalCost', 'appliDiscount', 'finalCost', 'paymentType', 'depositAmoun', 'depositMethod', 'balansAfterDeposit', 'nextPaymentDue', 'dueDate1', 'finalPaymentDue', 'dueDate2', 'clientNotes', 'adminNotes', 'dateFrom', 'dateTo', 'flightTotalCost', 'noOfDays', 'roomRequired', 'roomRate', 'status', 'promo', 'merchantFee', 'createdAt', 'updatedAt', 'noOfPersons', 'excursionCost', 'transferCost', 'itemCost', 'isDraft', 'referenceNumber', 'affiliateId', 'isBooked', 'roomNetCost', 'addonsNetCost', 'airportName', 'discountType', 'currencyCode', 'isUpdated', 'isRefund', 'refundAmt', 'extraAmtPaid', 'extraDepAmt', 'isExtraPaid', 'isDeleted', 'serviceManager');
        }

        return array('__isInitialized__', 'id', 'type', 'roomId', 'flight', 'departureFrom', 'departureTo', 'returnFrom', 'returnTo', 'totalCost', 'appliDiscount', 'finalCost', 'paymentType', 'depositAmoun', 'depositMethod', 'balansAfterDeposit', 'nextPaymentDue', 'dueDate1', 'finalPaymentDue', 'dueDate2', 'clientNotes', 'adminNotes', 'dateFrom', 'dateTo', 'flightTotalCost', 'noOfDays', 'roomRequired', 'roomRate', 'status', 'promo', 'merchantFee', 'createdAt', 'updatedAt', 'noOfPersons', 'excursionCost', 'transferCost', 'itemCost', 'isDraft', 'referenceNumber', 'affiliateId', 'isBooked', 'roomNetCost', 'addonsNetCost', 'airportName', 'discountType', 'currencyCode', 'isUpdated', 'isRefund', 'refundAmt', 'extraAmtPaid', 'extraDepAmt', 'isExtraPaid', 'isDeleted', 'serviceManager');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Reservation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', array($type));

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', array());

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoomId($roomId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoomId', array($roomId));

        return parent::setRoomId($roomId);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoomId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoomId', array());

        return parent::getRoomId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFlight($flight)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFlight', array($flight));

        return parent::setFlight($flight);
    }

    /**
     * {@inheritDoc}
     */
    public function getFlight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFlight', array());

        return parent::getFlight();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepartureFrom($departureFrom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepartureFrom', array($departureFrom));

        return parent::setDepartureFrom($departureFrom);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepartureFrom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepartureFrom', array());

        return parent::getDepartureFrom();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepartureTo($departureTo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepartureTo', array($departureTo));

        return parent::setDepartureTo($departureTo);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepartureTo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepartureTo', array());

        return parent::getDepartureTo();
    }

    /**
     * {@inheritDoc}
     */
    public function setReturnFrom($returnFrom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReturnFrom', array($returnFrom));

        return parent::setReturnFrom($returnFrom);
    }

    /**
     * {@inheritDoc}
     */
    public function getReturnFrom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReturnFrom', array());

        return parent::getReturnFrom();
    }

    /**
     * {@inheritDoc}
     */
    public function setReturnTo($returnTo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReturnTo', array($returnTo));

        return parent::setReturnTo($returnTo);
    }

    /**
     * {@inheritDoc}
     */
    public function getReturnTo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReturnTo', array());

        return parent::getReturnTo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalCost($totalCost)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalCost', array($totalCost));

        return parent::setTotalCost($totalCost);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalCost()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalCost', array());

        return parent::getTotalCost();
    }

    /**
     * {@inheritDoc}
     */
    public function setAppliDiscount($appliDiscount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAppliDiscount', array($appliDiscount));

        return parent::setAppliDiscount($appliDiscount);
    }

    /**
     * {@inheritDoc}
     */
    public function getAppliDiscount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAppliDiscount', array());

        return parent::getAppliDiscount();
    }

    /**
     * {@inheritDoc}
     */
    public function setFinalCost($finalCost)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFinalCost', array($finalCost));

        return parent::setFinalCost($finalCost);
    }

    /**
     * {@inheritDoc}
     */
    public function getFinalCost()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFinalCost', array());

        return parent::getFinalCost();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentType($paymentType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentType', array($paymentType));

        return parent::setPaymentType($paymentType);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentType', array());

        return parent::getPaymentType();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepositAmoun($depositAmoun)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepositAmoun', array($depositAmoun));

        return parent::setDepositAmoun($depositAmoun);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepositAmoun()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepositAmoun', array());

        return parent::getDepositAmoun();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepositMethod($depositMethod)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepositMethod', array($depositMethod));

        return parent::setDepositMethod($depositMethod);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepositMethod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepositMethod', array());

        return parent::getDepositMethod();
    }

    /**
     * {@inheritDoc}
     */
    public function setBalansAfterDeposit($balansAfterDeposit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBalansAfterDeposit', array($balansAfterDeposit));

        return parent::setBalansAfterDeposit($balansAfterDeposit);
    }

    /**
     * {@inheritDoc}
     */
    public function getBalansAfterDeposit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBalansAfterDeposit', array());

        return parent::getBalansAfterDeposit();
    }

    /**
     * {@inheritDoc}
     */
    public function setNextPaymentDue($nextPaymentDue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNextPaymentDue', array($nextPaymentDue));

        return parent::setNextPaymentDue($nextPaymentDue);
    }

    /**
     * {@inheritDoc}
     */
    public function getNextPaymentDue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNextPaymentDue', array());

        return parent::getNextPaymentDue();
    }

    /**
     * {@inheritDoc}
     */
    public function setDueDate1($dueDate1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDueDate1', array($dueDate1));

        return parent::setDueDate1($dueDate1);
    }

    /**
     * {@inheritDoc}
     */
    public function getDueDate1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDueDate1', array());

        return parent::getDueDate1();
    }

    /**
     * {@inheritDoc}
     */
    public function setFinalPaymentDue($finalPaymentDue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFinalPaymentDue', array($finalPaymentDue));

        return parent::setFinalPaymentDue($finalPaymentDue);
    }

    /**
     * {@inheritDoc}
     */
    public function getFinalPaymentDue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFinalPaymentDue', array());

        return parent::getFinalPaymentDue();
    }

    /**
     * {@inheritDoc}
     */
    public function setDueDate2($dueDate2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDueDate2', array($dueDate2));

        return parent::setDueDate2($dueDate2);
    }

    /**
     * {@inheritDoc}
     */
    public function getDueDate2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDueDate2', array());

        return parent::getDueDate2();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientNotes($clientNotes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientNotes', array($clientNotes));

        return parent::setClientNotes($clientNotes);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientNotes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientNotes', array());

        return parent::getClientNotes();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdminNotes($adminNotes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdminNotes', array($adminNotes));

        return parent::setAdminNotes($adminNotes);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdminNotes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdminNotes', array());

        return parent::getAdminNotes();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateFrom($dateFrom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateFrom', array($dateFrom));

        return parent::setDateFrom($dateFrom);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateFrom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateFrom', array());

        return parent::getDateFrom();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateTo($dateTo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateTo', array($dateTo));

        return parent::setDateTo($dateTo);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateTo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateTo', array());

        return parent::getDateTo();
    }

    /**
     * {@inheritDoc}
     */
    public function setFlightTotalCost($flightTotalCost)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFlightTotalCost', array($flightTotalCost));

        return parent::setFlightTotalCost($flightTotalCost);
    }

    /**
     * {@inheritDoc}
     */
    public function getFlightTotalCost()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFlightTotalCost', array());

        return parent::getFlightTotalCost();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoOfDays($noOfDays)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoOfDays', array($noOfDays));

        return parent::setNoOfDays($noOfDays);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoOfDays()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoOfDays', array());

        return parent::getNoOfDays();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoomRequired($roomRequired)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoomRequired', array($roomRequired));

        return parent::setRoomRequired($roomRequired);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoomRequired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoomRequired', array());

        return parent::getRoomRequired();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoomRate($roomRate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoomRate', array($roomRate));

        return parent::setRoomRate($roomRate);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoomRate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoomRate', array());

        return parent::getRoomRate();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setPromo(\Base\Entity\InventoryPromo $promo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPromo', array($promo));

        return parent::setPromo($promo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPromo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPromo', array());

        return parent::getPromo();
    }

    /**
     * {@inheritDoc}
     */
    public function setMerchantFee($merchantFee)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMerchantFee', array($merchantFee));

        return parent::setMerchantFee($merchantFee);
    }

    /**
     * {@inheritDoc}
     */
    public function getMerchantFee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMerchantFee', array());

        return parent::getMerchantFee();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt($createdAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array($createdAt));

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt($updatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', array($updatedAt));

        return parent::setUpdatedAt($updatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', array());

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoOfPersons($noOfPersons)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoOfPersons', array($noOfPersons));

        return parent::setNoOfPersons($noOfPersons);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoOfPersons()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoOfPersons', array());

        return parent::getNoOfPersons();
    }

    /**
     * {@inheritDoc}
     */
    public function setExcursionCost($excursionCost)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExcursionCost', array($excursionCost));

        return parent::setExcursionCost($excursionCost);
    }

    /**
     * {@inheritDoc}
     */
    public function getExcursionCost()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExcursionCost', array());

        return parent::getExcursionCost();
    }

    /**
     * {@inheritDoc}
     */
    public function setTransferCost($transferCost)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTransferCost', array($transferCost));

        return parent::setTransferCost($transferCost);
    }

    /**
     * {@inheritDoc}
     */
    public function getTransferCost()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTransferCost', array());

        return parent::getTransferCost();
    }

    /**
     * {@inheritDoc}
     */
    public function setItemCost($itemCost)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setItemCost', array($itemCost));

        return parent::setItemCost($itemCost);
    }

    /**
     * {@inheritDoc}
     */
    public function getItemCost()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItemCost', array());

        return parent::getItemCost();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsDraft($isDraft)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsDraft', array($isDraft));

        return parent::setIsDraft($isDraft);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsDraft()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsDraft', array());

        return parent::getIsDraft();
    }

    /**
     * {@inheritDoc}
     */
    public function setReferenceNumber($referenceNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReferenceNumber', array($referenceNumber));

        return parent::setReferenceNumber($referenceNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getReferenceNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReferenceNumber', array());

        return parent::getReferenceNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setAffiliateId($affiliateId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAffiliateId', array($affiliateId));

        return parent::setAffiliateId($affiliateId);
    }

    /**
     * {@inheritDoc}
     */
    public function getAffiliateId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAffiliateId', array());

        return parent::getAffiliateId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsBooked($isBooked)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsBooked', array($isBooked));

        return parent::setIsBooked($isBooked);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsBooked()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsBooked', array());

        return parent::getIsBooked();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoomNetCost($roomNetCost)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoomNetCost', array($roomNetCost));

        return parent::setRoomNetCost($roomNetCost);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoomNetCost()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoomNetCost', array());

        return parent::getRoomNetCost();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddonsNetCost($addonsNetCost)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddonsNetCost', array($addonsNetCost));

        return parent::setAddonsNetCost($addonsNetCost);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddonsNetCost()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddonsNetCost', array());

        return parent::getAddonsNetCost();
    }

    /**
     * {@inheritDoc}
     */
    public function setAirportName($airportName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAirportName', array($airportName));

        return parent::setAirportName($airportName);
    }

    /**
     * {@inheritDoc}
     */
    public function getAirportName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAirportName', array());

        return parent::getAirportName();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiscountType($discountType)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiscountType', array($discountType));

        return parent::setDiscountType($discountType);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscountType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscountType', array());

        return parent::getDiscountType();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrencyCode($currencyCode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrencyCode', array($currencyCode));

        return parent::setCurrencyCode($currencyCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrencyCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrencyCode', array());

        return parent::getCurrencyCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsUpdated($isUpdated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsUpdated', array($isUpdated));

        return parent::setIsUpdated($isUpdated);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsUpdated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsUpdated', array());

        return parent::getIsUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsRefund($isRefund)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsRefund', array($isRefund));

        return parent::setIsRefund($isRefund);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsRefund()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsRefund', array());

        return parent::getIsRefund();
    }

    /**
     * {@inheritDoc}
     */
    public function setRefundAmt($refundAmt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRefundAmt', array($refundAmt));

        return parent::setRefundAmt($refundAmt);
    }

    /**
     * {@inheritDoc}
     */
    public function getRefundAmt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRefundAmt', array());

        return parent::getRefundAmt();
    }

    /**
     * {@inheritDoc}
     */
    public function setExtraAmtPaid($extraAmtPaid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExtraAmtPaid', array($extraAmtPaid));

        return parent::setExtraAmtPaid($extraAmtPaid);
    }

    /**
     * {@inheritDoc}
     */
    public function getExtraAmtPaid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExtraAmtPaid', array());

        return parent::getExtraAmtPaid();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsExtraPaid($isExtraPaid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsExtraPaid', array($isExtraPaid));

        return parent::setIsExtraPaid($isExtraPaid);
    }

    /**
     * {@inheritDoc}
     */
    public function getIsExtraPaid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsExtraPaid', array());

        return parent::getIsExtraPaid();
    }

    /**
     * {@inheritDoc}
     */
    public function setExtraDepAmt($extraDepAmt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExtraDepAmt', array($extraDepAmt));

        return parent::setExtraDepAmt($extraDepAmt);
    }

    /**
     * {@inheritDoc}
     */
    public function getExtraDepAmt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExtraDepAmt', array());

        return parent::getExtraDepAmt();
    }

    /**
     * {@inheritDoc}
     */
    public function getIsDeleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsDeleted', array());

        return parent::getIsDeleted();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsDeleted($isDeleted)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsDeleted', array($isDeleted));

        return parent::setIsDeleted($isDeleted);
    }

    /**
     * {@inheritDoc}
     */
    public function setServiceManager($sm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setServiceManager', array($sm));

        return parent::setServiceManager($sm);
    }

    /**
     * {@inheritDoc}
     */
    public function getServiceManager()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServiceManager', array());

        return parent::getServiceManager();
    }

    /**
     * {@inheritDoc}
     */
    public function getEntityManager()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntityManager', array());

        return parent::getEntityManager();
    }

    /**
     * {@inheritDoc}
     */
    public function getForm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getForm', array());

        return parent::getForm();
    }

    /**
     * {@inheritDoc}
     */
    public function getCollection()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCollection', array());

        return parent::getCollection();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray($object = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array($object));

        return parent::toArray($object);
    }

    /**
     * {@inheritDoc}
     */
    public function toJson()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toJson', array());

        return parent::toJson();
    }

    /**
     * {@inheritDoc}
     */
    public function setCollection($collection)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCollection', array($collection));

        return parent::setCollection($collection);
    }

    /**
     * {@inheritDoc}
     */
    public function save()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'save', array());

        return parent::save();
    }

}
