<?php

namespace DoctrineORMModule\Proxy\__CG__\Base\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class InventoryEvent extends \Base\Entity\InventoryEvent implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }



    /**
     * {@inheritDoc}
     * @param string $name
     * @param mixed  $value
     */
    public function __set($name, $value)
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__set', array($name, $value));

        return parent::__set($name, $value);
    }



    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'eventId', 'resortId', 'roomId', 'name', 'eventName', 'hotelName', 'roomCategory', 'totalAvailable', 'bookedCount', 'dateFrom', 'dateTo', 'netPrice', 'grossPrice', 'promo', 'pricePer', 'tripleOccupancyAllowed', 'extraPriceNet', 'extraPriceGross', 'malesCount', 'femalesCount', 'board', 'doubleOccupancyRate', 'quadOccupancy', 'singlePremiumOccupancy', 'singleShare', 'triplePriceFemaleNet', 'triplePriceFemaleGross', 'triplePriceMaleNet', 'triplePriceMaleGross', 'quadPriceFemaleNet', 'quadPriceFemaleGross', 'quadPriceMaleNet', 'quadPriceMaleGross', 'singlePriceGross', 'singlePriceNet', 'serviceManager');
        }

        return array('__isInitialized__', 'id', 'eventId', 'resortId', 'roomId', 'name', 'eventName', 'hotelName', 'roomCategory', 'totalAvailable', 'bookedCount', 'dateFrom', 'dateTo', 'netPrice', 'grossPrice', 'promo', 'pricePer', 'tripleOccupancyAllowed', 'extraPriceNet', 'extraPriceGross', 'malesCount', 'femalesCount', 'board', 'doubleOccupancyRate', 'quadOccupancy', 'singlePremiumOccupancy', 'singleShare', 'triplePriceFemaleNet', 'triplePriceFemaleGross', 'triplePriceMaleNet', 'triplePriceMaleGross', 'quadPriceFemaleNet', 'quadPriceFemaleGross', 'quadPriceMaleNet', 'quadPriceMaleGross', 'singlePriceGross', 'singlePriceNet', 'serviceManager');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (InventoryEvent $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', array($name));

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', array());

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventId($eventId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventId', array($eventId));

        return parent::setEventId($eventId);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventId', array());

        return parent::getEventId();
    }

    /**
     * {@inheritDoc}
     */
    public function setResortId($resortId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResortId', array($resortId));

        return parent::setResortId($resortId);
    }

    /**
     * {@inheritDoc}
     */
    public function getResortId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResortId', array());

        return parent::getResortId();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoomId($roomId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoomId', array($roomId));

        return parent::setRoomId($roomId);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoomId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoomId', array());

        return parent::getRoomId();
    }

    /**
     * {@inheritDoc}
     */
    public function setEventName($eventName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEventName', array($eventName));

        return parent::setEventName($eventName);
    }

    /**
     * {@inheritDoc}
     */
    public function getEventName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEventName', array());

        return parent::getEventName();
    }

    /**
     * {@inheritDoc}
     */
    public function setHotelName($hotelName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHotelName', array($hotelName));

        return parent::setHotelName($hotelName);
    }

    /**
     * {@inheritDoc}
     */
    public function getHotelName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHotelName', array());

        return parent::getHotelName();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoomCategory($roomCategory)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoomCategory', array($roomCategory));

        return parent::setRoomCategory($roomCategory);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoomCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoomCategory', array());

        return parent::getRoomCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalAvailable($totalAvailable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalAvailable', array($totalAvailable));

        return parent::setTotalAvailable($totalAvailable);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalAvailable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalAvailable', array());

        return parent::getTotalAvailable();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateFrom($dateFrom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateFrom', array($dateFrom));

        return parent::setDateFrom($dateFrom);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateFrom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateFrom', array());

        return parent::getDateFrom();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateTo($dateTo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateTo', array($dateTo));

        return parent::setDateTo($dateTo);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateTo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateTo', array());

        return parent::getDateTo();
    }

    /**
     * {@inheritDoc}
     */
    public function setNetPrice($netPrice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNetPrice', array($netPrice));

        return parent::setNetPrice($netPrice);
    }

    /**
     * {@inheritDoc}
     */
    public function getNetPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNetPrice', array());

        return parent::getNetPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setGrossPrice($grossPrice)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrossPrice', array($grossPrice));

        return parent::setGrossPrice($grossPrice);
    }

    /**
     * {@inheritDoc}
     */
    public function getGrossPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrossPrice', array());

        return parent::getGrossPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setPromo(\Base\Entity\InventoryPromo $promo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPromo', array($promo));

        return parent::setPromo($promo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPromo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPromo', array());

        return parent::getPromo();
    }

    /**
     * {@inheritDoc}
     */
    public function setPricePer($pricePer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPricePer', array($pricePer));

        return parent::setPricePer($pricePer);
    }

    /**
     * {@inheritDoc}
     */
    public function getPricePer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPricePer', array());

        return parent::getPricePer();
    }

    /**
     * {@inheritDoc}
     */
    public function setTripleOccupancyAllowed($tripleOccupancyAllowed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTripleOccupancyAllowed', array($tripleOccupancyAllowed));

        return parent::setTripleOccupancyAllowed($tripleOccupancyAllowed);
    }

    /**
     * {@inheritDoc}
     */
    public function getTripleOccupancyAllowed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTripleOccupancyAllowed', array());

        return parent::getTripleOccupancyAllowed();
    }

    /**
     * {@inheritDoc}
     */
    public function setExtraPriceNet($extraPriceNet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExtraPriceNet', array($extraPriceNet));

        return parent::setExtraPriceNet($extraPriceNet);
    }

    /**
     * {@inheritDoc}
     */
    public function getExtraPriceNet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExtraPriceNet', array());

        return parent::getExtraPriceNet();
    }

    /**
     * {@inheritDoc}
     */
    public function setExtraPriceGross($extraPriceGross)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExtraPriceGross', array($extraPriceGross));

        return parent::setExtraPriceGross($extraPriceGross);
    }

    /**
     * {@inheritDoc}
     */
    public function getExtraPriceGross()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExtraPriceGross', array());

        return parent::getExtraPriceGross();
    }

    /**
     * {@inheritDoc}
     */
    public function setFemalesCount($femalesCount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFemalesCount', array($femalesCount));

        return parent::setFemalesCount($femalesCount);
    }

    /**
     * {@inheritDoc}
     */
    public function getFemalesCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFemalesCount', array());

        return parent::getFemalesCount();
    }

    /**
     * {@inheritDoc}
     */
    public function setMalesCount($malesCount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMalesCount', array($malesCount));

        return parent::setMalesCount($malesCount);
    }

    /**
     * {@inheritDoc}
     */
    public function getMalesCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMalesCount', array());

        return parent::getMalesCount();
    }

    /**
     * {@inheritDoc}
     */
    public function setBookedCount($bookedCount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBookedCount', array($bookedCount));

        return parent::setBookedCount($bookedCount);
    }

    /**
     * {@inheritDoc}
     */
    public function getBookedCount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBookedCount', array());

        return parent::getBookedCount();
    }

    /**
     * {@inheritDoc}
     */
    public function setBoard($board)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBoard', array($board));

        return parent::setBoard($board);
    }

    /**
     * {@inheritDoc}
     */
    public function getBoard()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBoard', array());

        return parent::getBoard();
    }

    /**
     * {@inheritDoc}
     */
    public function setDoubleOccupancyRate($doubleOccupancyRate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDoubleOccupancyRate', array($doubleOccupancyRate));

        return parent::setDoubleOccupancyRate($doubleOccupancyRate);
    }

    /**
     * {@inheritDoc}
     */
    public function getDoubleOccupancyRate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDoubleOccupancyRate', array());

        return parent::getDoubleOccupancyRate();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuadOccupancy($quadOccupancy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuadOccupancy', array($quadOccupancy));

        return parent::setQuadOccupancy($quadOccupancy);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuadOccupancy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuadOccupancy', array());

        return parent::getQuadOccupancy();
    }

    /**
     * {@inheritDoc}
     */
    public function setSinglePremiumOccupancy($singlePremiumOccupancy)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSinglePremiumOccupancy', array($singlePremiumOccupancy));

        return parent::setSinglePremiumOccupancy($singlePremiumOccupancy);
    }

    /**
     * {@inheritDoc}
     */
    public function getSinglePremiumOccupancy()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSinglePremiumOccupancy', array());

        return parent::getSinglePremiumOccupancy();
    }

    /**
     * {@inheritDoc}
     */
    public function setSingleShare($singleShare)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSingleShare', array($singleShare));

        return parent::setSingleShare($singleShare);
    }

    /**
     * {@inheritDoc}
     */
    public function getSingleShare()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSingleShare', array());

        return parent::getSingleShare();
    }

    /**
     * {@inheritDoc}
     */
    public function setTriplePriceFemaleNet($triplePriceFemaleNet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTriplePriceFemaleNet', array($triplePriceFemaleNet));

        return parent::setTriplePriceFemaleNet($triplePriceFemaleNet);
    }

    /**
     * {@inheritDoc}
     */
    public function getTriplePriceFemaleNet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTriplePriceFemaleNet', array());

        return parent::getTriplePriceFemaleNet();
    }

    /**
     * {@inheritDoc}
     */
    public function setTriplePriceFemaleGross($triplePriceFemaleGross)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTriplePriceFemaleGross', array($triplePriceFemaleGross));

        return parent::setTriplePriceFemaleGross($triplePriceFemaleGross);
    }

    /**
     * {@inheritDoc}
     */
    public function getTriplePriceFemaleGross()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTriplePriceFemaleGross', array());

        return parent::getTriplePriceFemaleGross();
    }

    /**
     * {@inheritDoc}
     */
    public function setTriplePriceMaleNet($triplePriceMaleNet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTriplePriceMaleNet', array($triplePriceMaleNet));

        return parent::setTriplePriceMaleNet($triplePriceMaleNet);
    }

    /**
     * {@inheritDoc}
     */
    public function getTriplePriceMaleNet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTriplePriceMaleNet', array());

        return parent::getTriplePriceMaleNet();
    }

    /**
     * {@inheritDoc}
     */
    public function setTriplePriceMaleGross($triplePriceMaleGross)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTriplePriceMaleGross', array($triplePriceMaleGross));

        return parent::setTriplePriceMaleGross($triplePriceMaleGross);
    }

    /**
     * {@inheritDoc}
     */
    public function getTriplePriceMaleGross()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTriplePriceMaleGross', array());

        return parent::getTriplePriceMaleGross();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuadPriceFemaleNet($quadPriceFemaleNet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuadPriceFemaleNet', array($quadPriceFemaleNet));

        return parent::setQuadPriceFemaleNet($quadPriceFemaleNet);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuadPriceFemaleNet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuadPriceFemaleNet', array());

        return parent::getQuadPriceFemaleNet();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuadPriceFemaleGross($quadPriceFemaleGross)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuadPriceFemaleGross', array($quadPriceFemaleGross));

        return parent::setQuadPriceFemaleGross($quadPriceFemaleGross);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuadPriceFemaleGross()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuadPriceFemaleGross', array());

        return parent::getQuadPriceFemaleGross();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuadPriceMaleNet($quadPriceMaleNet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuadPriceMaleNet', array($quadPriceMaleNet));

        return parent::setQuadPriceMaleNet($quadPriceMaleNet);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuadPriceMaleNet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuadPriceMaleNet', array());

        return parent::getQuadPriceMaleNet();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuadPriceMaleGross($quadPriceMaleGross)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuadPriceMaleGross', array($quadPriceMaleGross));

        return parent::setQuadPriceMaleGross($quadPriceMaleGross);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuadPriceMaleGross()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuadPriceMaleGross', array());

        return parent::getQuadPriceMaleGross();
    }

    /**
     * {@inheritDoc}
     */
    public function setSinglePriceGross($singlePriceGross)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSinglePriceGross', array($singlePriceGross));

        return parent::setSinglePriceGross($singlePriceGross);
    }

    /**
     * {@inheritDoc}
     */
    public function getSinglePriceGross()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSinglePriceGross', array());

        return parent::getSinglePriceGross();
    }

    /**
     * {@inheritDoc}
     */
    public function setSinglePriceNet($singlePriceNet)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSinglePriceNet', array($singlePriceNet));

        return parent::setSinglePriceNet($singlePriceNet);
    }

    /**
     * {@inheritDoc}
     */
    public function getSinglePriceNet()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSinglePriceNet', array());

        return parent::getSinglePriceNet();
    }

    /**
     * {@inheritDoc}
     */
    public function setServiceManager($sm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setServiceManager', array($sm));

        return parent::setServiceManager($sm);
    }

    /**
     * {@inheritDoc}
     */
    public function getServiceManager()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getServiceManager', array());

        return parent::getServiceManager();
    }

    /**
     * {@inheritDoc}
     */
    public function getEntityManager()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntityManager', array());

        return parent::getEntityManager();
    }

    /**
     * {@inheritDoc}
     */
    public function getForm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getForm', array());

        return parent::getForm();
    }

    /**
     * {@inheritDoc}
     */
    public function getCollection()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCollection', array());

        return parent::getCollection();
    }

    /**
     * {@inheritDoc}
     */
    public function toArray($object = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array($object));

        return parent::toArray($object);
    }

    /**
     * {@inheritDoc}
     */
    public function toJson()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toJson', array());

        return parent::toJson();
    }

    /**
     * {@inheritDoc}
     */
    public function setCollection($collection)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCollection', array($collection));

        return parent::setCollection($collection);
    }

    /**
     * {@inheritDoc}
     */
    public function save()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'save', array());

        return parent::save();
    }

}
