<?php

//d($this->collection[0]->getPaySchedule());
if (!is_null($this->message)):
    
   // d($this->message);
    if ($this->message):
        ?>		
        <div class="alert alert-dismissable alert-<?php echo $this->message[0]['type']; ?>">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <ul>
                <li><?php echo $this->message[0]['message']; ?></li>        
            </ul>
        </div>
        <?php
    endif;
endif;
?>

<?php
$date = date('Y-m-d');
//d($this->collection); die; //echo $date; die;
?>

<script>
    $(function() {
        $('#myselect option[value=<?php
if (!empty($this->paymenttyp)) {
    echo $this->paymenttyp;
} else {
    echo '';
}
?>]').attr('selected', 'selected');
    });
</script>    

<div class="grid">
    <div class="grid-title">
        <div class="pull-left">
            <div class="icon-title">
                <i class="icon-list"></i>
            </div> 
            <span>Payments</span>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
<div class="grid">    
    <div class="grid-content overflow">


      
        <table class="table table-bordered table-mod-2" id="datatable_3">
            <thead>
                <tr>                    
                 <!--   <th class="hidden-mobile">Reservation No.</th> -->
                    <th class="hidden-mobile">Agent Name</th>
                    <th class="hidden-mobile">Role</th> 

                    <th class="hidden-mobile">Total Commission Earned</th>
                
                    <th class="hidden-mobile">Actions</th>

                </tr>
            </thead>
            <tbody>
                <?php
      
                $i = 0;
              
                foreach ($this->collection as $item):
//                    d($item);
                ?>                  

                    <tr>
                      <td class="hidden-mobile"><?php
                           echo $item['collection']->getFirstName(). " ". $item['collection']->getLastName();
                            ?></td>
                        <td class="hidden-mobile"><?php echo $item['collection']->getRole()->getName();?></td>    

                     
                        <td class="hidden-mobile">$<?php echo $item['earned']; ?> </td> 
                        <td class="action-table">                            
                       
<!--                                <a href="javascript:alert('In Progress...')<?php //echo $this->url('payroll-edit', array('id' => $item->getId())); ?>" title="Update">
                                    <img src="/images/icon/table_edit.png" alt="Update">
                                </a> 
                            
                                <a href="javascript:alert('In Progress...')<?php //echo $this->url('payroll-view', array('id' => $item->getId())); ?>" title="View">
                                    <img src="/images/icon/table_view.png" alt="View">
                               </a>-->
                                <a href="<?php echo $this->url('commission-set', array('id' => $item['collection']->getId())); ?>" title="Set Commission Rate">
                                Set Commission Rate
                               </a>
                        </td>

                    </tr>                    
                <?php endforeach; ?>
            </tbody>
        </table>
       
        <div class="clearfix"></div>
    </div>
</div>
<?php //echo $this->partial('payments/ajax/modal.phtml'); ?>

