<?php //echo "edit view"; die;        ?>

<?php
$form = $this->form;
$form->prepare();
//d($form->get('paySchedule')->getValue());

$form->setAttribute('action', $this->url(
                'payroll-edit', array('id' => $form->get('id')->getValue())
));
$form->setAttribute('method', 'post');
?>
<div class="grid">
    <div class="grid-title">
        <div class="pull-left">
            <div class="icon-title">
                <i class="icon-plus"></i>
            </div>
            <span>Update Payroll</span>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
    <?php echo $this->form()->openTag($form); ?>
    <div class="grid-content">
        <div class="formRow control-group">                        



            <input type="hidden" id="today" value="<?php echo date('Y-m-d'); ?>">


            <div class="formRow control-group">
                <h4>Accounts</h4>
                <hr />
            </div>


            <div class="formRow control-group">
                
                
                 <div class="formRow control-group">
                    <?php echo $this->formLabel($form->get('rate')); ?>
                    <div class="formRight">
                        <?php echo $this->formElement($form->get('rate')->setAttribute('class', 'span input')); ?>
                        <?php echo $this->formElementErrors($form->get('rate'), array('class' => 'help-inline')); ?>
                    </div>
                </div>
                
                            
                
                <div class="formRow control-group">
                      
                       <label for="accountType">Type</label>
                         <div class="formRight">
                       <div name="accountType" class="distance distance-2">
                        <p>
                            <input type="radio" id="salary" class="load-entity" name="accountType" <?php if($form->get('accountType')->getValue() == 0){echo "checked='checked'";}?> value="0" >
                            <label for="salary"><span></span>Salary</label>
                        </p>
                        <p>
                            <input type="radio" id="commision" class="load-entity" <?php if($form->get('accountType')->getValue() == 1){echo "checked='checked'";}?> name="accountType" value="1" >
                            <label for="commision"><span></span>commision</label>
                        </p>
                        
                    </div>
                      
                      </div>
                    
                </div>
                
                  <div class="formRow control-group">
                      
                       <label for="paySchedule">Schedule</label>
                         <div class="formRight">
                       <div name="paySchedule" class="distance distance-2">
                        <p>
                            <input type="radio" id="weekly" class="load-entity" name="paySchedule" <?php if($form->get('paySchedule')->getValue() == 0){echo "checked='checked'";}?> value="0" >
                            <label for="weekly"><span></span>Weekly</label>
                        </p>
                        <p>
                            <input type="radio" id="bi-weekly" class="load-entity" <?php if($form->get('paySchedule')->getValue() == 1){echo "checked='checked'";}?> name="paySchedule" value="1" >
                            <label for="bi-weekly"><span></span>Bi-Weekly</label>
                        </p>
                         <p>
                            <input type="radio" id="monthly" class="load-entity" name="paySchedule" <?php if($form->get('paySchedule')->getValue() == 2){echo "checked='checked'";}?> value="2" >
                            <label for="monthly"><span></span>Monthly</label>
                        </p>
                    </div>
                      
                      </div>
                    
                </div>
                
                
                  <div class="formRow control-group">
                      
                       <label for="bonus">Bonus</label>
                         <div class="formRight">
                       <div name="bonus" class="distance distance-2">
                        <p>
                            <input type="radio" id="one-time" class="load-entity" name="bonus" <?php if($form->get('bonus')->getValue() == 0){echo "checked='checked'";}?> value="0" >
                            <label for="one-time"><span></span>One Time</label>
                        </p>
                        <p>
                            <input type="radio" id="recurring" class="load-entity" <?php if($form->get('bonus')->getValue() == 1){echo "checked='checked'";}?> name="bonus" value="1" >
                            <label for="recurring"><span></span>Recurring</label>
                        </p>
                        
                    </div>
                      
                      </div>
                    
                </div>
                
                
                
                <div class="formRow control-group">
                    <?php echo $this->formLabel($form->get('role')); ?>
                    <div class="formRight">
                        <?php echo $this->formElement($form->get('role')->setAttribute('class', 'chzn-select chosen_select width-100')); ?>
                        <?php echo $this->formElementErrors($form->get('role'), array('class' => 'help-inline')); ?>
                    </div>
                </div>
           
            
            
            </div>

        </div>

        <div class="formRow control-group">
            <?php ?>
            <button id="submitbtn" class="btn btn-success" type="submit"  name="submit" onclick=''>Update</button>


        </div>


        <div id="ajax-script"></div>
        <div class="clearfix"></div>

    </div>
    <?php echo $this->form()->closeTag() ?>
</div>
</div>
<?php //echo $this->partial('orders/ajax/modal.phtml');    ?>
<script src="/js/date-formater.js"></script>
<script src="/js/reservation.js"></script>
<script>

    $(function() {
        $('.grid-content .formRow ul.help-inline').parents('.formRow').addClass('error');
        $('.error input').keyup(function() {
            $(this).parents('.formRow').removeClass('error');
            $(this).next('ul.help-inline').remove();
        });




    });



</script>
