<?php

//d($this->collection[0]->getPaySchedule());
if (!is_null($this->message)):
    
   // d($this->message);
    if ($this->message):
        ?>		
        <div class="alert alert-dismissable alert-<?php echo $this->message[0]['type']; ?>">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <ul>
                <li><?php echo $this->message[0]['message']; ?></li>        
            </ul>
        </div>
        <?php
    endif;
endif;
?>

<?php
$date = date('Y-m-d');
//d($this->collection); die; //echo $date; die;
?>

<script>
    $(function() {
        $('#myselect option[value=<?php
if (!empty($this->paymenttyp)) {
    echo $this->paymenttyp;
} else {
    echo '';
}
?>]').attr('selected', 'selected');
    });
</script>    

<div class="grid">
    <div class="grid-title">
        <div class="pull-left">
            <div class="icon-title">
                <i class="icon-list"></i>
            </div> 
            <span>Payments</span>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
<div class="grid">    
    <div class="grid-content overflow">


      
        <table class="table table-bordered table-mod-2" id="datatable_3">
            <thead>
                <tr>                    
                 <!--   <th class="hidden-mobile">Reservation No.</th> -->
                    <th class="hidden-mobile">Agent Name</th>
                    <th class="hidden-mobile">Role</th> 

                    <th class="hidden-mobile">Payment Type</th>
                    <th class="hidden-mobile">Payment Schedule</th>
                    <th class="hidden-mobile">Rate</th>
                    <th class="hidden-mobile">Next Payment Date</th>
                    <th class="hidden-mobile">Status</th>
                    <th class="hidden-mobile">Actions</th>

                </tr>
            </thead>
            <tbody>
                <?php
      
                $i = 0;
              
                foreach ($this->collection as $item):

                               $salaryType=$item->getPaySchedule();
                
           //     print_r($salaryType);
                ?>                  

                    <tr>
                      <td class="hidden-mobile"><?php
                           echo $item->getFirstName(). " ". $item->getLastName();
                            ?></td>
                        <td class="hidden-mobile"><?php echo $item->getRole()->getName();?></td>    

                        <td class="hidden-mobile"> <?php echo 'Salary';?></td>				

                        <td class="hidden-mobile"><?php if($salaryType==0){ echo 'Weekly';}elseif($salaryType==1){echo 'Bi-Weekly';}else{echo 'Monthly';}?></td>

                        <td class="hidden-mobile"><?php echo '$' . $item->getRate(); ?></td>

                        <td class="hidden-mobile"><?php echo '-'; ?></td>
     
                           <td class="hidden-mobile">
                            <span class="s_<?php echo $item->getIsActive() ? 'green' : 'gray'; ?>">
                                 <?php echo $item->getIsActive() ? 'Active' : 'Blocked'; ?>
                            </span>
                        </td>
                        <td class="action-table">                            
                       
                                <a href="<?php echo $this->url('payroll-edit', array('id' => $item->getId())); ?>" title="Update">
                                    <img src="/images/icon/table_edit.png" alt="Update">
                                </a> 
                            
                                <a href="<?php echo $this->url('payroll-view', array('id' => $item->getId())); ?>" title="View">
                                    <img src="/images/icon/table_view.png" alt="View">
                               </a>
                                <a href="javascript:alert('In Progress...')<?php //echo $this->url('payments-applypayment', array('id' => $reservation->getId())); ?>" title="Apply">
                                <img src="/images/icon/icon_cont_check.png" alt="Apply">
                               </a>
                        </td>

                    </tr>                    
                <?php endforeach; ?>
            </tbody>
        </table>
       
        <div class="clearfix"></div>
    </div>
</div>
<?php //echo $this->partial('payments/ajax/modal.phtml'); ?>

