<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Inventory\Module'                        => __DIR__ . '/Module.php',
    'Inventory\Controller\ResortRoomsController' => __DIR__ . '/src/Inventory/Controller/ResortRoomsController.php',
    'InventoryTest\Framework\TestCase'        => __DIR__ . '/tests/Inventory/Framework/TestCase.php',
    'InventoryTest\SampleTest'                => __DIR__ . '/tests/Inventory/SampleTest.php',
);
