<?php

if (!is_null($this->message)):
    if ($this->message):
        ?>		
        <div class="alert alert-dismissable alert-<?php echo $this->message[0]['type']; ?>">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <ul>
                <li><?php echo $this->message[0]['message']; ?></li>        
            </ul>
        </div>
        <?php
    endif;
endif;
?>

<div class="grid">

    <div class="grid-title">
        <div class="pull-left">
            <div class="icon-title">
                <i class="icon-list"></i>
            </div>
            <span>Roles</span>
            <div class="clearfix"></div>
        </div>
        <div class="pull-right">
            <div class="icon-title">
                <a href="<?php echo $this->url('acl-add'); ?>"><i class="icon-plus-sign"></i></a>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>

    <div class="grid-content overflow">

        <table class="table table-bordered table-mod-2" id="datatable_3">
            <thead>
                <tr>
                    <th class="t_center">
                        <input type="checkbox" id="c0" name="cc" />
                        <label for="c0"><span></span></label>
                    </th>
                    <th class="hidden-mobile">Role Name</th>
                    <th class="hidden-mobile">Description</th>
                    <th class="hidden-mobile">Total User</th>
                    <th class="hidden-mobile">Status</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <?php
                $i = 1;
                foreach ($this->collection as $item):
                    ?>
                    <tr>
                        <td class="t_center">
                            <input type="checkbox" id="c<?php echo $i; ?>" name="cc" />
                            <label for="c<?php echo $i; ?>"><span></span></label>
                        </td>
                        <td><?php echo $item->getName(); ?></td>

                        <td class="hidden-mobile">

                            <?php echo $item->getDescription() ? substr(strip_tags($item->getDescription()), 0, 50) . '...' : '-' ?>

                        </td>


                        <td class="hidden-mobile">

                            <?php
                            foreach ($this->usercount as $result) {

                                if ($result[0]->getRole()->getId() == $item->getId()) {
                                    // echo '<pre>' . $result[0]->getRole()->getId();
                                    // echo '<br>';
                                    echo $result['count_role'];
                                }
                            } //echo 
                            ?>
                        </td>

                        <td class="hidden-mobile">
                            <span class="s_<?php echo $item->getIsActive() ? 'green' : 'gray'; ?>">
                                <?php echo $item->getIsActive() ? 'Enabled' : 'Disabled'; ?>
                            </span>
                        </td>
                        <td class="action-table">
                            <a href="<?php echo $this->url('acl-edit', array('id' => $item->getId())); ?>">
                                <img src="/images/icon/table_edit.png" alt="">
                            </a>
                            <a href="<?php echo $this->url('acl-suspend', array('id' => $item->getId())); ?>">
                              <!--  <img src="/images/icon/table_edit.png" alt="">--> Suspend
                            </a>
                            <a href="<?php echo $this->url('acl-delete', array('id' => $item->getId())); ?>"
                               data-confirm="Are you sure?">						
                                <img src="/images/icon/table_del.png" alt="">
                            </a>
                        </td>
                    </tr>
                    <?php $i++; ?>
                <?php endforeach; ?>
            </tbody>
        </table>


        <div class="clearfix"></div>
    </div>

</div>