<?php
$form = $this->form;

$form->prepare();
$form->setAttribute('action', $this->url(
                'inventory-transfers-edit', array('id' => $form->get('id')->getValue())
));

$form->setAttribute('method', 'post');

if ($form->get('dateFrom')->getValue() instanceof DateTime)
    $form->get('dateFrom')->setValue($form->get('dateFrom')->getValue()->format('Y-m-d')); // DateTime to str fix;
if ($form->get('dateTo')->getValue() instanceof DateTime)
    $form->get('dateTo')->setValue($form->get('dateTo')->getValue()->format('Y-m-d')); // DateTime to str fix;
?>
<div class="grid">
    <div class="grid-title">
        <div class="pull-left">
            <div class="icon-title">
                <i class="icon-plus"></i>
            </div>
            <span>Edit Transfer</span>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
<?php echo $this->form()->openTag($form); ?>
    <div class="grid-content">

        <div class="formRow control-group">
<?php echo $this->formLabel($form->get('transferName')); ?>
            <div class="formRight">
            <?php echo $this->formElement($form->get('transferName')->setAttribute('class', 'span input')); ?>
                <?php echo $this->formElementErrors($form->get('transferName'), array('class' => 'help-inline')); ?>
            </div>
        </div>

        <div class="formRow control-group">
<?php echo $this->formLabel($form->get('linkedTo')); ?>
            <div class="formRight">
            <?php echo $this->formElement($form->get('linkedTo')->setAttribute('class', 'chzn-select chosen_select width-100')); ?>
                <?php echo $this->formElementErrors($form->get('linkedTo'), array('class' => 'help-inline')); ?>
            </div>
        </div>
        <div id="ajax-data" class="formRow control-group">
<?php if ($form->get('resortId')->getValue() && $form->get('linkedTo')->getValue() == 1): ?>    
                <div class="formRow control-group">
                <?php echo $this->formLabel($form->get('resortId')); ?>
                    <div class="formRight">
                    <?php echo $this->formElement($form->get('resortId')->setAttribute('class', 'chzn-select chosen_select width-100')); ?>
                    <?php echo $this->formElementErrors($form->get('resortId'), array('class' => 'help-inline')); ?>
                    </div>
                </div>
                    <?php endif; ?>

            <?php if ($form->get('eventId')->getValue() && $form->get('linkedTo')->getValue() == 2): ?>    
                <div class="formRow control-group">
                <?php echo $this->formLabel($form->get('eventId')); ?>
                    <div class="formRight">
                <?php echo $this->formElement($form->get('eventId')->setAttribute('class', 'chzn-select chosen_select width-100')); ?>
                    <?php echo $this->formElementErrors($form->get('eventId'), array('class' => 'help-inline')); ?>
                    </div>
                </div>
                    <?php endif; ?>

<?php if ($form->get('cruiseId')->getValue() && $form->get('linkedTo')->getValue() == 3): ?>    
                <div class="formRow control-group">
                <?php echo $this->formLabel($form->get('cruiseId')); ?>
                    <div class="formRight">
                <?php echo $this->formElement($form->get('cruiseId')->setAttribute('class', 'chzn-select chosen_select width-100')); ?>
                <?php echo $this->formElementErrors($form->get('cruiseId'), array('class' => 'help-inline')); ?>
                    </div>
                </div>
                    <?php endif; ?>
        </div>

        <!--            <div class="formRow control-group">
            <?php //echo $this->formLabel($form->get('resortId'));  ?>
                            <div class="formRight">
<?php //echo $this->formElement($form->get('resortId')->setAttribute('class', 'chzn-select chosen_select width-100'));  ?>
<?php //echo $this->formElementErrors($form->get('resortId'), array('class' => 'help-inline'));  ?>
                            </div>
                    </div>	        -->

        <?php //echo $this->formElement($form->get('hotelName')); ?>    

        <div class="formRow control-group">
<?php echo $this->formLabel($form->get('supplierName')); ?>
            <div class="formRight">
        <?php echo $this->formElement($form->get('supplierName')->setAttribute('class', 'span input')); ?>
<?php echo $this->formElementErrors($form->get('supplierName'), array('class' => 'help-inline')); ?>
            </div>
        </div>
        <!--             <div class="formRow control-group">
                <?php //echo $this->formLabel($form->get('dateFrom')); ?>
                            <div class="formRight">
<?php
//echo $this->formElement($form->get('dateFrom')
//   ->setAttribute('class', 'span input')
//   ->setAttribute('min' , $form->get('dateFrom')->getValue())
//  );
?>
        <?php //echo $this->formElementErrors($form->get('dateFrom'), array('class' => 'help-inline')); ?>
                            </div>
                    </div>      
                    <div class="formRow control-group">
        <?php //echo $this->formLabel($form->get('dateTo')); ?>
                            <div class="formRight">
<?php
//echo $this->formElement($form->get('dateTo')
//     ->setAttribute('class', 'span input')
//      ->setAttribute('min' , $form->get('dateFrom')->getValue())
//      );
?>
        <?php //echo $this->formElementErrors($form->get('dateTo'), array('class' => 'help-inline')); ?>
                            </div>
                    </div>            -->

        <div class="formRow control-group">
<?php echo $this->formLabel($form->get('email')); ?>
            <div class="formRight">
<?php echo $this->formElement($form->get('email')->setAttribute('class', 'span input')); ?>
            <?php echo $this->formElementErrors($form->get('email'), array('class' => 'help-inline')); ?>
            </div>
        </div>

        <div class="formRow control-group">
<?php echo $this->formLabel($form->get('phone')); ?>
            <div class="formRight">
<?php echo $this->formElement($form->get('phone')->setAttribute('class', 'span input')); ?>
            <?php echo $this->formElementErrors($form->get('phone'), array('class' => 'help-inline')); ?>
            </div>
        </div>

        <div class="formRow control-group">
<?php echo $this->formLabel($form->get('numberAvailable')); ?>
            <div class="formRight">
<?php echo $this->formElement($form->get('numberAvailable')->setAttribute('class', 'span input')); ?>
            <?php echo $this->formElementErrors($form->get('numberAvailable'), array('class' => 'help-inline')); ?>
            </div>
        </div>   

        <div class="formRow control-group">
<?php echo $this->formLabel($form->get('netPrice')); ?>
            <div class="formRight">
<?php echo $this->formElement($form->get('netPrice')->setAttribute('class', 'span input')); ?>
            <?php echo $this->formElementErrors($form->get('netPrice'), array('class' => 'help-inline')); ?>
            </div>
        </div>            
        <div class="formRow control-group">
                <?php echo $this->formLabel($form->get('grossPrice')); ?>
            <div class="formRight">
<?php echo $this->formElement($form->get('grossPrice')->setAttribute('class', 'span input')); ?>
            <?php echo $this->formElementErrors($form->get('grossPrice'), array('class' => 'help-inline')); ?>
            </div>
        </div>    
        
         <div class="formRow control-group">
                <?php echo $this->formLabel($form->get('costMultiplier')); ?>
            <div class="formRight multicheckbox">
<?php echo $this->formElement($form->get('costMultiplier')->setAttribute('class', 'span input')); ?>
            <?php echo $this->formElementErrors($form->get('costMultiplier'), array('class' => 'help-inline')); ?>
            </div>
        </div>    
                           
        <div class="formRow control-group">
                <?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-info')) ?>
            <input id="resetbutton" class="btn btn-info" type="reset" value="Reset" name="reset"></input>
        </div>
        <div class="clearfix"></div>

    </div>
<?php echo $this->form()->closeTag() ?>
</div>

<script>
    $(function() {
        $('.grid-content .formRow ul.help-inline').parents('.formRow').addClass('error');
        $('.error input').keyup(function() {
            $(this).parents('.formRow').removeClass('error');
            $(this).next('ul.help-inline').remove();
        });

        $('select[name="resortId"]').change(function() {
            console.log($(this + ':selected').text());
            $('input[name="hotelName"]').val($(this + ':selected').text());
        });

        $('#linkedTo').change(function() {
            var id = $(this).val();
            switch (id) {
                case '4':
                    $.get('/admin/inventory/ajax/resorts', function(data) {
                        $('#ajax-data').html(data);
                    });
                    break;
                case '6':
                    {
                        $.get('/admin/inventory/ajax/events', function(data) {
                            $('#ajax-data').html(data);
                        });
                        break;
                    }
                case '7':
                    $.get('/admin/inventory/ajax/cruises', function(data) {
                        $('#ajax-data').html(data);
                    });
                    break;
                default:
                    $('#ajax-data').html(null);
                    break;
            }
        });
    });
</script>


