<ul class="additional-menu">
	
    <li class="menu-group">
        <a href="<?php echo $this->url('orders'); ?>">
            <i class="icon-home"></i>Reservation Manager
        </a>
        <ul>
            <li <?php if ($this->url() === $this->url('orders')) echo 'class="active"' ?>>
                <a href="<?php echo $this->url('orders'); ?>"><i class="icon-list"></i> View All</a>
            </li>


	    <li <?php if ($this->url() === $this->url('orders-event')) echo 'class="active"' ?>>
                <a href="<?php echo $this->url('orders-event'); ?>"><i class="icon-list"></i> Events</a>
            </li>


	
	    <li <?php if ($this->url() === $this->url('orders-resort')) echo 'class="active"' ?>>
                <a href="<?php echo $this->url('orders-resort'); ?>"><i class="icon-list"></i> Resorts</a>
            </li>	


	    <li <?php if ($this->url() === $this->url('orders-cruise')) echo 'class="active"' ?>>
                <a href="<?php echo $this->url('orders-cruise'); ?>"><i class="icon-list"></i> Cruises</a>
            </li>	


	    <li <?php if ($this->url() === $this->url('orders-cancel')) echo 'class="active"' ?>>
                <a href="<?php echo $this->url('orders-cancel'); ?>"><i class="icon-list"></i> Cancelled</a>
            </li>
	    
	     <li <?php if ($this->url() === $this->url('orders-draft')) echo 'class="active"' ?>>
                <a href="<?php echo $this->url('orders-draft'); ?>"><i class="icon-list"></i> Drafts</a>
            </li>		
	
		
	     <li <?php if ($this->url() === $this->url('orders-pending')) echo 'class="active"' ?>>
                <a href="<?php echo $this->url('orders-pending'); ?>"><i class="icon-list"></i> Pending</a>
            </li>	

            <li <?php if ($this->url() === $this->url('orders-rooms-search')) echo 'class="active"' ?>>
                <a href="<?php echo $this->url('orders-rooms-search'); ?>"><i class="icon-plus"></i> Create</a>
            </li>




        </ul>
    </li>

    <li class="menu-group">
        <a href="<?php echo $this->url('invoice'); ?>"><i class="icon-globe"></i>Invoce</a>
        <ul>
            <li <?php if ($this->url() === $this->url('invoice')) echo 'class="active"' ?> >
                <a href="<?php echo $this->url('invoice'); ?>"><i class="icon-list"></i>View Invoces</a>
            </li>	
            <li <?php if ($this->url() === $this->url('invoice-add')) echo 'class="active"' ?>>
                <a href="<?php echo $this->url('invoice-add'); ?>"><i class="icon-plus"></i> Add Invoce</a>
            </li>
        </ul>
    </li>
</ul>
