<ul class="additional-menu">
	
    <li class="menu-group">
        <a href="<?php echo $this->url('promos'); ?>">
            <i class="icon-home"></i>Sales
        </a>
        <ul>
            <li <?php if ($this->url() === $this->url('promos')) echo 'class="active"' ?>>
                <a href="<?php echo $this->url('promos'); ?>"><i class="icon-list"></i> View Promos</a>
            </li>


	  


        </ul>
    </li>

   
</ul>
