<label for="eventId" class="required">Event Name</label>                    
<div class="formRight">    
    <select data-resource="event/rooms/" id="events" name="eventId" required="required" class="chzn-select chosen_select width-100 entity-items">                
        <option value="">please select event...</option>
        <?php foreach ($this->collection as $item):?>                
            <option value="<?php echo $item->getId();?>"><?php echo $item->getTitle();?></option>
        <?php endforeach;?>    
    </select> 
</div>
