<?php
//d($this->collection[0]->getPaySchedule());
if (!is_null($this->message)):

    if ($this->message):
        ?>		
        <div class="alert alert-dismissable alert-<?php echo $this->message[0]['type']; ?>">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <ul>
                <li><?php echo $this->message[0]['message']; ?></li>        
            </ul>
        </div>
        <?php
    endif;
endif;
?>

<?php
$date = date('Y-m-d');
//d($this->collection); die; //echo $date; die;
?>


<script>
  $(function() {
        var id = <?php echo $this->paymenttyp; ?>;
        var typeid=<?php echo $this->typeId; ?>;
      //  alert(id);
        $.post('/admin/report/ajax/commision/type/'+id+'/'+typeid, {id:id,typeid:typeid}, function(data){
            
//            alert(data);
            $('#users').html(data);                        
        });      
    });
</script>


<script>
    $(function() {
        $('#myselect option[value=<?php
if (!empty($this->paymenttyp)) {
    echo $this->paymenttyp;
} else {
    echo '';
}
?>]').attr('selected', 'selected');
    });
</script>    

<div class="grid">
    <div class="grid-title">
        <div class="pull-left">
            <div class="icon-title">
                <i class="icon-list"></i>
            </div> 
            <span>Sales Reports</span>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
<div class="grid">    
    <div class="grid-content overflow">

        <div class="formRight">
            <form method="post" action="<?php echo $this->url('reports'); ?>">
                <select name="myselect" id="myselect" class="chzn-select">
                    <option value="">Select</option>
                    <option value="1">Resort</option>
                    <option value="2">Event</option>
                    <option value="3">Cruise</option>

                </select>
                <span id="users"></span>
                <input type="date" id="startDate" name="mydate" placeholder="Date From" class="" value="<?php
                if (!empty($this->startdat)) {
                    echo $this->startdat;
                } else {
                    echo '';
                }
                ?>">  
                <input type="date" id="endDate" name="mydate1" class="" placeholder="Date To" value="<?php
                if (!empty($this->enddat)) {
                    echo $this->enddat;
                } else {
                    echo '';
                }
                ?>">

                


                <input type="submit" name="submit" class="btn btn-info" id="btnmargin" value="Search">
            </form> 
        </div>



        <table class="table table-bordered table-mod-2" id="datatable_7">
            <thead>
                <tr>                    

                    <th class="hidden-mobile">Order No</th>
                    <th class="hidden-mobile">Item Sold</th> 

                    <th class="hidden-mobile">Order Date</th>
                    <th class="hidden-mobile">Order Total</th>
                    <th class="hidden-mobile">Total Received</th>


                </tr>
            </thead>
            <tbody>
                <?php
                $total = 0;
                $i = 0;
                $totalreceived = 0;
                $totaldue = 0;
                foreach ($this->collection as $item):

                    $hotelName = $item['hotelName'];
                    $type = $item['type'];
                    $roomName = $item['roomName'];
                    $travellers = $item['travellers'];
                    $reservation = $item['reservation'];
                    $status = $item['status'];
                    $paymentDue = $item['paymentDues'];
                    $invoice = $item['invoice'];
                    $total = ($total + $reservation->getfinalCost());
                    $totalreceived = ($totalreceived + $reservation->getdepositAmoun());
                    $totaldue = ($totaldue + $reservation->getBalansAfterDeposit());
                    $i++;
                    ?>

                    <tr>
                        <td class="hidden-mobile"><?php
                            echo $invoice[0]->getId();
                            ?></td>
                        <td class="hidden-mobile"><?php echo $hotelName; ?></td>

                        <td class="hidden-mobile"> <?php  echo ($invoice[0]->getdateAdded() instanceof \DateTime) ? $invoice[0]->getdateAdded()->format('Y-m-d') : $invoice[0]->getdateAdded(); ?></td>

                        <td class="hidden-mobile"><?php echo '$' . $reservation->getfinalCost(); ?></td>

                        <td class="hidden-mobile"><?php echo '$' . $reservation->getdepositAmoun(); ?></td>

                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        
         <br><br>
        <p>
            Item Sold :
            <?php echo $i.' , ';?>
            Order Total :	
            <?php echo '$' . $total . ' , '; ?>
            Total Received :	
            <?php echo '$' . $totalreceived .' , '; ?>
            Average Order :
            <?php if($i!=0){echo '$'. ($total/$i);} else { echo '$ 0'; }?>
            
        </p>
         <form method="post" action="<?php echo $this->url('csv-sale'); ?>">
             
                           
          <input type="hidden" name="strdate" value=<?php  echo $this->startdat;?>>   
          <input type="hidden" name="enddate" value=<?php  echo $this->enddat;?>>    
          <input type="hidden" name="filename" value="sales">   
          <input type="hidden" name="resulttype" value="<?php echo $this->paymenttyp; ?>"> 
          <input type="hidden" name="resortId" value="<?php echo $this->typeId; ?>"> 
          <input type="submit" name="submit" class="btn btn-info" id="btnmargin" value="Download Csv">
         </form> 

        <div class="clearfix"></div>
    </div>
</div>
<?php //echo $this->partial('payments/ajax/modal.phtml');  ?>

<script>
   
  $('#myselect').change(function(){        
        var id = $(this).val();   
        var typeid=<?php $this->typeId; ?>
      //  alert(id);
        $.post('/admin/report/ajax/commision/type/'+id+'/'+typeid, {id:id,typeid:typeid}, function(data){
            
//            alert(data);
            $('#users').html(data); 
        });        
    });
    
   
 </script>   

