<?php

if (!is_null($this->message)):

    if ($this->message):
        ?>		
        <div class="alert alert-dismissable alert-<?php echo $this->message[0]['type']; ?>">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <ul>
                <li><?php echo $this->message[0]['message']; ?></li>        
            </ul>
        </div>
        <?php
    endif;
endif;
?>

<?php
$date = date('Y-m-d');

?>

<script>
  $(function() {
        var id = <?php echo $this->paymenttyp; ?>;
        var typeid=<?php echo $this->typeId; ?>;
      //  alert(id);
        $.post('/admin/report/ajax/commision/type/'+id+'/'+typeid, {id:id,typeid:typeid}, function(data){
            
//            alert(data);
            $('#users').html(data);                        
        });      
    });
</script>

<script>
    $(function() {
        $('#myselect option[value=<?php
if (!empty($this->paymenttyp)) {
    echo $this->paymenttyp;
} else {
    echo '';
}
?>]').attr('selected', 'selected');
    });
</script>    

<div class="grid">
    <div class="grid-title">
        <div class="pull-left">
            <div class="icon-title">
                <i class="icon-list"></i>
            </div> 
            <span>Reservation Reports</span>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
<div class="grid">    
    <div class="grid-content overflow">

        <div class="formRight">
            <form method="post" action="<?php echo $this->url('report-reservation'); ?>">
                 <select name="myselect" id="myselect" class="chzn-select">
                    <option value="">Select</option>
                    <option value="1">Resort</option>
                    <option value="2">Event</option>
                    <option value="3">Cruise</option>

                </select>
                <span id="users">
                    
                </span>
                <input type="date" id="startDate" name="mydate" placeholder="Date From" class="" value="<?php
                if (!empty($this->startdat)) {
                    echo $this->startdat;
                } else {
                    echo '';
                }
                ?>">  
                <input type="date" id="endDate" name="mydate1" placeholder="Date To" class="" value="<?php
                if (!empty($this->enddat)) {
                    echo $this->enddat;
                } else {
                    echo '';
                }
                ?>">

               


                <input type="submit" name="submit" class="btn btn-info" id="btnmargin" value="Search">
            </form> 
        </div>



        <table class="table table-bordered table-mod-2" id="datatable_7">
            <thead>
                <tr>                    

                    <th class="hidden-mobile">Hotel/Cruise Name</th>
                    <th class="hidden-mobile">Client Name</th> 

                    <th class="hidden-mobile">PAX</th>
                    <th class="hidden-mobile">Room Category</th>
                    <th class="hidden-mobile">Net Total</th>
                    <th class="hidden-mobile">Gross Total</th>
                    <th class="hidden-mobile">Status</th>
                    <th class="hidden-mobile">Reservation Date</th>

                </tr>
            </thead>
            <tbody>
                <?php
                $total = 0;
                $i = 0;
                $totalnet = 0;
                $totalgross = 0;
                foreach ($this->collection as $item):
                    $hotelName = $item['hotelName'];
                    $type = $item['type'];
                    $roomName = $item['roomName'];
                    $travellers = $item['travellers'];
                    $reservation = $item['reservation'];
                    
                    $reservationdate=($reservation->getcreatedAt() instanceof \DateTime) ? $reservation->getcreatedAt()->format('Y-m-d') : $reservation->getcreatedAt(); 

                 
                    
                    $status = $item['status'];
                    $paymentDue = $item['paymentDues'];
                    $invoice = $item['invoice'];
                    $total = ($total + $reservation->getfinalCost());
                    
                    $discount=$reservation->getappliDiscount();
                            
                    $merchantfee=$reservation->getmerchantFee();        
                   
                    $nettotal=$reservation->getRoomNetCost()+$reservation->getAddonsNetCost();
                    
                    $grosstotal=$reservation->getfinalCost();
                    
                    $totalnet = ($totalnet + $nettotal);
                    $totalgross = ($totalgross + $grosstotal);
                    $i++;
                    ?>

                    <tr>
                        
                         <td class="hidden-mobile"><?php echo $hotelName; ?></td>
                         <td class="hidden-mobile"><?php
                           // foreach ($travellers as $traveller) {
                                echo $travellers[0];
                             //}
                            ?></td>
                       
                         <td class="hidden-mobile"><?php echo count($travellers); ?></td>
                        <td class="hidden-mobile"> <?php echo $roomName ?></td>
                        <td class="hidden-mobile"><?php echo '$' . $nettotal; ?></td>

                        <td class="hidden-mobile"><?php echo '$' . $grosstotal; ?></td>
                        
                       <td class="hidden-mobile"><?php if($reservation->getbalansAfterDeposit()==0){echo 'Completed';}else{echo 'Due';}?></td>
                       <td class="hidden-mobile"><?php echo $reservationdate; ?></td>

                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        
         <br><br>
        <p>
            
            Net Total :	
            <?php echo '$' . $totalnet . ' , '; ?>
            Gross Total :	
            <?php echo '$' . $totalgross ; ?>
           
        </p>
         <form method="post" action="<?php echo $this->url('csv-reservation'); ?>">
             
                           
          <input type="hidden" name="strdate" value=<?php  echo $this->startdat;?>>   
          <input type="hidden" name="enddate" value=<?php  echo $this->enddat;?>>    
          <input type="hidden" name="filename" value="reservation">   
          <input type="hidden" name="resulttype" value="<?php echo $this->paymenttyp; ?>"> 
          <input type="hidden" name="resortId" value="<?php echo $this->typeId; ?>"> 
          <input type="submit" name="submit" class="btn btn-info" id="btnmargin" value="Download Csv">
         </form> 

        <div class="clearfix"></div>
    </div>
</div>
<?php //echo $this->partial('payments/ajax/modal.phtml');  ?>

<script>
   
  $('#myselect').change(function(){        
        var id = $(this).val();   
        var typeid=<?php $this->typeId; ?>
      //  alert(id);
        $.post('/admin/report/ajax/commision/type/'+id+'/'+typeid, {id:id,typeid:typeid}, function(data){
            
//            alert(data);
            $('#users').html(data); 
        });        
    });
    
   
 </script> 