<div class="formRow control-group">
    <h4>Notes</h4>
    <hr />
</div>
<!--<div class="formRow control-group">
    <label for="adminNotes">Admin Notes</label>
    <div class="formRight">
        <textarea type="text" name="adminNotes" class="span input same-height-1" rows="4"></textarea>
    </div>
</div>
<div class="formRow control-group">
    <label for="returnTo">Client Notes</label>
    <div class="formRight">
        <textarea type="text" name="clientNotes" class="span input same-height-1" rows="4"></textarea>
    </div>
</div>-->


 <div class="formRow control-group">
                <?php echo $this->formLabel($form->get('adminNotes')); ?>
                <div class="formRight">
                    <?php
                    echo $this->formElement($form->get('adminNotes')->setAttribute('class', 'span input same-height-1'));
                    ?>
                    <?php echo $this->formElementErrors($form->get('adminNotes'), array('class' => 'help-inline')); ?>
                </div>
            </div>

<div class="formRow control-group">
                <?php echo $this->formLabel($form->get('clientNotes')); ?>
                <div class="formRight">
                    <?php
                    echo $this->formElement($form->get('clientNotes')->setAttribute('class', 'span input same-height-1'));
                    ?>
                    <?php echo $this->formElementErrors($form->get('clientNotes'), array('class' => 'help-inline')); ?>
                </div>
            </div>    