<div class="formRow control-group">			
    <label for="reservationType" class="required">Reservation Type</label>
    <div class="formRight">
        <div name="reservationType" class="distance distance-2">
            <p>
                <input type="radio" id="fit" class="load-entity" name="type" checked="checked" value="1" data-resource="resorts">
                <label for="fit"><span></span>Resort (FIT)</label>
            </p>
            <p>
                <input type="radio" id="event" class="load-entity" name="type" value="2" data-resource="events">
                <label for="event"><span></span> Event (Group)</label>
            </p>
            <p>
                <input type="radio" id="cruise" class="load-entity" name="type" value="3" data-resource="cruises">
                <label for="cruise"><span></span> Cruise</label>
            </p>   
        </div>
    </div>
</div>
