<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'SalesObjects\Module'                        => __DIR__ . '/Module.php',
    'SalesObjects\Controller\HotelsController' => __DIR__ . '/src/SalesObjects/Controller/HotelsController.php',
    'SalesObjectsTest\Framework\TestCase'        => __DIR__ . '/tests/SalesObjects/Framework/TestCase.php',
    'SalesObjectsTest\SampleTest'                => __DIR__ . '/tests/SalesObjects/SampleTest.php',
);
