<?php
if ($this->message):
    ?>		
    <div class="alert alert-dismissable alert-<?php echo $this->message[0]['type']; ?>">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <ul>
            <li><?php echo $this->message[0]['message']; ?></li>        
        </ul>
    </div>
    <?php
endif;
?>

<div class="grid">

    <div class="grid-title">
        <div class="pull-left">
            <div class="icon-title">
                <i class="icon-list"></i>
            </div>
            <span>Events</span>
            <div class="clearfix"></div>
        </div>
        <div class="pull-right">
            <div class="icon-title">
                <a href="<?php echo $this->url('events-add'); ?>"><i class="icon-plus-sign"></i></a>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>

    <div class="grid-content overflow">

        <table class="table table-bordered table-mod-2" id="datatable_3">
            <thead>
                <tr>
                    <th class="t_center">
                        <input type="checkbox" id="c0" name="cc" />
                        <label for="c0"><span></span></label>
                    </th>					
                    <th class="hidden-mobile">Image</th>
                    <th class="hidden-mobile">Title</th>
                    <th class="hidden-mobile">Resort</th>
                    <th class="hidden-mobile">Event Category</th>
                    <th class="hidden-mobile">Start Date</th>
                    <th class="hidden-mobile">End Date</th>
                    <th class="hidden-mobile">Status</th>					
                    <th class="hidden-mobile">Status</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <?php $i = 1;
                foreach ($this->collection as $item): ?>
                    <tr>
                        <td class="t_center">
                            <input type="checkbox" id="c<?php echo $i; ?>" name="cc" />
                            <label for="c<?php echo $i; ?>"><span></span></label>
                        </td>

                        <td><img src="<?php echo $this->imagePath . $item['image']; ?>" alt=""></td>

                        <td class="hidden-mobile"><?php echo substr(strip_tags($item['title']), 0, 50).'...'; ?></td>

                        <td class="hidden-mobile">
                            <a data-toggle="modal" href="<?php echo $this->url('ajax-resorts-item', array('id' => $item['resortId']));?>" data-target=".bs-example-modal-lg">
                                <?php echo $item['resortTitle']; ?>
                            </a>
                        </td>
                        
			<td class="hidden-mobile"><?php echo $item['eventCategory']; ?></td>
                        <td class="hidden-mobile"><?php echo $item['startDate']->format('M d, Y'); ?></td>
                        <td class="hidden-mobile"><?php echo $item['endDate']->format('M d, Y'); ?></td>
                        
                        <td class="hidden-mobile">
                            <span class="s_<?php echo $item['status'] ? 'green' : 'gray'; ?>">
                                <?php echo $item['status'] ? 'Enabled' : 'Disabled'; ?>
                            </span>
                        </td>

                        <td class="hidden-mobile">
                            <span class="s_<?php echo $item['approved'] === 1 ? 'green' : 'gray'; ?>">
                                <?php echo $item['approved'] === 1 ? 'Approve' : 'Decline'; ?>
                            </span>
                        </td>
                        
                        <td class="action-table">
                            <!-- 						<a href="javascript:void(0);"> -->
                            <!-- 							<img src="/images/icon/table_view.png" alt=""> -->
                            <!-- 						</a> -->
                            <a href="<?php echo $this->url('events-edit', array('id' => $item['id'])); ?>">
                                <img src="/images/icon/table_edit.png" alt="">
                            </a>
                            <a href="<?php echo $this->url('events-delete', array('id' => $item['id'])); ?>"
                               data-confirm="Are you sure?">
                                <img src="/images/icon/table_del.png" alt="">
                            </a>
                            <a href="javascript:void(0);" onclick="viewRooms(<?php echo $item['id']; ?>)">
                                Add Rooms
                            </a>
                        </td>
                    </tr>
                    <?php $i++; ?>
<?php endforeach; ?>
            </tbody>
        </table>
        <div class="clearfix"></div>
    </div>
</div>
<?php echo $this->partial('sales-objects/ajax/modal.phtml');?>


<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close">×</button>
    <h3 id="myModalLabel"></h3>
  </div>
  <div class="modal-body">
    <p></p>
  </div>
  <div class="modal-footer">
    <button class="btn close">Close</button>
  </div>
</div>

<script>
function viewRooms(id){
   
    $.ajax({
                async:false,    
                url: '/admin/event/rooms/'+id,
                type: 'GET',
                beforeSend:function(){
                   $(".modal-body").html('<center><img src="/images/ajax-loader.gif" alt="Loading..."></center>');  
                    $("#myModalLabel").html('Event Rooms');
                    $("#myModal").css({"display": "block"});
                    $("#myModal").modal();
                },
                success: function(data){
                    $(".modal-body").html(data)  
//                  $("#myModal").modal()  
                }
            });
}

$(document).ready(function(){
    $('.close').click(function(){
        $("#itemModal").css({"display": "none"});
        $("#myModal").css({"display": "none"});
    });
});
</script>