<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Orders\Module'                        => __DIR__ . '/Module.php',
    'Orders\Controller\OrdersController' => __DIR__ . '/src/Orders/Controller/OrdersController.php',
    'OrdersTest\Framework\TestCase'        => __DIR__ . '/tests/Orders/Framework/TestCase.php',
    'OrdersTest\SampleTest'                => __DIR__ . '/tests/Orders/SampleTest.php',
);
