<?php 

$form = $this->form;

$form->prepare();
$form->setAttribute('action', $this->url(
		'credit-payment'
));

$form->setAttribute('method', 'post');
?>
<div class="grid">
	<div class="grid-title">
		<div class="pull-left">
			<div class="icon-title">
				<i class="icon-plus"></i>
			</div>
			<span>Billing Details</span>
			<div class="clearfix"></div>
		</div>
		<div class="clearfix"></div>
	</div>
	<?php echo $this->form()->openTag($form); ?>
	<div class="grid-content">
            
            <div class="formRow control-group">
                    <?php echo $this->formLabel($form->get('typeOfCard')); ?>
                    <div class="formRight">
                            <?php echo $this->formElement($form->get('typeOfCard')->setAttribute('class', 'span input')); ?>
                    <?php echo $this->formElementErrors($form->get('typeOfCard'), array('class' => 'help-inline')); ?>
                    </div>
            </div>
                        
            <div class="formRow control-group">
                    <?php echo $this->formLabel($form->get('cardNumber')); ?>
                    <div class="formRight">
                            <?php echo $this->formElement($form->get('cardNumber')->setAttribute('class', 'span input')); ?>
                    <?php echo $this->formElementErrors($form->get('cardNumber'), array('class' => 'help-inline')); ?>
                    </div>
            </div>
            
            <!-- chzn-select chosen_select width-100 -->
             <div class="formRow control-group">
                    <?php echo "Card Expiry"?>
                    <div class="formRight">
                        <select name="cardMonth" class="">
                            <option value="01">January</option>
                            <option value="02">Febuary</option>
                            <option value="03">March</option>
                            <option value="04">April</option>
                            <option value="05">May</option>
                            <option value="06">June</option>
                            <option value="07">July</option>
                            <option value="08">August</option>
                            <option value="09">September</option>
                            <option value="10">October</option>
                            <option value="11">November</option>
                            <option value="12">December</option>    
                        </select>
                        
                        <select>
                            <?php foreach(range(date('Y'),date('Y')+15) as $i): ?>
                            <option value="<?php echo $i ;?>"><?php echo $i ;?></option>
                            <?php endforeach;?>
                        </select>
                    </div>
             </div>
            
            <div class="formRow control-group">
                    <?php echo $this->formLabel($form->get('cvvNumber')); ?>
                    <div class="formRight">
                            <?php echo $this->formElement($form->get('cvvNumber')->setAttribute('class', 'span input')->setAttribute('required', 'required')); ?>
                    <?php echo $this->formElementErrors($form->get('cvvNumber'), array('class' => 'help-inline')); ?>
                    </div>
            </div>
            
            <div><input type="hidden" name="sec" value="<?php echo base64_encode($reservation->getId());?>"></div>
            
             <div class="formRow control-group">
            <?php echo $this->formSubmit($form->get('billProcess')->setAttribute('class', 'btn btn-info')) ?>
        </div>
        <div class="clearfix"></div>
            
	<?php echo $this->form()->closeTag() ; ?>
</div>

<script>
    
$(document).ready(function(){
   
    $('.grid-content .formRow ul.help-inline').parents('.formRow').addClass('error');
    $('.error input').keyup(function(){
                            $(this).parents('.formRow').removeClass('error');
                            $(this).next('ul.help-inline').remove();
    });
    
    $('.chzn-select').chosen();
    
});

</script>