<!--<div class="formRow control-group">			
    <label for="reservationType" class="required">Reservation Type</label>
    <div class="formRight">
        <div name="reservationType" class="distance distance-2">
            <p>
                <input type="radio" id="fit" class="load-entity" name="type" checked="checked" value="1" data-resource="resorts">
                <label for="fit"><span></span>Resort (FIT)</label>
            </p>
            <p>
                <input type="radio" id="event" class="load-entity" name="type" value="2" data-resource="events">
                <label for="event"><span></span> Event (Group)</label>
            </p>
            <p>
                <input type="radio" id="cruise" class="load-entity" name="type" value="3" data-resource="cruises">
                <label for="cruise"><span></span> Cruise</label>
            </p>   
        </div>
    </div>
</div>-->
<?php 
switch($this->data[0]['type']){
    case 1:
        $typeName = "Resort";
        $dataresource = '<input type="hidden" name="data-resource" id="data-resource" value="resorts"/>';
        break;
    case 2:
        $typeName = "Event";
        $dataresource = '<input type="hidden" name="data-resource" id="data-resource" value="events"/>';
        break;
    case 3:
        $typeName = "Cruise";
        $dataresource = '<input type="hidden" id="data-resource" name="data-resource"  value="cruises"/>';
        break;
}
?>
<div class="formRow control-group">			
    <label for="reservationType" class="">Reservation Type</label>
    <div class="formRight">
        <div name="reservationType" class="distance distance-2">
            <label for="reservationType1" class=""><?php echo $typeName; ?></label>
            <input type="hidden" name="type" value="<?php echo $this->data[0]['type']; ?>"/>
            <?php echo $dataresource ; ?>
        </div>
    </div>
</div>
