<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Reports\Module'                        => __DIR__ . '/Module.php',
    'Reports\Controller\ReportsController' => __DIR__ . '/src/Reports/Controller/ReportsController.php',
);
