<?php
$id = $note->getId();
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url(
		'manageclients-editnotes',array('id'=>$id)
));
$form->setAttribute('method', 'post');



?>
<?php
if (!is_null($this->message)):
    if ($this->message):
        ?>		
        <div class="alert alert-dismissable alert-<?php echo $this->message[0]['type']; ?>">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <ul>
                <li><?php echo $this->message[0]['message']; ?></li>        
            </ul>
        </div>
        <?php 
    endif;
endif;


?>
<div class="grid">
	<div class="grid-title">
		<div class="pull-left">
			<div class="icon-title">
				<i class="icon-plus"></i>
			</div>
			<span>Edit Note</span>
			<div class="clearfix"></div>
		</div>
		<div class="clearfix"></div>
	</div>
	<?php echo $this->form()->openTag($form); ?>
        <input type='hidden' name='id' value='<?php echo $this->note->getId(); ?>'>
	<div class="grid-content">
                <div class="formRow control-group">
			<?php echo $this->formLabel($form->get('subject')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('subject')->setAttribute('class', 'span input')); ?>
                                <?php echo $this->formElement($form->get('travellerId')); ?>
	        	<?php echo $this->formElementErrors($form->get('subject'), array('class' => 'help-inline')); ?>
			</div>
		</div>
                <div class="formRow control-group">
			<?php echo $this->formLabel($form->get('message')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('message')->setAttribute('class', 'span input same-height-1')->setAttribute('rows', '3')); ?>
	        	<?php echo $this->formElementErrors($form->get('message'), array('class' => 'help-inline')); ?>
			</div>
		</div>  
               <div class="formRow control-group">
			<?php echo $this->formLabel($form->get('reminderDate')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('reminderDate')->setAttribute('class', 'span input')); ?>
	        	<?php echo $this->formElementErrors($form->get('reminderDate'), array('class' => 'help-inline')); ?>
			</div>
		</div>
		
		<div class="formRow control-group">
			<?php echo $this->formSubmit( $form->get('submit')->setAttribute('class', 'btn btn-info')) ?>
                        <input id="resetbutton" class="btn btn-info" type="reset" value="Reset" name="reset"></input>
		</div>
		<div class="clearfix"></div>
	</div>
	<?php echo $this->form()->closeTag() ?>
</div>

<script>

	function checkPass(){

		var pass = $('#pass1').val();
		var repass = $('#pass2').val();

		console.log(pass !== repass && pass == '');
		
		if(pass !== repass || pass == '' || repass == ''){
			$('#pass1, #pass2').parents('.formRow').addClass('error');//.append('<ul class="help-inline"><li>Password does not match the confirm password</li></ul>')
			$('#submitbutton').attr('disabled', 'disabled');
		}else{
			$('#pass1, #pass2').parents('.formRow').removeClass('error').addClass('success');
			$('#submitbutton').removeAttr('disabled');
		} 
	};			
				
	$(function(){
		$('.grid-content .formRow ul.help-inline').parents('.formRow').addClass('error');
		$('.error input').keyup(function(){
					$(this).parents('.formRow').removeClass('error');
					$(this).next('ul.help-inline').remove();
		});

		$('#pass1, #pass2').keyup(checkPass);
	});				
</script>


