<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Base\Module'                        => __DIR__ . '/Module.php',
    'Base\Controller\BaseController' => __DIR__ . '/src/Base/Controller/BaseController.php',
    'BaseTest\Framework\TestCase'        => __DIR__ . '/tests/Base/Framework/TestCase.php',
    'BaseTest\SampleTest'                => __DIR__ . '/tests/Base/SampleTest.php',
);
