<?php
$form = $this->form;
?>
<div class="block03">
    <div class="box01">
        <input type="radio" name="paymentType" id="full-payment" value="1"  <?php if (!$form->get('paymentType')->getValue()) echo 'checked="checked"'; ?>>
        Full Payment
    </div>
    <div class="box01" id="deposit-hide">
        <input type="radio" name="paymentType" id="deposit" value="0"  <?php //if(!$form->get('paymentType')->getValue()) echo 'checked="checked"';    ?>>
        Deposit
    </div>
</div>  
<div class="block04">




<div class="box01"><!--<input name="" type="text">-->

        <?php
        echo $this->formElement($form->get('depositAmount')
                        ->setAttribute('readonly', 'readonly')
                        ->setAttribute('class', ''));
        ?>
        <?php echo $this->formElementErrors($form->get('depositAmount'), array('class' => 'help-inline')); ?>

    </div>
    <div class="box02">(Deposite amounts are calculated at 20% of full total)
    </div>
</div>




<div id="deposit-due-fields" style="display:none;">
<!--   
<div class="block03">
      
           <!-- <div class="distance distance-2 payment-type"> -->

                <!--<p>-->
           <!--      <div class="box01">
                    <input type="radio" name="depositMethod" id="deposit-due" value="0"  <?php //if (!$form->get('depositMethod')->getValue()) echo 'checked="checked"'; ?>>
                    Deposit Due
                </div>
                <!--<p>-->
              <!--  <div class="box01">
                    <input type="radio" name="depositMethod" id="rcvd" value="1"  <?php //if ($form->get('depositMethod')->getValue()) echo 'checked="checked"'; ?>>
                    RCVD
                </div>
</div>
       
-->
   <div class="block04">
        <div class="box01">
        <?php echo $this->formLabel($form->get('balansAfterDeposit')); ?>
         </div>   
      <!--  <div class="formRight input-prepend">
            <span class="add-on">$</span>-->
       <div class="box02">
            <?php echo $this->formElement($form->get('balansAfterDeposit')->setAttribute('class', '')); ?>
            <?php echo $this->formElementErrors($form->get('balansAfterDeposit'), array('class' => 'help-inline')); ?>
   <!--     </div>-->
        </div>
    </div>
    <div id="due-date">
         <div class="block04">
            <div class="box01">
            <?php echo $this->formLabel($form->get('nextPaymentDue[]')); ?>
            </div >
                
             <div class="box02">  
                <?php echo $this->formElement($form->get('nextPaymentDue[]')->setAttribute('class', '')
                        
                                                                              -> setAttribute('readonly', 'readonly') ); ?>
                <?php echo $this->formElementErrors($form->get('nextPaymentDue[]'), array('class' => 'help-inline')); ?>
            </div>
        </div>
        <div class="block04">
             <div class="box01">
            <?php echo $this->formLabel($form->get('dueDate1[]')); ?>
            </div>
              <div class="box02">  
                <?php
                echo $this->formElement($form->get('dueDate1[]')
                                //->setAttribute('min', date('Y-m-d'))
                                 ->setAttribute('id', 'dueDate1')
                                ->setAttribute('class', 'span input'));
                ?>
                <?php echo $this->formElementErrors($form->get('dueDate1[]'), array('class' => 'help-inline')); ?>
            </div>
        </div>
    </div>
    
    
    
    <div class="block04">
         <div class="box01">
        <?php echo $this->formLabel($form->get('finalPaymentDue')); ?>
         </div>    
            <div class="box02">  
            <?php echo $this->formElement($form->get('finalPaymentDue')->setAttribute('class', '')); ?>
            <?php echo $this->formElementErrors($form->get('finalPaymentDue'), array('class' => 'help-inline')); ?>
        </div>
    </div>
    
    <div class="block04">
         <div class="box01">
        <?php echo $this->formLabel($form->get('dueDate2')); ?>
          </div>
         <div class="box02">
            <?php
            echo $this->formElement($form->get('dueDate2')
                            //->setAttribute('min', date('Y-m-d'))
                             ->setAttribute('id', 'dueDate2')
                            //->setAttribute('required', 'required')
                            ->setAttribute('class', ''));
            ?>
            <?php echo $this->formElementErrors($form->get('dueDate2'), array('class' => 'help-inline')); ?>
        </div>
    </div>

<!--    <div class="formRow control-group">			
        <div class="formRight">
            <input type="button" value="Add" class="btn btn-info" id="addduebutton" name="dueButton">     	
        </div>
    </div>
-->
</div>


<script>
    $(function() {


        if ($('#deposit').is(':checked')) {
            $('#deposit-due-fields').show();
        }

        $('input[name="paymentType"]').click(function() {
            console.log('change');
            if ($('#deposit').is(':checked')) {
                $('#deposit-due-fields').show();
            } else {
                $('#deposit-due-fields').hide();
            }

        });

    });
</script>
