<?php

if (count($results) > 0) {
    $fh = @fopen('php://output', 'w');
//d($fh);

    $header_row = array();
    $str = "Order,";
    $str.= "Hotel Name,";
    $str.= "Room Category,";
    $str.= "No. of PAX,";
    $str.= "Travel From,";
    $str.= "Travel To,";
    $str.= "No of Nights";
    $strt = preg_replace("/([,])(\\1+)/i", '\\1', rtrim($str, ','));
    $header_row = explode(',', rtrim($strt, ','));

    fputcsv($fh, $header_row, ',', '"');


    foreach ($results['collection'] as $item) {

        $hotelName = $item['hotelName'];
        $type = $item['type'];
        $roomName = $item['roomName'];
        $travellers = $item['travellers'];
        $reservation = $item['reservation'];

        $order = $reservation->getreferenceNumber();

        $reservationdate = ($reservation->getcreatedAt() instanceof \DateTime) ? $reservation->getcreatedAt()->format('Y-m-d') : $reservation->getcreatedAt();
        $datefrom = ($reservation->getdateFrom() instanceof \DateTime) ? $reservation->getdateFrom()->format('Y-m-d') : $reservation->getdateFrom();
        $dateto = ($reservation->getdateTo() instanceof \DateTime) ? $reservation->getdateTo()->format('Y-m-d') : $reservation->getdateTo();

        $noofdays = $reservation->getnoOfDays();

        $status = $item['status'];
        $paymentDue = $item['paymentDues'];
        $invoice = $item['invoice'];
        $total = ($total + $reservation->getfinalCost());

        $discount = $reservation->getappliDiscount();

        $merchantfee = $reservation->getmerchantFee();

        $nettotal = $reservation->getfinalCost();

        $grosstotal = $nettotal - ($discount + $merchantfee);



        $str1 = $order . ",";
        $str1.= $hotelName . ",";
        $str1.=$roomName . ",";
        $str1.=count($travellers). ",";
        $str1.=$datefrom. ",";
        $str1.=$dateto. ",";
        $str1.=$noofdays. ",";
        $strt1 = preg_replace("/([,])(\\1+)/i", '\\1', rtrim($str1, ','));

        $row = explode(',', $strt1);

        fputcsv($fh, $row, ',', '"');
    }
    fclose($fh);
}