<?php 
$count = $travellerCount;
?>
<div class="added-traveller">
    <div class="formRow control-group">
       
            <hr/>
        <div class="formRight">
            
            
        </div>
    </div> 
    <div class="formRow control-group">
        <?php echo $this->formLabel($form->get('travellerName')); ?>
        <div class="formRight">
            <input type="text" name="tname[]" class="span input" required="required">
        </div>
    </div>
    
     <div class="formRow control-group">			
        <label for="sex" class="required">Sex</label>
        <div class="formRight">
            <div name="sex" class="distance distance-2">
                <p>
                    <input type="radio" id="male_<?php echo $count;?>" class="sex" required="required" name="tsex" onClick="callPriceCal(this);"  value="1">
                    <label id="labm_<?php echo $count;?>" for="male_<?php echo $count;?>"><span></span>Male</label>
                </p>
                <p>
                    <input type="radio" id="female_<?php echo $count;?>" required="required" class="sex" name="tsex" onClick="callPriceCal(this);" value="2">
                    <label id="labf_<?php echo $count;?>" for="female_<?php echo $count;?>"><span></span>Female</label>
                </p>
                  
            </div>
        </div>
    </div>
    
    <div class="formRow control-group">
        <?php echo $this->formLabel($form->get('travellerEmail')); ?>
        <div class="formRight">
            <input type="email" name="tEmail[]" class="span input" >
        </div>
    </div>
    <div class="formRow control-group">
        <?php echo $this->formLabel($form->get('travellerPhone')); ?>
        <div class="formRight">
            <input type="text" name="tPhone[]" class="span input" >
        </div>
    </div>
    <div class="formRow control-group">
        <?php echo $this->formLabel($form->get('travellerDOB')); ?>
        <div class="formRight">
           <input type="date" name="tDob[]" class="span input" id="dob_<?php echo $count;?>" required="required"> 
        </div>
    </div>
    <div class="formRow control-group">
        <?php echo $this->formLabel($form->get('travellerAddress')); ?>
        <div class="formRight">
            <input type="text" name="tAddress[]" class="span input" /> 
        </div>
    </div>
     <div class="formRow control-group">
        
        <div class="formRight">
            <span style="float: right">
                <button type="button" class="remove-traveller btn btn-danger btn-small metro">Remove Guest</button>
            <span>
            <div class="clearfix"></div>
        </div>
    </div>
</div> 