<label for="roomCategory" class="required">Room Category</label> 
<div class="formRight">    
    <select eventStartDate="<?php echo $this->data->getStartDate()->format('Y-m-d'); ?>" eventEndDate="<?php echo $this->data->getEndDate()->format('Y-m-d'); ?>" data-extra-type="<?php echo \Inventory\Model\Items::LINKED_TO_EVENT_NAME; ?>" data-type="<?php echo \Orders\Controller\AjaxController::EVENT_ROOMS; ?>"  id="event-rooms" data-url="/event/room/" name="roomCategory" required="required" class="chzn-select chosen_select width-100 load-item">                
        <option value="">please select room category...</option>
        <?php foreach ($this->collection as $item):?>                
            <option value="<?php echo $item->getId();?>" room_id="<?php echo $item->getRoomId();?>"><?php echo $item->getRoomCategory() ; ?></option>
        <?php endforeach;?>    
    </select> 
</div>
<input type="hidden" name="eventStart" id="hid-start" value="<?php echo $this->data->getStartDate()->format('Y-m-d'); ?>">
<input type="hidden" name="eventEnd" id="hid-end" value="<?php echo $this->data->getEndDate()->format('Y-m-d'); ?>">

