<?php //d($this->collection[3]['reservation']->getAffiliateId());   ?>


<script>
    function printPage(id)
    {
        var mywindow = window.open('<?php echo $this->url('print-reservation') ?>' + id, 'Reservation', 'left=10,top=10,height=700,width=700,scrollbars=1,resizable=1');
    }
</script>
<?php
if (!is_null($this->message)):
    if ($this->message):
        ?>		
        <div class="alert alert-dismissable alert-<?php echo $this->message[0]['type']; ?>">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <ul>
                <li><?php echo $this->message[0]['message']; ?></li>        
            </ul>
        </div>
        <?php
    endif;
endif;
?>
<div class="grid">
    <div class="grid-title">
        <div class="pull-left">
            <div class="icon-title">
                <i class="icon-list"></i>
            </div> 
            <span>Pending Reservations</span>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>




</div>
<div class="grid">    
    <div class="grid-content overflow">


        <div class="formRight">
            <form method="post" action="<?php
            echo $this->url(
                    'orders-pending'
            );
            ?>">


                Date From : <input type="date" id="startDate" name="mydate" class="" value="<?php
                if (!empty($this->startdat)) {
                    echo $this->startdat;
                } else {
                    echo '';
                }
                ?>">  
                Date To : <input type="date" id="endDate" name="mydate1" class="" value="<?php
                if (!empty($this->enddat)) {
                echo $this->enddat;
                } else {
                echo '';
                }  ?>">
                <input type = "submit" name = "submit" class = "btn btn-info" id = "btnmargin" value = "Search">
                </form> </div>

                <table class = "table table-bordered table-mod-2" id = "datatable_3">
                <thead>
                <tr>
                <!--<th class = "hidden-mobile">Reservation No.</th>-->
                <th class = "hidden-mobile">Name</th>
                <th class = "hidden-mobile">Booking From</th>
                <th class = "hidden-mobile">Booking Date</th>
                <th class = "hidden-mobile">Type</th>
                <th class = "hidden-mobile">For</th>
                <th class = "hidden-mobile">Order Total</th>
                <th class = "hidden-mobile">Actions</th>

                </tr>
                </thead>
                <tbody>
                <?php
                $total = 0;
                $i = 0;
                foreach ($this->collection as $item):

                $hotelName = $item['hotelName'];
                $type = $item['type'];
                $roomName = $item['roomName'];
                $travellers = $item['travellers'];
                $reservation = $item['reservation'];
                $status = $item['status'];

                $total = ($total + $reservation->getFinalCost());
                $i++;
                if ($reservation->getAffiliateId()) {
                $affiliateinfo = '-';
                } else {
                    $affiliateinfo = 'vacationparties.com';
                }
                ?>                  

                                 <tr>

                                 <td class="hidden-mobile"><?php
                                 echo $travellers[0];
                                 ?></td>
                <td class="hidden-mobile"><?php echo $affiliateinfo ?></td> 

                <td class="hidden-mobile"><?php echo $reservation->getCreatedAt()->format("Y-m-d"); ?></td>

                <?php if ($type == 'FIT') { ?>
                    <td class="hidden-mobile"><?php echo "Resort"; ?></td>   
                <?php }if ($type == 'Group') { ?>
                    <td class="hidden-mobile"><?php echo "Event"; ?></td>   

                <?php }if ($type == 'Cruise') { ?>
                    <td class="hidden-mobile"><?php echo "Cruises"; ?></td>   
                <?php } ?>

                <td class="hidden-mobile"><?php echo $hotelName; ?></td> 


                <td class="hidden-mobile"><?php echo '$' . $reservation->getFinalCost(); ?></td>

                <td class="action-table">                            
                    <a href="<?php echo $this->url('orders-pending-view', array('id' => $reservation->getId())); ?>" title="View">
                        <img src="/images/icon/table_view.png" alt="View">
                    </a>


                    <a href="<?php echo $this->url('orders-pending-markcomplete', array('id' => $reservation->getId())); ?>"  title="Mark As Completed">
                        <img src="/images/icon/icon_cont_check.png" alt="Mark As Completed">
                    </a>

                    <a href="<?php echo $this->url('orders-pending-sendmail', array('id' => $reservation->getId())); ?>"  title="Email Client">
                        Email client
                    </a>

                    <a href="<?php echo $this->url('orders-pending-delete', array('id' => $reservation->getId())); ?>" data-confirm="Are you sure?" title="Delete">
                        <img src="/images/icon/table_del.png" alt="Delete">
                    </a>

                </td>

                </tr>                    
                <?php endforeach; ?>
                </tbody>
                </table>
                <br><br>
                <p> Total Orders :	
                    <?php echo $i . ' , '; ?>
                    Order Total :	
                    <?php echo '$' . $total; ?>
                </p>
                <div class="clearfix"></div>
        </div>
    </div>
