<?php //d($this->collection[3]['reservation']->getAffiliateId());   ?>


<script>
    function printPage(id)
    {
        var mywindow = window.open('<?php echo $this->url('print-reservation') ?>' + id, 'Reservation', 'left=10,top=10,height=700,width=700,scrollbars=1,resizable=1');
    }
</script>
<?php
if (!is_null($this->message)):
    if ($this->message):
        ?>		
        <div class="alert alert-dismissable alert-<?php echo $this->message[0]['type']; ?>">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <ul>
                <li><?php echo $this->message[0]['message']; ?></li>        
            </ul>
        </div>
        <?php
    endif;
endif;
?>
<div class="grid">
    <div class="grid-title">
        <div class="pull-left">
            <div class="icon-title">
                <i class="icon-list"></i>
            </div> 
            <span>Pending Reservations</span>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>




</div>
<div class="grid">    
    <div class="grid-content overflow">


        <div class="formRight">
            <form method="post" action="<?php
            echo $this->url(
                    'orders-pending'
            );
            ?>">


                Date From : <input type="date" id="startDate" name="mydate" class="" value="<?php
                if (!empty($this->startdat)) {
                    echo $this->startdat;
                } else {
                    echo '';
                }
                ?>">  
                Date To : <input type="date" id="endDate" name="mydate1" class="" value="<?php
                if (!empty($this->enddat)) {
                echo $this->enddat;
                } else {
                echo '';
                }  ?>">
                <input type = "submit" name = "submit" class = "btn btn-info" id = "btnmargin" value = "Search">
                </form> </div>
                <form method="post" id="formview" action="<?php
                    echo $this->url(
                            'orders-delete'
                    );
                    ?>">
                      <div class="formRight">
                   <input type="button" name="removechecked"  onclick="return removeChecked();"class="btn btn-info rem-checked" id="btnmargin" value="Remove">
                </div>
                <table class = "table table-bordered table-mod-2" id = "datatable_3">
                <thead>
                <tr>
                <!--<th class = "hidden-mobile">Reservation No.</th>-->
                      <th class="t_center">
                        <input type="checkbox" id="c0" name="cc" />
                        <label for="c0"><span></span></label>
                    </th>
                <th class="hidden-mobile">Sr No.</th>     
                <th class = "hidden-mobile">Name</th>
                <th class="hidden-mobile">Reference No.</th>
                <th class = "hidden-mobile">Booking From</th>
                <th class = "hidden-mobile">Booking Date</th>
                <th class = "hidden-mobile">Type</th>
                <th class = "hidden-mobile">For</th>
                <th class = "hidden-mobile">Order Total</th>
                <th class = "hidden-mobile">Status</th>
                <th class = "hidden-mobile">Actions</th>

                </tr>
                </thead>
                <tbody>
                <?php
                $total = 0;
                $i = 0;
                foreach ($this->collection as $item):

                $hotelName = $item['hotelName'];
                $type = $item['type'];
                $roomName = $item['roomName'];
                $travellers = $item['travellers'];
                $reservation = $item['reservation'];
                $status = $item['status'];
                
                if($isBooked == 0){
                    $status = 'Pending';
                }

                $total = ($total + $reservation->getFinalCost());
                $i++;
                if ($reservation->getAffiliateId()) {  
                    $affiliateinfo = $reservation->getAffiliateId()->getName();
                } else {
                    $affiliateinfo = 'vacationparties.com';
                }
                ?>                  

                                 <tr>
                                 <td class="t_center">
                                    <input type="checkbox" id="c<?php echo $i; ?>" class="checkb" name="cc[]" value="<?php echo $reservation->getId(); ?>"/>
                                    <label for="c<?php echo $i; ?>"><span></span></label>
                                </td>
                                <td class="hidden-mobile"><?php echo $i;  ?></td> 
                                 <td class="hidden-mobile"><?php
                                 echo $travellers[0];
                                 ?></td>
                <td class="hidden-mobile"><?php echo $reservation->getReferenceNumber(); ?></td> 
                <td class="hidden-mobile"><?php echo $affiliateinfo ?></td> 

                <td class="hidden-mobile"><?php echo $reservation->getCreatedAt()->format("Y-m-d"); ?></td>

                <?php if ($type == 'FIT') { ?>
                    <td class="hidden-mobile"><?php echo "Resort"; ?></td>   
                <?php }if ($type == 'Group') { ?>
                    <td class="hidden-mobile"><?php echo "Event"; ?></td>   

                <?php }if ($type == 'Cruise') { ?>
                    <td class="hidden-mobile"><?php echo "Cruises"; ?></td>   
                <?php } ?>

                <td class="hidden-mobile"><?php echo $hotelName; ?></td> 


                <td class="hidden-mobile"><?php echo $reservation->getCurrencyCode() . ' ' . $reservation->getFinalCost(); ?></td>
                <td class="hidden-mobile"><?php echo $status; ?></td>
                <td class="action-table">                            
                    <a href="<?php echo $this->url('orders-pending-view', array('id' => $reservation->getId())); ?>" title="View">
                        <img src="/images/icon/table_view.png" alt="View">
                    </a>


                    <a href="<?php echo $this->url('order-apply-payment', array('id' => $reservation->getId())); ?>"  title="Apply Payment">
                        <img src="/images/icon/icon_cont_check.png" alt="Apply Payment">
                    </a>
                      <a href="<?php echo $this->url('orders-edit', array('id' => $reservation->getId())); ?>" title="Update">
                                <img src="/images/icon/table_edit.png" alt="Update">
                            </a>
                    <a href="<?php echo $this->url('orders-pending-sendmail', array('id' => $reservation->getId())); ?>"  title="Email Client">
                        Email client
                    </a>

<!--                    <a href="<?php echo $this->url('orders-pending-delete', array('id' => $reservation->getId())); ?>" data-confirm="Are you sure?" title="Delete">
                        <img src="/images/icon/table_del.png" alt="Delete">
                    </a>-->
                    
                     <a href="javascript:void"  onclick="return removeSingle(<?php echo $reservation->getId();?>)"title="Delete">
                                <img src="/images/icon/delete-icon.gif" alt="Delete">
                            </a>

                </td>

                </tr>                    
                <?php endforeach; ?>
                </tbody>
                </table>
                </form>
                <br><br>
                <p> Total Orders :	
                    <?php echo $i . ' , '; ?>
                    Order Total :	
                    <?php echo '$' . $total; ?>
                </p>
                <div class="clearfix"></div>
        </div>
    </div>

<style>
    .updated{
        background: #ccc;
    }
    
    .rem-checked{
        margin-left: 350px;
    }
    </style>
    
    <script>
        function removeChecked(){
            if (confirm("Are you sure!") == true) {
                $("#formview").submit();
        } else {
            return false;
        }
            
        }
        
         function removeSingle(id){
            if (confirm("Are you sure!") == true) {
                location.href='<?php echo $this->serverUrl();?>/admin/reservation/delete/'+id;
        } else {
            return false;
        }
            
        }
        
        $(document).ready(function(){
            $('#c0').click(function(){
                if($('#c0').is(":checked") == true){
                    $('.checkb').prop('checked', true);
                    $(".rem-checked").show();
                    
                }else{
                    $('.checkb').prop('checked', false);
                    $(".rem-checked").hide();
                }
            })
            
            
            $('.checkb').click(function(){
               var flag;
                $('.checkb').each(function(){
                   var checked=$(this).is(':checked');
                    if(checked==true){
                        flag=true;
                    }
                });
                if(flag){
                    $(".rem-checked").show();
                }else{
                    $(".rem-checked").hide();
                }
            });
            $(".rem-checked").hide();
        })
        </script>
        

    
