<?php 
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url(
		'receipts-edit',array('id'=>$receipt->getId())
));
$form->setAttribute('method', 'post');



?>
<div class="grid">
	<div class="grid-title">
		<div class="pull-left">
			<div class="icon-title">
				<i class="icon-plus"></i>
			</div>
			<span>Edit Receipt</span>
			<div class="clearfix"></div>
		</div>
		<div class="clearfix"></div>
	</div>
	<?php echo $this->form()->openTag($form); ?>
        <input type="hidden" name="id" value="<?php echo $receipt->getId(); ?>">
	<div class="grid-content">
		<div class="formRow control-group">
			<?php echo $this->formLabel($form->get('name')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('name')->setAttribute('class', 'span input')); ?>
	        	<?php echo $this->formElementErrors($form->get('name'), array('class' => 'help-inline')); ?>
			</div>
		</div>
                
		<div class="formRow control-group">
			<?php echo $this->formLabel($form->get('email')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('email')->setAttribute('class', 'span input')); ?>
	        	<?php echo $this->formElementErrors($form->get('email'), array('class' => 'help-inline')); ?>
			</div>
		</div>
                <div class="formRow control-group">
			<?php echo $this->formLabel($form->get('phone')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('phone')->setAttribute('class', 'span input')); ?>
	        	<?php echo $this->formElementErrors($form->get('phone'), array('class' => 'help-inline')); ?>
			</div>
		</div>  
                <div class="formRow control-group">
			<?php echo $this->formLabel($form->get('address')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('address')->setAttribute('class', 'span input same-height-1')->setAttribute('rows', '3')); ?>
	        	<?php echo $this->formElementErrors($form->get('address'), array('class' => 'help-inline')); ?>
			</div>
		</div>
		<div class="formRow control-group">
			<?php echo $this->formLabel($form->get('suite')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('suite')->setAttribute('class', 'span input')); ?>
	        	<?php echo $this->formElementErrors($form->get('suite'), array('class' => 'help-inline')); ?>
			</div>
		</div>
		<div class="formRow control-group">
			<?php echo $this->formLabel($form->get('city')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('city')->setAttribute('class', 'span input')); ?>
	        	<?php echo $this->formElementErrors($form->get('city'), array('class' => 'help-inline')); ?>
			</div>
		</div>		
		<div class="formRow control-group">
			<?php echo $this->formLabel($form->get('state')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('state')->setAttribute('class', 'span input')); ?>
	        	<?php echo $this->formElementErrors($form->get('state'), array('class' => 'help-inline')); ?>
			</div>
		</div>		
		<div class="formRow control-group">
			<?php echo $this->formLabel($form->get('countryId')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('countryId')->setAttribute('class', 'chzn-select chosen_select width-100')); ?>
	        	<?php echo $this->formElementErrors($form->get('countryId'), array('class' => 'help-inline')); ?>
			</div>
		</div>		
		<div class="formRow control-group">
			<?php echo $this->formLabel($form->get('zip')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('zip')->setAttribute('class', 'span input')); ?>
	        	<?php echo $this->formElementErrors($form->get('zip'), array('class' => 'help-inline')); ?>
			</div>
		</div>
                <div class="formRow control-group">
			<?php echo $this->formLabel($form->get('total_received')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('total_received')->setAttribute('class', 'span input')); ?>
	        	<?php echo $this->formElementErrors($form->get('total_received'), array('class' => 'help-inline')); ?>
			</div>
		</div>
                <div class="formRow control-group">
			<?php echo $this->formLabel($form->get('date')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('date')->setAttribute('class', 'span input')); ?>
	        	<?php echo $this->formElementErrors($form->get('date'), array('class' => 'help-inline')); ?>
			</div>
		</div>
		<div class="formRow control-group">
			<?php echo $this->formLabel($form->get('for_type')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('for_type')->setAttribute('class', 'chzn-select chosen_select width-100')); ?>
	        	<?php echo $this->formElementErrors($form->get('for_type'), array('class' => 'help-inline')); ?>
			</div>
		</div>
            <div class="formRow control-group">
                        <div class="formRight" id='users'>
				
			</div>
            </div>
                <div class="formRow control-group">
			<?php echo $this->formLabel($form->get('description')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('description')->setAttribute('class', 'span input same-height-1')->setAttribute('rows', '3')); ?>
	        	<?php echo $this->formElementErrors($form->get('description'), array('class' => 'help-inline')); ?>
			</div>
		</div>
                
		<div class="formRow control-group">
			<?php echo $this->formSubmit( $form->get('submit')->setAttribute('class', 'btn btn-info')) ?>
                        
		</div>
		<div class="clearfix"></div>
	</div>
	<?php echo $this->form()->closeTag() ?>
</div>

<script>
			
				
	$(function(){
		$('.grid-content .formRow ul.help-inline').parents('.formRow').addClass('error');
		$('.error input').keyup(function(){
					$(this).parents('.formRow').removeClass('error');
					$(this).next('ul.help-inline').remove();
		});

		$('#pass1, #pass2').keyup(checkPass);
	});				
</script>

<script>
   
  $('#myselect').change(function(){        
        var id = $(this).val();   
        var typeid=<?php $this->typeId; ?>
//        alert(id);
        $.post('/admin/report/ajax/commision/type/'+id+'/'+typeid+'/reseller', {id:id,typeid:typeid}, function(data){
            
//            alert(data);
            $('#users').html(data); 
        });        
    });
    
   
 </script>   
<style>
    select{
        width:100%;
    }
</style>