<?php
if (!is_null($this->message)):
    if ($this->message):
        ?>		
        <div class="alert alert-dismissable alert-<?php echo $this->message[0]['type']; ?>">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <ul>
                <li><?php echo $this->message[0]['message']; ?></li>        
            </ul>
        </div>
        <?php 
    endif;
endif;


?>



<div class="grid">
	<div class="grid-title">
		<div class="pull-left">
			<div class="icon-title">
				<i class="icon-plus"></i>
			</div>
			<span>Receipt's</span>
			<div class="clearfix"></div>
		</div>
        
		
	</div>
	<div class="grid-content overflow">
                <table class="table table-bordered table-mod-2" id="datatable_3">
            <thead>
                <tr>
                    <th class="hidden-mobile">Receipt No</th>
                    <th class="hidden-mobile">Sent On</th>
                    <th class="hidden-mobile">To</th>    
                    <th class="hidden-mobile">Actions</th>                    
                </tr>
            </thead>
            <tbody>
           <?php foreach($this->receipt as $rec){?>
            <tr>    
                <td><?php echo $rec->getId(); ?></td>
                <td><?php echo $rec->getDate()->format('M d, Y');?></td>
                <td><?php echo $rec->getName();?></td>
                <td class="action-table">
                            <a data-toggle="modal" title="View" href="<?php echo $this->url('receipts-view', array('id' => $rec->getId())); ?>" data-target=".bs-example-modal-lg">
                                <img src="/images/icon/table_view.png" alt="">
                            </a>
                            <a title="Re-send Email" href="<?php echo $this->url('receipts-sendmail', array('id' => $rec->getId())); ?>">
                                <img src="/images/icon/envelope.png" alt="">
                            </a>
                            <a title="Edit" href="<?php echo $this->url('receipts-edit', array('id' => $rec->getId())); ?>">
                                <img src="/images/icon/table_edit.png" alt="">
                            </a>
                            <a title="Delete" href="<?php echo $this->url('receipts-delete', array('id' => $rec->getId())); ?>"data-confirm="Are you sure?">
                                <img src="/images/icon/table_del.png" alt="">
                            </a>
                            
                </td>
           </tr>     
           <?php } ?>
            </tbody>
        </table>
		<div class="clearfix"></div>
	</div>
	
</div>
<?php echo $this->partial('users/ajax/modal.phtml');?>
<script>

				
				
	$(function(){
		$('.grid-content .formRow ul.help-inline').parents('.formRow').addClass('error');
		$('.error input').keyup(function(){
					$(this).parents('.formRow').removeClass('error');
					$(this).next('ul.help-inline').remove();
		});

		$('#pass1, #pass2').keyup(checkPass);
	});				
</script>


