<?php 
    $form = $this->form;
    //if((int)$post['paymentType'] == 1){
        $final=$paymentData['deposit']+($paymentData['deposit']*0.025);
        $final=round($final, 2);
        $mfee=$paymentData['deposit']*0.025;
    //}
//    d($paymentData['paymentArray']);
?>

<div class="formRow control-group">
   
<!--    <div class="formRight">
        <div class="distance distance-2 payment-type">
            <p>
                <input type="radio" name="depositMethod" id="deposit-due" value="0"  <?php if(!$form->get('depositMethod')->getValue()) echo 'checked="checked"';?>>
                <label for="deposit-due"><span></span> Pay</label>
            </p>
            <p>
                <input type="radio" name="depositMethod" id="rcvd" value="1"  <?php if($form->get('depositMethod')->getValue()) echo 'checked="checked"';?>>
                <label for="rcvd"><span></span> RCVD</label>
            </p>
        </div>
    </div>-->
</div>
    <div class="formRow control-group">
        <div class="labelNew"><?php echo $this->formLabel($form->get('depositAmount')); ?></div>
        <div class="formRight input-prepend inputDiv">
            <span class="add-on">$</span>
            <?php echo $this->formElement($form->get('depositAmount')
                                               ->setAttribute('readonly', 'readonly')
                                               ->setAttribute('class', 'span8 input inputBox')->setAttribute('value',$paymentData['deposit'])); ?>
            <?php // echo $this->formElementErrors($form->get('depositAmount'), array('class' => 'help-inline')); ?>
        </div>
    </div>
<!--    <input type="hidden" name="depositAmount" value="<?php echo $paymentData['deposit']; ?>">
    <input type="hidden" name="mFee" value="<?php echo $mfee; ?>">
    <div class="formRow control-group">
        <div class="labelNew"><?php echo $this->formLabel($form->get('depositAmount')); ?></div>
        <div class="formRight input-prepend inputDiv">
            <span class="add-on">$</span>
            <input type="text" value="<?php echo $final; ?>" readonly>
        </div>
    </div>-->



<?php 
if((int)$post['paymentType'] == 0): ?>

<div class="formRow control-group">
        <div class="labelNew"><?php echo $this->formLabel($form->get('balansAfterDeposit')); ?></div>
        <div class="formRight input-prepend inputDiv">
            <span class="add-on">$</span>
            <?php echo $this->formElement($form->get('balansAfterDeposit')->setAttribute('class', 'span8 input inputBox')->setAttribute('readonly', 'readonly')->setAttribute("value",$paymentData['balance'])); ?>
            <?php echo $this->formElementErrors($form->get('balansAfterDeposit'), array('class' => 'help-inline')); ?>
        </div>
</div>

<?php foreach($paymentData['paymentArray'] as $payment ):
    $i =1;
    ?>
    <div class="formRow control-group">
        <div class="labelNew"><?php echo $this->formLabel($form->get('nextPaymentDue[]')); ?></div>
        <div class="formRight input-prepend inputDiv">
            <span class="add-on">$</span>
            <?php echo $this->formElement($form->get('nextPaymentDue[]')->setAttribute('class', 'span8 input cnt inputBox')
                                                                        ->setAttribute('id', 'dueAmount'+$i)
                                                                        ->setAttribute('readonly', 'readonly')
                                                                        ->setAttribute('value',$payment['dueAmount'])); ?>
            <?php echo $this->formElementErrors($form->get('nextPaymentDue[]'), array('class' => 'help-inline')); ?>
        </div>
    </div>
    <div class="formRow control-group">
        <div class="labelNew"><?php echo $this->formLabel($form->get('dueDate1[]')); ?></div>
        <div class="formRight inputDiv">
            <?php echo $this->formElement($form->get('dueDate1[]')
                                               ->setAttribute('id', 'dueDate'+i)
                                               ->setAttribute('type', 'text')
                                               ->setAttribute('readonly', 'readonly')
                                               ->setAttribute('value',$payment['maxFinalPaymentDue']->format("Y-m-d"))
                                               ->setAttribute('class', 'span input inputBox')); ?>
            <?php // echo $this->formElementErrors($form->get('dueDate1[]'), array('class' => 'help-inline')); ?>
        </div>
    </div>
<?php endforeach;?>
<!--    <div class="formRow control-group">			
    <div class="formRight">
        <input type="button" value="Add" class="btn btn-info" id="addduebutton" name="dueButton">     	
    </div>
</div>-->
<?php endif;?>

<style>
    .labelNew{
        width:40% !important;
        float:left !important;
        font-size:15px !important;
    }
    .inputDiv{
        width:50% !important;
        float:left !important;
    }
    .inputBox{
        width:50% !important;
    }
    </style>