<!doctype html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<title>Payment Reminder</title>
	<link rel="stylesheet" href="/css/estilos.css">
</head>
<body>
    <div class="gral" style="margin-top: 100px; max-width: 90%;">
        <div class="span6" style="height: 400px; width: 100%; background: white;">
        
        <center><h2 style="margin-top: 50px; font-size: 30pt;"> <?php echo $msg; ?></h2></center>
        </div>
    </div>
    
</body>
</html>