<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Marketing\Module'                        => __DIR__ . '/Module.php',
    'Marketing\Controller\MarketingController' => __DIR__ . '/src/Marketing/Controller/MarketingController.php',
);
