<?php 

$form = $this->form;

$form->prepare();
$form->setAttribute('action', $this->url(
		'inventory-excursions-add'
));

$form->setAttribute('method', 'post');

?>
<div class="grid">
	<div class="grid-title">
		<div class="pull-left">
			<div class="icon-title">
				<i class="icon-plus"></i>
			</div>
			<span>Add New Excursion</span>
			<div class="clearfix"></div>
		</div>
		<div class="clearfix"></div>
	</div>
	<?php echo $this->form()->openTag($form); ?>
	<div class="grid-content">
            
            <div class="formRow control-group">
                    <?php echo $this->formLabel($form->get('excursionName')); ?>
                    <div class="formRight">
                            <?php echo $this->formElement($form->get('excursionName')->setAttribute('class', 'span input')); ?>
                    <?php echo $this->formElementErrors($form->get('excursionName'), array('class' => 'help-inline')); ?>
                    </div>
            </div>
            <div class="formRow control-group">
                    <?php echo $this->formLabel($form->get('supplierName')); ?>
                    <div class="formRight">
                            <?php echo $this->formElement($form->get('supplierName')->setAttribute('class', 'span input')); ?>
                    <?php echo $this->formElementErrors($form->get('supplierName'), array('class' => 'help-inline')); ?>
                    </div>
            </div>                    
            <div class="formRow control-group">
                    <?php echo $this->formLabel($form->get('resortId')); ?>
                    <div class="formRight">
                            <?php echo $this->formElement($form->get('resortId')->setAttribute('class', 'chzn-select chosen_select width-100')); ?>
                    <?php echo $this->formElementErrors($form->get('resortId'), array('class' => 'help-inline')); ?>
                    </div>
            </div>            
            <div class="formRow control-group">
                    <?php echo $this->formLabel($form->get('numberAvailable')); ?>
                    <div class="formRight">
                            <?php echo $this->formElement($form->get('numberAvailable')->setAttribute('class', 'span input')); ?>
                    <?php echo $this->formElementErrors($form->get('numberAvailable'), array('class' => 'help-inline')); ?>
                    </div>
            </div>                                 
            <div class="formRow control-group">
                    <?php echo $this->formLabel($form->get('netPrice')->setAttribute('class', 'span input')); ?>
                    <div class="formRight">
                            <?php echo $this->formElement($form->get('netPrice')); ?>
                    <?php echo $this->formElementErrors($form->get('netPrice'), array('class' => 'help-inline')); ?>
                    </div>
            </div>            
            <div class="formRow control-group">
                    <?php echo $this->formLabel($form->get('grossPrice')->setAttribute('class', 'span input')); ?>
                    <div class="formRight">
                            <?php echo $this->formElement($form->get('grossPrice')); ?>
                    <?php echo $this->formElementErrors($form->get('grossPrice'), array('class' => 'help-inline')); ?>
                    </div>
            </div>                        
            <div class="formRow control-group">
                    <?php echo $this->formSubmit( $form->get('submit')->setAttribute('class', 'btn btn-info')) ?>
                    <input id="resetbutton" class="btn btn-info" type="reset" value="Reset" name="reset"></input>
            </div>
            <div class="clearfix"></div>

	</div>
	<?php echo $this->form()->closeTag() ?>
</div>

<script>				
$(function(){
    $('.grid-content .formRow ul.help-inline').parents('.formRow').addClass('error');
    $('.error input').keyup(function(){
                            $(this).parents('.formRow').removeClass('error');
                            $(this).next('ul.help-inline').remove();
    });
});				
</script>


