
 <select id="resorts" name="resortId" required="required" class="span input chzn-select">                    
        <?php foreach ($this->collection as $item):?>                
            <option value="<?php echo $item->getId();?>"><?php echo $item->getFirstName();?> <?php echo $item->getLastName(); ?></option>
        <?php endforeach;?> 
            </select> 
    
            
            <script>
    $(document).ready(function(){
        $('.chzn-select').chosen();
    });
</script>

