<?php 

$form = $this->form;

$form->prepare();
$form->setAttribute('action', $this->url(
		'ports-add'
));

$form->setAttribute('method', 'post');

?>
<div class="grid">
	<div class="grid-title">
		<div class="pull-left">
			<div class="icon-title">
				<i class="icon-plus"></i>
			</div>
			<span>Add New Port</span>
			<div class="clearfix"></div>
		</div>
		<div class="clearfix"></div>
	</div>
	<?php echo $this->form()->openTag($form); ?>
	<div class="grid-content">
	
                <div class="formRow control-group">
			<?php echo $this->formLabel($form->get('cruiseId')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('cruiseId')->setAttribute('class', 'chzn-select chosen_select width-100')->setAttribute('required', 'required')); ?>
	        	<?php echo $this->formElementErrors($form->get('cruiseId'), array('class' => 'help-inline')); ?>
			</div>
		</div>	
            
		<div class="formRow control-group">
			<?php echo $this->formLabel($form->get('title')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('title')->setAttribute('class', 'span input')->setAttribute('required', 'required')); ?>
	        	<?php echo $this->formElementErrors($form->get('title'), array('class' => 'help-inline')); ?>
			</div>
		</div>
		
		<div class="formRow control-group">
			<?php echo $this->formLabel($form->get('description')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('description')->setAttribute('class', 'ckeditor')); ?>
	        	<?php echo $this->formElementErrors($form->get('description'), array('class' => 'help-inline')); ?>
			</div>
		</div>
		
		<div class="formRow control-group">
			<?php echo $this->formLabel($form->get('thingsToDo')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('thingsToDo')->setAttribute('class', 'ckeditor')); ?>
	        	<?php echo $this->formElementErrors($form->get('thingsToDo'), array('class' => 'help-inline')); ?>
			</div>
		</div>
		
		<div class="formRow control-group">
			<?php echo $this->formLabel($form->get('dontMiss')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('dontMiss')->setAttribute('class', 'ckeditor')); ?>
	        	<?php echo $this->formElementErrors($form->get('dontMiss'), array('class' => 'help-inline')); ?>
			</div>
		</div>

                <div class="formRow control-group">
			<?php echo $this->formSubmit( $form->get('submit')->setAttribute('class', 'btn btn-info')) ?>
                        <input id="resetbutton" class="btn btn-info" type="reset" value="Reset" name="reset"></input>
		</div>
		<div class="clearfix"></div>

	</div>
	<?php echo $this->form()->closeTag() ?>
</div>

<script>

				
	$(function(){
		$('.grid-content .formRow ul.help-inline').parents('.formRow').addClass('error');
		$('.error input').keyup(function(){
					$(this).parents('.formRow').removeClass('error');
					$(this).next('ul.help-inline').remove();
		});

		
	});				
</script>


