<?php
if ($this->message):
    ?>		
    <div class="alert alert-dismissable alert-<?php echo $this->message[0]['type']; ?>">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <ul>
            <li><?php echo $this->message[0]['message']; ?></li>        
        </ul>
    </div>
    <?php
endif;
?>

<div class="grid">

    <div class="grid-title">
        <div class="pull-left">
            <div class="icon-title">
                <i class="icon-list"></i>
            </div>
            <span>Ports</span>
            <div class="clearfix"></div>
        </div>
        <div class="pull-right">
            <div class="icon-title">
                <a href="<?php echo $this->url('ports-add'); ?>"><i class="icon-plus-sign"></i></a>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>

    <div class="grid-content overflow">

        <table class="table table-bordered table-mod-2" id="datatable_3">
            <thead>
                <tr>
                    <th class="t_center">
                        <input type="checkbox" id="c0" name="cc" />
                        <label for="c0"><span></span></label>
                    </th>					
                    <th class="hidden-mobile">Title</th>
                    <th class="hidden-mobile">Description</th>								
                    <th class="hidden-mobile">Things To Do</th>
                    <th class="hidden-mobile">Don't Miss</th>
                    <th class="hidden-mobile">Cruise</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <?php $i = 1;
                foreach ($this->collection as $item): ?>
                    <tr>
                        <td class="t_center">
                            <input type="checkbox" id="c<?php echo $i; ?>" name="cc" />
                            <label for="c<?php echo $i; ?>"><span></span></label>
                        </td>
                        <td class="hidden-mobile"><?php echo substr($item['title'], 0, 50) . '...'; ?></td>
                        <td class="hidden-mobile"><?php echo substr(strip_tags($item['description']), 0, 50) . '...'; ?></td>
                        <td class="hidden-mobile"><?php echo substr(strip_tags($item['thingsToDo']), 0, 50) . '...'; ?></td>
                        <td class="hidden-mobile"><?php echo substr(strip_tags($item['dontMiss']), 0, 50) . '...'; ?></td>						
                        <td class="hidden-mobile">
                                            <a data-toggle="modal" href="<?php echo $this->url('ajax-cruises-item', array('id' => $item['cruiseId']));?>" data-target=".bs-example-modal-lg">
                                                <?php echo $item['cruiseTitle']; ?>
                                            </a>
                        </td>
                        <td class="action-table">
                            <!-- 						<a href="javascript:void(0);"> -->
                            <!-- 							<img src="/images/icon/table_view.png" alt=""> -->
                            <!-- 						</a> -->
                            <a href="<?php echo $this->url('ports-edit', array('id' => $item['id'])); ?>">
                                <img src="/images/icon/table_edit.png" alt="">
                            </a>
                            <a href="<?php echo $this->url('ports-delete', array('id' => $item['id'])); ?>"
                               data-confirm="Are you sure?">
                                <img src="/images/icon/table_del.png" alt="">
                            </a>
                        </td>
                    </tr>
                    <?php $i++; ?>
<?php endforeach; ?>
            </tbody>
        </table>
        <div class="clearfix"></div>
    </div>
</div>
<?php echo $this->partial('sales-objects/ajax/modal.phtml');?>