<?php 
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url(
		'marketing-image-add'
));
$form->setAttribute('method', 'post');
$form->setAttribute('enctype', 'multipart/form-data');


?>
<div class="grid">
	<div class="grid-title">
		<div class="pull-left">
			<div class="icon-title">
				<i class="icon-plus"></i>
			</div>
			<span>Add New PDF</span>
			<div class="clearfix"></div>
		</div>
		<div class="clearfix"></div>
	</div>
	<?php echo $this->form()->openTag($form); ?>
	<div class="grid-content">
		<div class="formRow control-group">
			<?php echo $this->formLabel($form->get('name')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('name')->setAttribute('class', 'span input')); ?>
	        	<?php echo $this->formElementErrors($form->get('name'), array('class' => 'help-inline')); ?>
			</div>
		</div>
                
		
		<div class="formRow control-group">
			<?php echo $this->formLabel($form->get('for_type')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('for_type')->setAttribute('class', 'chzn-select chosen_select width-100')); ?>
	        	<?php echo $this->formElementErrors($form->get('for_type'), array('class' => 'help-inline')); ?>
			</div>
		</div>
            
                <div class="formRow control-group">
                            <div class="formRight" id='users'>

                            </div>
                </div>
            
                <div class="formRow control-group">
			<?php echo $this->formLabel($form->get('image')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('image')->setAttribute('required', 'required')); ?>
	        	<?php echo $this->formElementErrors($form->get('image'), array('class' => 'help-inline')); ?>
			</div>
                </div>
                
		<div class="formRow control-group">
			<?php echo $this->formSubmit( $form->get('submit')->setAttribute('class', 'btn btn-info')) ?>
                       
                        <input id="resetbutton" class="btn btn-info" type="reset" value="Reset" name="reset"></input>
		</div>
		<div class="clearfix"></div>
	</div>
	<?php echo $this->form()->closeTag() ?>
</div>

<script>
			
				
	$(function(){
		$('.grid-content .formRow ul.help-inline').parents('.formRow').addClass('error');
		$('.error input').keyup(function(){
					$(this).parents('.formRow').removeClass('error');
					$(this).next('ul.help-inline').remove();
		});

		$('#pass1, #pass2').keyup(checkPass);
	});				
</script>

<script>
   
  $('#myselect').change(function(){        
        var id = $(this).val();   
        var typeid=<?php $this->typeId; ?>
//        alert(id);
        $.post('/admin/report/ajax/commision/type/'+id+'/'+typeid+'/reseller', {id:id,typeid:typeid}, function(data){
            
//            alert(data);
            $('#users').html(data); 
        });        
    });
    
   
 </script>   
<style>
    select{
        width:100%;
    }
</style>