<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url(
		'marketing-newsletter-add'
));
$form->setAttribute('method', 'post');



?>
<div class="grid">
	<div class="grid-title">
		<div class="pull-left">
			<div class="icon-title">
				<i class="icon-plus"></i>
			</div>
			<span>Newsletter</span>
			<div class="clearfix"></div>
		</div>
		<div class="clearfix"></div>
	</div>
	<?php echo $this->form()->openTag($form); ?>
	<div class="grid-content">
                <div class="formRow control-group">
			<?php echo $this->formLabel($form->get('to')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('to')->setAttribute('class', 'chzn-select chosen_select width-100')); ?>
	        	<?php echo $this->formElementErrors($form->get('to'), array('class' => 'help-inline')); ?>
			</div>
		</div>
                <div class="formRow control-group">
			<?php echo $this->formLabel($form->get('subject')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('subject')->setAttribute('class', 'span input')); ?>
                                
	        	<?php echo $this->formElementErrors($form->get('subject'), array('class' => 'help-inline')); ?>
			</div>
		</div>
                <div class="formRow control-group">
			<?php echo $this->formLabel($form->get('message')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('message')->setAttribute('class', 'span input same-height-1')->setAttribute('rows', '3')); ?>
	        	<?php echo $this->formElementErrors($form->get('message'), array('class' => 'help-inline')); ?>
			</div>
		</div>  
                
		
		<div class="formRow control-group">
			<?php echo $this->formSubmit( $form->get('submit')->setAttribute('class', 'btn btn-info')) ?>
                        <input id="resetbutton" class="btn btn-info" type="reset" value="Reset" name="reset"></input>
		</div>
		<div class="clearfix"></div>
	</div>
	<?php echo $this->form()->closeTag() ?>
</div>

<script>

	function checkPass(){

		var pass = $('#pass1').val();
		var repass = $('#pass2').val();

		console.log(pass !== repass && pass == '');
		
		if(pass !== repass || pass == '' || repass == ''){
			$('#pass1, #pass2').parents('.formRow').addClass('error');//.append('<ul class="help-inline"><li>Password does not match the confirm password</li></ul>')
			$('#submitbutton').attr('disabled', 'disabled');
		}else{
			$('#pass1, #pass2').parents('.formRow').removeClass('error').addClass('success');
			$('#submitbutton').removeAttr('disabled');
		} 
	};			
				
	$(function(){
		$('.grid-content .formRow ul.help-inline').parents('.formRow').addClass('error');
		$('.error input').keyup(function(){
					$(this).parents('.formRow').removeClass('error');
					$(this).next('ul.help-inline').remove();
		});

		$('#pass1, #pass2').keyup(checkPass);
	});				
</script>


