<?php
if (!is_null($this->message)):
    if ($this->message):
        ?>		
        <div class="alert alert-dismissable alert-<?php echo $this->message[0]['type']; ?>">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <ul>
                <li><?php echo $this->message[0]['message']; ?></li>        
            </ul>
        </div>
        <?php 
    endif;
endif;


?>
<div class="grid">
	<div class="grid-title">
		<div class="pull-left">
			<div class="icon-title">
				<i class="icon-plus"></i>
			</div>
			<span>PDF</span>
			<div class="clearfix"></div>
		</div>
        
		<div class="clearfix"></div>
	</div>
	<div class="grid-content overflow">
                <table class="table table-bordered table-mod-2" id="datatable_3">
            <thead>
                <tr>
                    <th class="hidden-mobile">Pdf</th>
                    <th class="hidden-mobile">Type</th>
                    <th class="hidden-mobile">Name</th>
                    <th class="hidden-mobile">Date</th>
                    <th class="hidden-mobile">Actions</th>                    
                </tr>
            </thead>
             <tbody>
                <?php foreach($pdf as $pdfs){?>
                <tr>
                    <td><?php echo $pdfs->getFile();?></td>
                    <td><?php $to = $pdfs->getType(); if($to==1){echo "Resort";}if($to==2){echo "Event";}if($to==3){echo "Cruise";} if($to==4){echo "Items";}if($to==5){echo "Excursion";}if($to==6){echo "Transfer";}?></td>
                    <td><?php echo "New Template 1";?></td>
                    <td><?php echo $pdfs->getCreated()->format('M d, Y');?></td>
                    <td class="action-table">
                        <a title="Download" href="/img/user_uploads/userdocuments/<?php echo $pdfs->getFile();?>" download>
                                <img src="/images/icon/download-icon.png" alt="">
                            </a>
<!--                            <a title="Delete" href="<?php echo $this->url('manageclients-deletenotes', array('id' => $pdfs->getId())); ?>"data-confirm="Are you sure?">
                                <img src="/images/icon/table_del.png" alt="">
                            </a>-->
                    </td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
		<div class="clearfix"></div>
	</div>
	
</div>
<?php echo $this->partial('users/ajax/modal.phtml');?>



