<label for="suiteId" class="required">Suite Name</label>                    
<div class="formRight">    
    <select name="suiteId" required="required" class="chzn-select chosen_select width-100 cabinId">        
        <option value="">please select suite...</option>
        <?php foreach ($this->collection as $item):?>                
            <option value="<?php echo $item['id'];?>"><?php echo $item['suiteName'];?></option>
        <?php endforeach;?>    
    </select> 
</div>
<script>
    $('.chzn-select').chosen();
    
      $('.cabinId').change(function() {
        var id = $(this).val();
        $.post('/admin/inventory/ajax/cruise/cabinbyid/' + id, {id: id}, function(data) {
            d = jQuery.parseJSON(data);
           // $("#noa").val(d.stock);
            $("#deckNumber").val(d.deckNumber);
            $("#netPrice").val(d.price);
        });
    });
</script>