<label for="roomId" class="required">Room Category</label>                    
<div class="formRight">    
    <select name="roomId" required="required" class="chzn-select chosen_select width-100 roomId">        
        <option value="">please select room...</option>
        <?php foreach ($this->collection as $item): ?>                
            <option value="<?php echo $item['id']; ?>"<?php if($this->roomId == $item['id']) echo 'selected="selected"' ;?>><?php echo $item['roomCategory']; ?></option>
        <?php endforeach; ?>    
    </select> 
</div>
<script>
    $('.chzn-select').chosen();

    $('.roomId').change(function() {
        var id = $(this).val();
        $.post('/admin/inventory/ajax/resort/roomsbyid/' + id, {id: id}, function(data) {
            d = jQuery.parseJSON(data);
           // $("#noa").val(d.stock);
            $("#netPrice").val(d.price);
        });
    });
</script>