<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Manageclients\Module'                        => __DIR__ . '/Module.php',
    'Manageclients\Controller\ManageclientsController' => __DIR__ . '/src/Manageclients/Controller/ManageclientsController.php',
);
