<script>
    function printPage(id) 
    {
        var mywindow = window.open('<?php echo $this->url('print-reservation')?>'+id, 'Advanced Communication Skills', 'left=10,top=10,height=700,width=700,scrollbars=1,resizable=1');
    }
</script>
<div class="grid">
	<div class="grid-title">
		<div class="pull-left">
			<div class="icon-title">
                            <i class="icon-list"></i>
                        </div> 
			<span>Reservations</span>
			<div class="clearfix"></div>
		</div>
		<div class="clearfix"></div>
	</div>
	
	
	
	
</div>
<div class="grid">    
    <div class="grid-content overflow">
        
        
        <div class="formRight">
            <form method="post" action="<?php
            echo $this->url(
                    'orders'
            );
            ?>">


                Date From : <input type="date" id="startDate" name="mydate" class="">  
                Date To : <input type="date" id="endDate" name="mydate1" class="">       
                <input type="submit" name="submit" class="btn btn-info" id="btnmargin" value="Search">
        </form> </div>

        <table class="table table-bordered table-mod-2" id="datatable_3">
            <thead>
                <tr>                    
                 <!--   <th class="hidden-mobile">Reservation No.</th> -->
                    <th class="hidden-mobile">Name</th>
                    <th class="hidden-mobile">Order No.</th>
                    <th class="hidden-mobile">Order Total</th>
		    <th class="hidden-mobile">Type</th> 
                    <th class="hidden-mobile">Status</th>
                    <th class="hidden-mobile">Actions</th>
                    					
                </tr>
            </thead>
            <tbody>
                <?php      $total=0;   $i=0;                
                    foreach ($this->collection as $item): 
                     
		    $hotelName = $item['hotelName'];    
                    $type = $item['type'];
                    $roomName = $item['roomName'];
                    $travellers = $item['travellers'];
                    $reservation = $item['reservation'];
                    $status = $item['status'];

		    $total=($total + $reservation->getTotalCost());
		    $i++;
?>                  
                
                    <tr>
                     <!--   <td class="hidden-mobile"><?php //echo $reservation->getId(); ?></td>        -->                
                        <td class="hidden-mobile"><?php  
                                foreach ($travellers as $traveller){
                                    echo $traveller.', ';
                                }
                        
                        ?></td>
			<td class="hidden-mobile"><?php echo $reservation->getId(); ?></td> 
                <!--        <td class="hidden-mobile"><?php //echo $hotelName; ?></td> -->
                        <td class="hidden-mobile"><?php echo '$'.$reservation->getTotalCost(); ?></td>

                     <!--    <td class="hidden-mobile"><?php //echo $type; ?></td>   -->
                         
                         <?php if($type=='FIT'){ ?>
                         <td class="hidden-mobile"><?php echo "Resort"; ?></td>   
                         <?php }if($type=='Group'){ ?>
                         <td class="hidden-mobile"><?php echo "Event"; ?></td>   
                             
                         <?php }if($type=='Cruise'){ ?>
			<td class="hidden-mobile"><?php echo "Cruises"; ?></td>   
                         <?php }?>

                        <td class="hidden-mobile"><?php echo $status; ?></td> 
                        <td class="action-table">                            
                            <a href="<?php echo $this->url('orders-view', array('id' => $reservation->getId())); ?>" title="View">
                                <img src="/images/icon/table_view.png" alt="View">
                            </a>
                          <a href="<?php //echo $this->url('orders-edit', array('id' => $reservation->getId())); ?>" title="Update">
                                <img src="/images/icon/table_edit.png" alt="Update">
                            </a>
                            <a href="/admin/reservation/cancel/<?php echo $item['id'] ; ?>" title="Cancel">
                                <img src="/images/icon/table_del.png" alt="Cancel">
                            </a>
                            <a title="Print" href="javascript:printPage(<?php echo $item['id'] ; ?>)">
                                <i class="icon-print"></i>
                            </a>
                            <a title="Reinstate" href="javascript:alert('In Progress...')">
                                <i class="icon-resend"></i>
                            </a>
                        </td>
                         
                    </tr>                    
                <?php endforeach; ?>
            </tbody>
        </table>
	  <br><br>
	 <p> Total Orders :	
	  <?php echo $i.' , ';?>
	  Order Total :	
	  <?php echo '$'.$total;?>
	  </p>
        <div class="clearfix"></div>
    </div>
</div>
