<?php 
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url(
		'inventory-cruise-cabins-edit', array('id' => $form->get('id')->getValue())
));
$form->setAttribute('method', 'post');

if($form->get('dateFrom')->getValue() instanceof DateTime)
	$form->get('dateFrom')->setValue($form->get('dateFrom')->getValue()->format('Y-m-d')); // DateTime to str fix;
if($form->get('dateTo')->getValue() instanceof DateTime)
	$form->get('dateTo')->setValue($form->get('dateTo')->getValue()->format('Y-m-d')); // DateTime to str fix;
?>
<div class="grid">
	<div class="grid-title">
		<div class="pull-left">
			<div class="icon-title">
				<i class="icon-plus"></i>
			</div>
			<span>Edit Cruise Cabin</span>
			<div class="clearfix"></div>
		</div>
		<div class="clearfix"></div>
	</div>
	<?php echo $this->form()->openTag($form); ?>
	<div class="grid-content">
                        
            <div class="formRow control-group">
                    <?php echo $this->formLabel($form->get('cruiseId')); ?>
                    <div class="formRight">
                            <?php echo $this->formElement($form->get('cruiseId')->setAttribute('class', 'chzn-select chosen_select width-100')); ?>
                    <?php echo $this->formElementErrors($form->get('cruiseId'), array('class' => 'help-inline')); ?>
                    </div>
            </div>
            
            <div id="cabins" class="formRow control-group">
                    <?php echo $this->formLabel($form->get('suiteId')); ?>
                    <div class="formRight">
                            <?php echo $this->formElement($form->get('suiteId')->setAttribute('class', 'chzn-select chosen_select width-100')); ?>
                    <?php echo $this->formElementErrors($form->get('suiteId'), array('class' => 'help-inline')); ?>
                    </div>
            </div>         
            
             <div class="formRow control-group">
                    <?php echo $this->formLabel($form->get('deckNumber')); ?>
                    <div class="formRight">
                            <?php echo $this->formElement($form->get('deckNumber')->setAttribute('class', 'chzn-select chosen_select width-100')->setAttribute('required', 'required')); ?>
                            <?php echo $this->formElementErrors($form->get('deckNumber'), array('class' => 'help-inline')); ?>
                    </div>
             </div>
            
            <div class="formRow control-group">
                    <?php echo $this->formLabel($form->get('totalAvailable')); ?>
                    <div class="formRight">
                            <?php echo $this->formElement($form->get('totalAvailable')->setAttribute('class', 'span input')->setAttribute('required', 'required')); ?>
                    <?php echo $this->formElementErrors($form->get('totalAvailable'), array('class' => 'help-inline')); ?>
                    </div>
            </div>            
            <div class="formRow control-group">
                    <?php echo $this->formLabel($form->get('dateFrom')); ?>
                    <div class="formRight">
                            <?php echo $this->formElement($form->get('dateFrom')->setAttribute('class', 'span input')); ?>
                    <?php echo $this->formElementErrors($form->get('dateFrom'), array('class' => 'help-inline')); ?>
                    </div>
            </div>            
            <div class="formRow control-group">
                    <?php echo $this->formLabel($form->get('dateTo')); ?>
                    <div class="formRight">
                            <?php echo $this->formElement($form->get('dateTo')->setAttribute('class', 'span input')); ?>
                    <?php echo $this->formElementErrors($form->get('dateTo'), array('class' => 'help-inline')); ?>
                    </div>
            </div>            
            <div class="formRow control-group">
                    <?php echo $this->formLabel($form->get('netPrice')); ?>
                    <div class="formRight">
                            <?php echo $this->formElement($form->get('netPrice')->setAttribute('class', 'span input')); ?>
                    <?php echo $this->formElementErrors($form->get('netPrice'), array('class' => 'help-inline')); ?>
                    </div>
            </div>            
            <div class="formRow control-group">
                    <?php echo $this->formLabel($form->get('grossPrice')); ?>
                    <div class="formRight">
                            <?php echo $this->formElement($form->get('grossPrice')->setAttribute('class', 'span input')); ?>
                    <?php echo $this->formElementErrors($form->get('grossPrice'), array('class' => 'help-inline')); ?>
                    </div>
            </div>   
            <div class="formRow control-group">
                    <?php echo $this->formLabel($form->get('notes')); ?>
                    <div class="formRight">
                            <?php echo $this->formElement($form->get('notes')->setAttribute('class', 'span input same-height-1')->setAttribute('rows', '3')); ?>
                    <?php echo $this->formElementErrors($form->get('notes'), array('class' => 'help-inline')); ?>
                    </div>
            </div>
            <div class="formRow control-group">
                    <?php echo $this->formLabel($form->get('promo')); ?>
                    <div class="formRight">
                            <?php echo $this->formElement($form->get('promo')); ?>
                    <?php echo $this->formElementErrors($form->get('promo'), array('class' => 'help-inline')); ?>
                    </div>
            </div> 
            <div class="formRow control-group">
                    <?php echo $this->formSubmit( $form->get('submit')->setAttribute('class', 'btn btn-info')) ?>
                    <input id="resetbutton" class="btn btn-info" type="reset" value="Reset" name="reset"></input>
            </div>
            <div class="clearfix"></div>

	</div>
	<?php echo $this->form()->closeTag() ?>
</div>

<script>				
$(function(){
    $('.grid-content .formRow ul.help-inline').parents('.formRow').addClass('error');
    $('.error input').keyup(function(){
                            $(this).parents('.formRow').removeClass('error');
                            $(this).next('ul.help-inline').remove();
    });  
    $('#cruises').change(function(){        
        var id = $(this).val();        
        $.post('/admin/inventory/ajax/cruise/cabins/'+id, {id:id}, function(data){            
            $('#cabins').html(data);                        
        });        
    });
});				
</script>