<?php 

$form = $this->form;

$form->prepare();
$form->setAttribute('action', $this->url(
		'itineraries-edit', array('id' => $form->get('id')->getValue())
));

$form->setAttribute('method', 'post');

if($form->get('arrivalTime')->getValue() instanceof DateTime)
	$form->get('arrivalTime')->setValue($form->get('arrivalTime')->getValue()->format('H:i')); // DateTime to str fix;

if($form->get('departureTime')->getValue() instanceof DateTime)
	$form->get('departureTime')->setValue($form->get('departureTime')->getValue()->format('H:i')); // DateTime to str fix;

?>
<div class="grid">
	<div class="grid-title">
		<div class="pull-left">
			<div class="icon-title">
				<i class="icon-bookmark"></i>
			</div>
			<span>Edit Itinerary</span>
			<div class="clearfix"></div>
		</div>
		<div class="pull-right">
			<div class="icon-title">
				<a href="#"><i class="icon-refresh"></i></a>
			</div>
			<div class="icon-title">
				<a href="#"><i class="icon-user"></i></a>
			</div>
			<div class="icon-title">
				<a href="#"><i class="icon-cog"></i></a>
			</div>
		</div>
		<div class="clearfix"></div>
	</div>
	<?php echo $this->form()->openTag($form); ?>
	<?php echo $this->formElement($form->get('id')); ?>
	<div class="grid-content">
	
		<div class="formRow control-group">
			<?php echo $this->formLabel($form->get('day')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('day')->setAttribute('class', 'span input')); ?>
	        	<?php echo $this->formElementErrors($form->get('day'), array('class' => 'help-inline')); ?>
			</div>
		</div>
	
		<div class="formRow control-group">
			<?php echo $this->formLabel($form->get('portLocation')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('portLocation')->setAttribute('class', 'span input')); ?>
	        	<?php echo $this->formElementErrors($form->get('portLocation'), array('class' => 'help-inline')); ?>
			</div>
		</div>
		
		<div class="formRow control-group">
			<?php echo $this->formLabel($form->get('arrivalTime')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('arrivalTime')->setAttribute('class', 'span input same-height-1')); ?>
	        	<?php echo $this->formElementErrors($form->get('arrivalTime'), array('class' => 'help-inline')); ?>
			</div>
		</div>
				
		<div class="formRow control-group">
			<?php echo $this->formLabel($form->get('departureTime')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('departureTime')->setAttribute('class', 'span input same-height-1')); ?>
	        	<?php echo $this->formElementErrors($form->get('departureTime'), array('class' => 'help-inline')); ?>
			</div>
		</div>
		
		<div class="formRow control-group">
			<?php echo $this->formLabel($form->get('activity')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('activity')->setAttribute('class', 'span input same-height-1')); ?>
	        	<?php echo $this->formElementErrors($form->get('activity'), array('class' => 'help-inline')); ?>
			</div>
		</div>
		
		<div class="formRow control-group">
			<?php echo $this->formLabel($form->get('cruise')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('cruise')->setAttribute('class', 'chzn-select chosen_select width-100')->setAttribute('required', 'required')); ?>
	        	<?php echo $this->formElementErrors($form->get('cruise'), array('class' => 'help-inline')); ?>
			</div>
		</div>				
		
		<div class="formRow control-group">
			<?php echo $this->formSubmit( $form->get('submit')->setAttribute('class', 'btn btn-info')) ?>
		</div>
		<div class="clearfix"></div>

	</div>
	<?php echo $this->form()->closeTag() ?>
</div>

<script>

				
	$(function(){
		$('.grid-content .formRow ul.help-inline').parents('.formRow').addClass('error');
		$('.error input').keyup(function(){
					$(this).parents('.formRow').removeClass('error');
					$(this).next('ul.help-inline').remove();
		});

		
	});				
</script>




