
<div class="grid">
    <div class="grid-title">
        <div class="pull-left">
            <div class="icon-title">
                <i class="icon-edit"></i>
            </div>
            <span>Add Disclaimer</span>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="grid-content">

        <form action="" method="post">
         <div class="formRow control-group">
             <label>
                 Title : </label>
            <div class="formRight">
                <input type="text" name="title" class="span input" required>
            </div>
        </div>	
         <div class="formRow control-group">
             <label>
                 Description : </label>
            <div class="formRight">
                <textarea name="description" class="ckeditor" required>
                </textarea>
            </div>
        </div>	
     

        
        <div class="formRow control-group">
            <input type="submit" value="Submit" class="btn btn-info">
        </div>
            </form>
        <div class="clearfix"></div>

    </div>

</div>




