
<div class="grid">
    <div class="grid-title">
        <div class="pull-left">
            <div class="icon-title">
                <i class="icon-edit"></i>
            </div>
            <span>Edit Disclaimer</span>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="grid-content">

        <form action="" method="post">
         <div class="formRow control-group">
             <input type="hidden" name="id" value="<?php echo $this->data['0']->getid(); ?>">
             <label>
                 Title : </label>
            <div class="formRight">
                <input type="text" name="title" class="span input" value="<?php echo $this->data['0']->getTitle(); ?>" required>
            </div>
        </div>	
         <div class="formRow control-group">
             <label>
                 Description : </label>
            <div class="formRight">
                <textarea name="description" class="ckeditor" required><?php echo $this->data['0']->getDescription(); ?>
                </textarea>
            </div>
        </div>	
     

        
        <div class="formRow control-group">
            <input type="submit" value="Submit" class="btn btn-info">
        </div>
            </form>
        <div class="clearfix"></div>

    </div>

</div>




