
<?php if (!is_null($this->message)):
    
   // d($this->message);
    if ($this->message):
        ?>		
        <div class="alert alert-dismissable alert-<?php echo $this->message[0]['type']; ?>">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <ul>
                <li><?php echo $this->message[0]['message']; ?></li>        
            </ul>
        </div>
        <?php
    endif;
endif;
?>


<div class="grid">
    <div class="grid-title">
        <div class="pull-left">
            <div class="icon-title">
                <i class="icon-list"></i>
            </div> 
            <span>Disclaimers</span>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>


<div class="grid">  
    

    <div class="grid-content overflow">
        
            
        <div class="formRight">
            
        
        <table class="table table-bordered table-mod-2" id="datatable_7">
            <thead>
                <tr>                    
                    <th class="hidden-mobile">Title</th> 
                    <th class="hidden-mobile">Action</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->collection as $item): ?>
               
                 <tr>


                        <td class="hidden-mobile"><?php echo $item->getTitle(); ?></td>

                        <td class="hidden-mobile">
                            <a href="javascript:void(0);"  onclick="view(<?php echo $item->getId(); ?>)" title="View">
                                <img src="/images/icon/table_view.png" alt="View" height="18" width="18">
                            </a>
                            <a href="<?php echo $this->url('settings-disclaimer-edit',array('id'=>$item->getId())); ?>" title="Update">
                                <img src="/images/icon/table_edit.png" alt="Update" height="18" width="18">
                            </a>
                        </td>
                     
                    </tr>
                <?php endforeach; ?>
                 </tbody>
        </table>
        <div class="clearfix"></div>
    </div>
</div>
</div>

    <!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close">×</button>
    <h3 id="myModalLabel"></h3>
  </div>
  <div class="modal-body">
    <p></p>
  </div>
  <div class="modal-footer">
    <button class="btn close">Close</button>
  </div>
</div>

<script>
function view(id){
    $.ajax({
                async:false,    
                url: '/admin/settings/disclaimer/view/'+id,
                type: 'POST',
                data: {id:id},
                beforeSend:function(){
                   $(".modal-body").html('<center><img src="/images/ajax-loader.gif" alt="Loading..."></center>');  
                    $("#myModalLabel").html('View Disclaimer');
                    $("#myModal").css({"display": "block"});
                    $("#myModal").modal();
                },
                success: function(data){
                    $(".modal-body").html(data)  
//                  $("#myModal").modal()  
                }
            });
}

$(document).ready(function(){
    $('.close').click(function(){
        $("#itemModal").css({"display": "none"});
        $("#myModal").css({"display": "none"});
    });
});
</script>