<?php
if (!is_null($this->message)):
    if ($this->message):
        ?>		
        <div class="alert alert-dismissable alert-<?php echo $this->message[0]['type']; ?>">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <ul>
                <li><?php echo $this->message[0]['message']; ?></li>        
            </ul>
        </div>
        <?php
    endif;
endif;
?>

<div class="grid">
    <div class="grid-title">
        <div class="pull-left">
            <div class="icon-title">
                <i class="icon-list"></i>
            </div> 
            <span>Leads</span>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>




</div>
<div class="grid">    
    <div class="grid-content overflow">


        <div class="formRight">
            <form method="post" action="<?php echo $this->url('leads'); ?>">
                Date From : <input type="date" id="startDate" name="mydate" class="" value="<?php
                if (!empty($this->startdat)) {
                    echo $this->startdat;
                } else {
                    echo '';
                }
                ?>">  
                Date To : <input type="date" id="endDate" name="mydate1" class="" value="<?php
                if (!empty($this->enddat)) {
                    echo $this->enddat;
                } else {
                    echo '';
                }
                ?>">       
                <input type="submit" name="submit" class="btn btn-info" id="btnmargin" value="Search">
            </form> </div>

        <table class="table table-bordered table-mod-2" id="datatable_3">
            <thead>
                <tr>                    
                 <!--   <th class="hidden-mobile">Reservation No.</th> -->
                    <th class="hidden-mobile">Name</th>
                    <th class="hidden-mobile">Type</th>
                    <th class="hidden-mobile">Date</th>
                    <th class="hidden-mobile">From</th>
                    <th class="hidden-mobile">Status</th>
                    <th class="hidden-mobile">Action</th>
                </tr>
            </thead>
            <tbody>
                <?php
           foreach ($this->collection as $item):

                    $clientName = $item['name'];
                    $type = $item['type'];
                    $status = $item['lead']->getStatus();
                    if($status==0){
                        $statusnew="New Lead";
                    }elseif ($status==1) {
                        
                       $statusnew="Email Sent";     
                    }
                    elseif ($status==2) {
                        
                       $statusnew="Quote Sent";     
                    }
                     elseif ($status==3) {
                        
                       $statusnew="Quote Accepted";     
                    }
                    ?>                  

                    <tr>

                        <td class="hidden-mobile"><?php echo $clientName; ?></td> 
                        <td class="hidden-mobile"><?php echo $type; ?></td>
                        <?php if ($item['lead']->getCreatedAt()) { ?>
                            <td class="hidden-mobile"><?php echo $item['lead']->getCreatedAt()->format('Y-m-d'); ?></td>
                        <?php } else { ?>
                            <td class="hidden-mobile"><?php echo '-'; ?></td> 
                        <?php }  ?>
                         <?php if ($item['lead']->getAffiliateId()) { ?> 
                             <td class="hidden-mobile"><?php echo 'From Reseller Site'; ?></td> 
                             <?php } else { ?>
                        <td class="hidden-mobile"><?php echo 'From VP Site'; ?></td> 
                         <?php } ?>
                        <td class="hidden-mobile"><?php echo $statusnew; ?></td> 
                        <td class="action-table">                            
                            <a href="<?php echo $this->url('leads-view', array('id' => $item['id'])); ?>" title="View">
                                <img src="/images/icon/table_view.png" alt="View">
                            </a>
                            <a href="<?php echo $this->url('leads-sendmail', array('id' => $item['id'])); ?>" title="Send Mail" class="btn btn-success">
                                Send Mail
                            </a>
                        </td>

                    </tr>                    
                <?php endforeach; ?>
            </tbody>
        </table>

        <div class="clearfix"></div>
    </div>
</div>


