<?php
$form = $this->form;

$form->prepare();
$form->setAttribute('action', $this->url('affiliate-template-edit',array('id'=>$this->id)));

$form->setAttribute('method', 'post');
$form->setAttribute('enctype', 'multipart/form-data');

//d($form->get('id')->getValue());
?>   

<div class="grid">
    <div class="grid-title">
        <div class="pull-left">
            <div class="icon-title">
                <i class="icon-edit"></i>
            </div>
            <span>Edit Template</span>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="grid-content">

       <?php echo $this->form()->openTag($form) ?> 
         <div class="formRow control-group">
            <?php echo $this->formLabel($form->get('title')); ?>
            <div class="formRight">
                <?php echo $this->formElement($form->get('title')->setAttribute('class', 'span input')->setAttribute('required', 'required')); ?>
                <?php echo $this->formElementErrors($form->get('title'), array('class' => 'help-inline')); ?>
            </div>
        </div>	
         <div class="formRow control-group">
             <label>Template Type<font color="red">*</font></label>
            <div class="formRight">
                <input type="radio" name="type" value="1" <?php if($this->collection['type']==1){ echo "checked"; } ?>>Premium
                <input type="radio" name="type" value="2" <?php if($this->collection['type']==2){ echo "checked"; } ?>>Free
                <input type="radio" name="type" value="3" <?php if($this->collection['type']==3){ echo "checked"; } ?>>Exclusive
            </div>
        </div>	
        
        <div class="formRow control-group">
            <?php echo $this->formLabel($form->get('image')); ?>
            <div class="formRight">
                <img src="<?php echo \Base\Model\Plugins\Imagine::$imagesBaseUrl; ?>reseller_theme/<?php echo $this->collection['image']; ?>" height="100" width="100"> OR 
                <?php echo $this->formElement($form->get('image')); ?>
                <?php echo $this->formElementErrors($form->get('image'), array('class' => 'help-inline')); ?>
            </div>
        </div>
        <div class="formRow control-group" id="cost" style="display:none">
            <?php echo $this->formLabel($form->get('cost')); ?>
            <div class="formRight">
                <?php echo $this->formElement($form->get('cost')->setAttribute('class', 'span input')); ?>
                <?php echo $this->formElementErrors($form->get('cost'), array('class' => 'help-inline')); ?>
            </div>
        </div>
        <div class="formRow control-group" id="email" style="display:none">
            <?php echo $this->formLabel($form->get('email')); ?>
            <div class="formRight">
                <?php echo $this->formElement($form->get('email')->setAttribute('class', 'span input')->setAttribute('id', 'resellerEmail')); ?>
                <?php echo $this->formElementErrors($form->get('email'), array('class' => 'help-inline')); ?>
                <img src="/images/ajax-loader.gif" id="loading" style="display:none">
                
                <?php echo $this->formElement($form->get('id')->setAttribute('class', 'span input')->setAttribute('id', 'resellerId')); ?>
                <?php echo $this->formElementErrors($form->get('id'), array('class' => 'help-inline')); ?>
            </div>
        </div>

      
       

        
        <div class="formRow control-group">
            <?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-info')) ?>
        </div>

        <div class="clearfix"></div>

    </div>
    <?php echo $this->form()->closeTag() ?>
</div>

<script>


    $(function() {
        $('input[type="radio"]').click(function(){
            var value=$(this).val();
            if(value==1){
                $('#cost').show();
                $('#email').hide();
            }else if(value==3){
                $('#cost').hide();
                $('#email').show();
            }else{
                $('#cost').hide();
                $('#email').hide();
            }
        });
        
        var value=<?php echo $this->collection['type']; ?>;
            if(value==1){
                $('#cost').show();
                $('#email').hide();
            }else if(value==3){
                $('#cost').hide();
                $('#email').show();
            }else{
                $('#cost').hide();
                $('#email').hide();
            }

    });
</script>

<script>
    $(function() {

        $("#resellerEmail").autocomplete({
            select: function (event, ui) {
                    $('#resellerId').val(ui.item.key);
                },
            source: function(request, callback) {
                $("#loading").show();
                $.ajax({
                    type: "POST",
                    url: "/admin/reseller/template/ajax/getEmails",
                    dataType: "json",
                    data: {pattern: request.term},
                    success: function(data) {
                        $("#loading").hide();
                        callback($.map(data, function(obj,key) {
                            return obj;
                        }))
                    }
                });
            }
        });
       
    });
</script>

<style>
    input[type="radio"]{
         display: inline-block;
         margin: 1% 1% 1% 2%;
    }
</style>


