<?php
//echo "hello"; die;
//d($this->rooms[0]->getDescription());
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url(
                'lead-generate-quote', array('id' => $this->id)
));
$form->setAttribute('method', 'post');
//d($form->get('email')->getValue());
$data = $this->data['leads'];
//d($data);

$type = $data['typeid'];
$roomId = $data['roomid'];
//d($roomId);
//d($this->roomdetails);
if ($form->get('dateFrom')->getValue() instanceof DateTime)
    $form->get('dateFrom')->setValue($form->get('dateFrom')->getValue()->format('Y-m-d')); // DateTime to str fix;
if ($form->get('dateTo')->getValue() instanceof DateTime)
    $form->get('dateTo')->setValue($form->get('dateTo')->getValue()->format('Y-m-d'));
?>
<div class="grid">
    <div class="grid-title">
        <div class="pull-left">
            <div class="icon-title">
                <i class="icon-plus"></i>
            </div>
            <span>Send Quote</span>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
    <?php echo $this->form()->openTag($form); ?>
    <div class="grid-content">
        <div class="formRow control-group">                        
            <input type="hidden" name="id" value="<?php echo $this->id; ?>">
            <div class="formRow control-group">
                <?php echo $this->formLabel($form->get('name')); ?>
                <div class="formRight">
                    <?php echo $this->formElement($form->get('name')->setAttribute('class', 'span input')); ?>
                    <?php echo $this->formElementErrors($form->get('name'), array('class' => 'help-inline')); ?>
                </div>
            </div>


            <div class="formRow control-group">
                <?php echo $this->formLabel($form->get('email')); ?>
                <div class="formRight">
                    <?php
                    echo $this->formElement($form->get('email')
                                    ->setAttribute('id', 'email')
                                    ->setAttribute('class', 'span input'));
                    ?>
                    <?php echo $this->formElementErrors($form->get('email'), array('class' => 'help-inline')); ?>
                </div>
            </div>     

            <div class="formRow control-group">
                <?php echo $this->formLabel($form->get('phone')); ?>
                <div class="formRight">
                    <?php
                    echo $this->formElement($form->get('phone')
                                    ->setAttribute('id', 'phone')
                                    ->setAttribute('class', 'span input'));
                    ?>
                    <?php echo $this->formElementErrors($form->get('phone'), array('class' => 'help-inline')); ?>
                </div>
            </div>




            <?php
            switch ($data['lead']->getType()) {
                case 1:
                    $typeName = "Resort";
                    $description = $this->roomdetails->getDescription();
                    $roomName = $this->roomdetails->getTitle();
                    break;
                case 2:
                    $typeName = "Event";
                    $description = $this->roomdetails->getRoomId()->getDescription();
                    $roomName = $this->roomdetails->getRoomCategory();
                    break;
                case 3:
                    $typeName = "Cruise";
                    $description = $this->roomdetails->getDescription();
                    $roomName = $this->roomdetails->getDeckName();
                    break;
            }
            ?>
            <div class="formRow control-group">			
                <label for="reservationType" class="">Reservation Type</label>
                <div class="formRight">
                    <div name="reservationType" class="distance distance-2">
                        <label for="reservationType1" class=""><?php echo $typeName; ?></label>
                        <input type="hidden" name="type" value="<?php echo $data['lead']->getType(); ?>"/>
                    </div>
                </div>
            </div>
            <div class="formRow control-group">
                <label class="" for="typeName"><?php echo $typeName; ?></label>
                <div class="formRight">
                    <?php echo $data['hotelName']; ?>
                </div>

            </div>




            <div class="formRow control-group">
                <?php echo $this->formLabel($form->get('dateFrom')); ?>
                <div class="formRight">
                    <?php
                    echo $this->formElement($form->get('dateFrom')
                                    ->setAttribute('id', 'dateFrom')
                                    ->setAttribute('class', 'span input'));
                    ?>
                    <?php echo $this->formElementErrors($form->get('dateFrom'), array('class' => 'help-inline')); ?>
                </div>
            </div>
            <div class="formRow control-group">
                <?php echo $this->formLabel($form->get('dateTo')); ?>
                <div class="formRight">
                    <?php
                    echo $this->formElement($form->get('dateTo')
                                    ->setAttribute('id', 'dateTo')
                                    ->setAttribute('class', 'span input'));
                    ?>
                    <?php echo $this->formElementErrors($form->get('dateTo'), array('class' => 'help-inline')); ?>
                </div>
            </div>

            <?php
            if ($type == 1) {
                $dataExtraType = 4;
                ?>
                <input type="hidden" name="roomCategory[]" value="<?php echo $data['Typename']; ?>">


                <?
            } else if ($type == 2) {


                $dataExtraType = 6;
                // echo   $data['Typename'];die; 
                ?>

                <input type="hidden" name="roomCategory[]" value="<?php echo $data['Typename']; ?>">
                <?php
            } else {

                $dataExtraType = 7;
                ?>

                <input type="hidden" name="suiteName[]" value="<?php echo $data['Typename']; ?>">
            <?php } ?>



            <input type="hidden" name="dataExtraType" id="data-extra-type" value="<?php echo $dataExtraType; ?>">
            <input type="hidden" name="dataTypeId" id="data-type-id" value="<?php echo $data['TypeName']; ?>">

            <div id="ajax-what" class="formRow control-group">



                <label for="roomCategory">Room Category</label>                    
                <div class="formRight">    
                    <?php echo $roomName; ?>
                </div>





            </div>


            <div class="formRow control-group">
                <?php echo $this->formLabel($form->get('description[]')); ?>
                <div class="formRight">
                    <?php
                    echo $this->formElement($form->get('description[]')
                                    ->setAttribute('id', 'description')
                                    ->setAttribute('class', 'ckeditor')
                                    ->setAttribute('value', $description));
                    ?>
                    <?php echo $this->formElementErrors($form->get('description[]'), array('class' => 'help-inline')); ?>
                </div>
            </div>





            <div class="formRow control-group">
                <?php echo $this->formLabel($form->get('cost[]')); ?>
                <div class="formRight">
                    <?php
                    echo $this->formElement($form->get('cost[]')
                                    ->setAttribute('id', 'cost[]')
                                    ->setAttribute('class', 'span input'));
                    ?>
                    <?php echo $this->formElementErrors($form->get('cost[]'), array('class' => 'help-inline')); ?>
                </div>
            </div>


            <div class="formRight">
                <div class="distance distance-2">
                    <p>
                        <input type="radio" name="paymentType[]" id="per-person" value="1" checked="checked">
                        <label for="per-person"><span></span>Per Person</label>
                    </p>
                    <p id="deposit-hide">
                        <input type="radio" name="paymentType[]" id="per-room" value="0"  <?php //if(!$form->get('paymentType')->getValue()) echo 'checked="checked"';       ?>>
                        <label for="per-room; ?>"><span></span>Per Room</label>
                    </p>
                </div>
            </div>
            <div class="formRow control-group">
                <div class="formLeft">
                    <a href="javascript:void(0)" id="add-rooms">Add Rooms</a>
                </div>
            </div>
            <style>
                #inventory_room_available{color:green;}
            </style>


            <div id="ajax-what_1" class="formRow control-group"></div>


            <input type="hidden" id="today" value="<?php echo date('Y-m-d'); ?>">

            <input type="hidden" id="savesend">




            <div class="formRow control-group">
                <?php echo $this->formLabel($form->get('AccomodationDetails')); ?>
                <div class="formRight">
                    <?php
                    echo $this->formElement($form->get('AccomodationDetails')
                                    ->setAttribute('id', 'AccomodationDetails')
                                    ->setAttribute('class', 'ckeditor'));
                    ?>
                    <?php echo $this->formElementErrors($form->get('AccomodationDetails'), array('class' => 'help-inline')); ?>
                </div>
            </div>    






            <div id="ajax-items" class="formRow control-group"></div>
            <div id="ajax-excursion" class="formRow control-group"></div>
            <div id="ajax-transfer" class="formRow control-group"></div>


            <div class="formRow control-group">
                <?php echo $this->formLabel($form->get('note')); ?>
                <div class="formRight">
                    <?php
                    echo $this->formElement($form->get('note')
                                    ->setAttribute('id', 'note')
                                    ->setAttribute('class', 'ckeditor'));
                    ?>
                    <?php echo $this->formElementErrors($form->get('note'), array('class' => 'help-inline')); ?>
                </div>
            </div>           


            <div class="formRow control-group">

                <!-- <button id="creat" class="btn btn-success" type="submit"  name="submit" onclick=''>Save</button>!-->
                <button id="creat1" class="btn btn-success" type="submit"  name="submit" onclick="" value="1">Send</button>

            </div>


            <div id="ajax-script"></div>
            <div class="clearfix"></div>

        </div>
        <?php echo $this->form()->closeTag() ?>
    </div>
</div>

<?php //echo $this->partial('orders/ajax/modal.phtml');        ?>
<script src="/js/date-formater.js"></script>
<script src="/js/leadsedit.js"></script>
<script>
    LeadsEdit.init();
    $(function() {
        $('.grid-content .formRow ul.help-inline').parents('.formRow').addClass('error');
        $('.error input').keyup(function() {
            $(this).parents('.formRow').removeClass('error');
            $(this).next('ul.help-inline').remove();
        });

        //   var _getExtraItems = function(typeCode, id) {

        //     $.post('/admin/orders/ajax/items', {typeCode: 4, id: id}, function(data) {
        //       $('#ajax-items').html(data);

        // });
        // }



        // var selected = $('select[name="dancerCountry"]').val() ;
        // var selected = $('# resort-rooms').find('option:selected');
        // var description = selected.data('description');
        // alert(description);
        //  $("textarea#description").val("<?php //echo $this->roomdetails->getDescription();         ?>"); 


        $('#add-rooms').click(function() {

            var clickCount = jQuery.data(this, 'clickCount');
            if (!clickCount) {
                clickCount = 0
            }
            clickCount++;
            jQuery.data(this, 'clickCount', clickCount);
            var id =<?php echo $data['Typename']; ?>;
            var type =<?php echo $type; ?>;
            //  var resource ='resort/rooms/';

            $.post('/admin/leads/ajaxroomdetails/', {id: id, type: type, count: clickCount}, function(data) {

                if (clickCount == 1) {
                    $('#ajax-what_1').attr('id', 'it_');
                    var appendDiv = $('#it_' + clickCount).html(data);
                    // console.log(appendDiv);
                    $("#it_").append(data);
                    //  $(appendDiv).insertAfter('#it_');
                } else {
                    // alert(clickCount-1);
                    // var appendDiv = $('#it_'+clickCount).html('hello');
                    //  $('#it_').attr('id', 'it_'); 
                    $("#it_").append(data);
                    $('.chzn-select').chosen();
                }
                // $('#it_'+clickCount).html(data);
                $('.chzn-select').chosen();

            });
<?php //echo $this->partial('partial/leads_form/notes_part');         ?>


            //alert(clickCount);
        });

    });



</script>


<script>
    $(function() {

        $("#resort-rooms").on('change', function() {
            //      alert(this.id);
            var id = $(this).val();
            var resource = $(this).attr('data-resource');
            var type = $(this).attr('data-type');
            var selected = $(this).find('option:selected');
            var description = selected.data('description');
            //  alert(description);
            $("textarea#description").val(description);
//            alert(description);
            //   console.log(description);

            /*   if (id) {
             $.post('/admin/leads/ajaxroomdetails/', {id: id, type: type}, function(data) {
             
             //console.log(data);
             
             $('#ajax-what_1').html(data);
             // $('.ckeditor').ckeditor();
             });
             
             } else {
             _clearAll();
             }*/

            //   alert('here');          //  var transfersCost = 0;
            /* if ($('#' + this.id).is(":checked")) {
             
             //     alert(this.id);
             var appendDiv = $('#show-transfers').html();
             
             var transferamount = parseFloat($(this).attr('grossPrice'));
             var transfername = $(this).attr('transfername');
             
             // alert(transfername);
             // alert(transferamount);
             
             $(appendDiv).insertAfter("#insurance");
             
             $('#transfer_').attr('id', 'transfer_' + this.id);
             $('#transfersrate').html("<?php //echo $symbol;            ?>" + transferamount);
             $('#transfersname').html(transfername);
             $('#transfersrate').attr('id', this.id);
             }
             else if ($('#' + this.id).is(":unchecked")) {
             $("#transfer_" + this.id).remove();
             }*/

        });
        $('savesend').click(function() {

            alert('hello');
        });

    });


</script>


<script>
// Make sure the DOM elements are loaded and accounted for


    $(document).ready(function() {
        $('a[data-toggle="modal-preview"]').click(function() {
            var remote_content = $(this).attr('href');
            //console.log(remote_content);            
            var modal = $('.bs-example-modal-lg');
            var modalBody = $('.bs-example-modal-lg .modal-body');
            var data = $("#orders").serialize();

            $.post(remote_content, {data: data}, function(data) {
                modalBody.html(data);
                modal.modal();
            });

            return false;
        });
    });

</script>



