<?php
$form = $this->form;

$form->prepare();
$form->setAttribute('action', $this->url(
                'inventory-event-rooms-add'
));

$form->setAttribute('method', 'post');
?>
<div class="grid">
    <div class="grid-title">
        <div class="pull-left">
            <div class="icon-title">
                <i class="icon-plus"></i>
            </div>
            <span>Add New Event Room<?php //echo $config->configuraion['basePath'];?></span>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
    <?php echo $this->form()->openTag($form); ?>
    <div class="grid-content">
        
<!--        <div class="formRow control-group">
                    <?php //echo $this->formLabel($form->get('name')); ?>
                    <div class="formRight">
                            <?php //echo $this->formElement($form->get('name')->setAttribute('class', 'span input')); ?>
                    <?php //echo $this->formElementErrors($form->get('name'), array('class' => 'help-inline')); ?>
                    </div>
            </div>-->
        
        <div class="formRow control-group">
            <?php echo $this->formLabel($form->get('eventId')); ?>
            <div class="formRight">
                <?php echo $this->formElement($form->get('eventId')->setAttribute('class', 'chzn-select chosen_select width-100')); ?>
                <?php echo $this->formElementErrors($form->get('eventId'), array('class' => 'help-inline')); ?>
            </div>
        </div>

        <div id="rooms" class="formRow control-group">                
            <?php echo $this->formElementErrors($form->get('roomId'), array('class' => 'help-inline')); ?>
        </div>

        <div class="formRow control-group">
            <?php echo $this->formLabel($form->get('totalAvailable')); ?>
            <div class="formRight">
                <?php echo $this->formElement($form->get('totalAvailable')->setAttribute('class', 'span input')->setAttribute('required', 'required')); ?>
                <?php echo $this->formElementErrors($form->get('totalAvailable'), array('class' => 'help-inline')); ?>
            </div>
        </div>            
        <div class="formRow control-group">
            <?php echo $this->formLabel($form->get('dateFrom')); ?>
            <div class="formRight">
                <?php echo $this->formElement($form->get('dateFrom')->setAttribute('class', 'span input')); ?>
                <?php echo $this->formElementErrors($form->get('dateFrom'), array('class' => 'help-inline')); ?>
            </div>
        </div>            
        <div class="formRow control-group">
            <?php echo $this->formLabel($form->get('dateTo')); ?>
            <div class="formRight">
                <?php echo $this->formElement($form->get('dateTo')->setAttribute('class', 'span input')); ?>
                <?php echo $this->formElementErrors($form->get('dateTo'), array('class' => 'help-inline')); ?>
            </div>
        </div> 

<!--        <div class="formRow control-group">
            <?php //echo $this->formLabel($form->get('pricePer')); ?>
            <div class="formRight toa">
                <?php //echo $this->formElement($form->get('pricePer')->setAttribute('class', 'span input')); ?>
                <?php //echo $this->formElementErrors($form->get('pricePer'), array('class' => 'help-inline')); ?>
            </div>
        </div> 

        <div class="formRow control-group">
            <?php //echo $this->formLabel($form->get('tripleOccupancyAllowed')); ?>
            <div class="formRight toa">
                <?php //echo $this->formElement($form->get('tripleOccupancyAllowed')->setAttribute('class', 'span input')); ?>
                <?php //echo $this->formElementErrors($form->get('tripleOccupancyAllowed'), array('class' => 'help-inline')); ?>
            </div>
        </div>-->
        
        <div class="formRow control-group">			
                <label for="board">Board</label>
                <div class="formRight">
                    <div name="board" class="distance distance-2">
                        <p>
                            <input type="radio" id="all-inclusive" class="load-entity" name="board" checked="checked" value="1" data-resource="all-inclusive">
                            <label for="all-inclusive"><span></span>All Inclusive</label>
                        </p>
                        <p>
                            <input type="radio" id="breakfast-included" class="load-entity" name="board" value="2" data-resource="breakfast-included">
                            <label for="breakfast-included"><span></span>Breakfast Included</label>
                        </p>
                         <p>
                            <input type="radio" id="room-only" class="load-entity" name="board" value="3" data-resource="room-only">
                            <label for="room-only"><span></span>Room Only</label>
                        </p>
                    </div>
                </div>
            </div>

            <div class="formRow control-group">
                <?php echo $this->formLabel($form->get('netPrice')); ?>
                <div class="formRight">
                    <?php echo $this->formElement($form->get('netPrice')->setAttribute('class', 'span input')); ?>
                    <?php echo $this->formElementErrors($form->get('netPrice'), array('class' => 'help-inline')); ?>
                </div>
            </div>            
            <div class="formRow control-group">
                <?php echo $this->formLabel($form->get('grossPrice')); ?>
                <div class="formRight">
                    <?php echo $this->formElement($form->get('grossPrice')->setAttribute('class', 'span input')); ?>
                    <?php echo $this->formElementErrors($form->get('grossPrice'), array('class' => 'help-inline')); ?>
                </div>
            </div>

            <div class="formRow control-group">			
                <label for="pricePer">Price Per</label>
                <div class="formRight">
                    <div name="pricePer" class="distance distance-2">
                        <p>
                            <input type="radio" id="person" class="load-entity" name="pricePer" checked="checked" value="1" data-resource="person">
                            <label for="person"><span></span>Person</label>
                        </p>
                        <p>
                            <input type="radio" id="room" class="load-entity" name="pricePer" value="2" data-resource="room">
                            <label for="room"><span></span>Room</label>
                        </p>
                    </div>
                </div>
            </div>

            <div class="formRow control-group">			
                <label for="doubleOccupancy"> Double Occupancy Rate</label>
                <div class="formRight">
                    <div name="double-occupancy-rate" class="distance distance-2">
                        <p>
                            <input type="radio" id="double-yes" class="load-entity" name="doubleOccupancyRate"  value="1" data-resource="double-yes">
                            <label for="double-yes"><span></span>Yes</label>
                        </p>
                        <p>
                            <input type="radio" id="double-no" class="load-entity" name="doubleOccupancyRate" checked="checked" value="0" data-resource="double-no">
                            <label for="double-no"><span></span>No</label>
                        </p>
                    </div>
                </div>
            </div>

             <div class="formRow control-group">
                <?php echo $this->formLabel($form->get('femalesCount')); ?>
                <div class="formRight">
                    <?php echo $this->formElement($form->get('femalesCount')->setAttribute('class', 'span input')); ?>
                    <?php echo $this->formElementErrors($form->get('femalesCount'), array('class' => 'help-inline')); ?>
                </div>
            </div>

            <div class="formRow control-group">
                <?php echo $this->formLabel($form->get('malesCount')); ?>
                <div class="formRight">
                    <?php echo $this->formElement($form->get('malesCount')->setAttribute('class', 'span input')); ?>
                    <?php echo $this->formElementErrors($form->get('malesCount'), array('class' => 'help-inline')); ?>
                </div>
            </div>


            <div class="formRow control-group">			
                <label for="tripleOccupancyAllowed">Does this room allows triple Occupancy</label>
                <div class="formRight">
                    <div name="pricePer" class="distance distance-2">
                        <p>
                            <input type="radio" id="yes" class="load-entity" name="tripleOccupancyAllowed"  value="1" data-resource="yes">
                            <label for="yes"><span></span>Yes</label>
                        </p>
                        <p>
                            <input type="radio" id="no" class="load-entity" name="tripleOccupancyAllowed" checked="checked" value="0" data-resource="no">
                            <label for="no"><span></span>No</label>
                        </p>
                    </div>
                </div>
            </div>
            
             <div id="triple_event">
            <div class="formRow control-group">
                <?php echo $this->formLabel($form->get('triplePriceFemaleGross')); ?>
                <div class="formRight">
                    <?php echo $this->formElement($form->get('triplePriceFemaleNet')->setAttribute('class', 'span')); ?>
                    <?php echo $this->formElement($form->get('triplePriceFemaleGross')->setAttribute('class', 'span')); ?>
                    <?php echo $this->formElementErrors($form->get('triplePriceFemaleNet'), array('class' => 'help-inline')); ?>
                    <?php echo $this->formElementErrors($form->get('triplePriceFemaleGross'), array('class' => 'help-inline')); ?>
                </div>
            </div>      

            <div class="formRow control-group">
                <?php echo $this->formLabel($form->get('triplePriceMaleGross')); ?>
                <div class="formRight">
                    <?php echo $this->formElement($form->get('triplePriceMaleNet')->setAttribute('class', 'span')); ?>
                    <?php echo $this->formElement($form->get('triplePriceMaleGross')->setAttribute('class', 'span')); ?>
                    <?php echo $this->formElementErrors($form->get('triplePriceMaleNet'), array('class' => 'help-inline')); ?>
                    <?php echo $this->formElementErrors($form->get('triplePriceMaleGross'), array('class' => 'help-inline')); ?>
                </div>
            </div>
             </div>

            
             <div class="formRow control-group">			
                <label for="quadOccupancy">Does this room allow Quad Occupancy</label>
                <div class="formRight">
                    <div name="quadOccupancy" class="distance distance-2">
                        <p>
                            <input type="radio" id="quad-yes" class="load-entity" name="quadOccupancy"  value="1" data-resource="quad-yes">
                            <label for="quad-yes"><span></span>Yes</label>
                        </p>
                        <p>
                            <input type="radio" id="quad-no" class="load-entity" name="quadOccupancy" checked="checked" value="0" data-resource="quad-no">
                            <label for="quad-no"><span></span>No</label>
                        </p>
                    </div>
                </div>
            </div>

            <div id="quad">
        <div class="formRow control-group">
                <?php echo $this->formLabel($form->get('quadPriceFemaleGross')); ?>
                <div class="formRight">
                    <?php echo $this->formElement($form->get('quadPriceFemaleNet')->setAttribute('class', 'span')
                                                                                    ->setAttribute('id','quad-price-female-net')); ?>
                    <?php echo $this->formElement($form->get('quadPriceFemaleGross')->setAttribute('class', 'span')
                                                                                      ->setAttribute('id','quad-price-female-gross')); ?>
                    <?php echo $this->formElementErrors($form->get('quadPriceFemaleNet'), array('class' => 'help-inline')); ?>
                    <?php echo $this->formElementErrors($form->get('quadPriceFemaleGross'), array('class' => 'help-inline')); ?>
                </div>
            </div>      

            <div class="formRow control-group">
                <?php echo $this->formLabel($form->get('quadPriceMaleGross')); ?>
                <div class="formRight">
                    <?php echo $this->formElement($form->get('quadPriceMaleNet')->setAttribute('class', 'span') 
                                                                                   ->setAttribute('id','quad-price-male-net')); ?>
                    <?php echo $this->formElement($form->get('quadPriceMaleGross')->setAttribute('class', 'span') 
                                                                                    ->setAttribute('id','quad-price-male-gross')); ?>
                    <?php echo $this->formElementErrors($form->get('quadPriceMaleNet'), array('class' => 'help-inline')); ?>
                    <?php echo $this->formElementErrors($form->get('quadPriceMaleGross'), array('class' => 'help-inline')); ?>
                </div>
            </div>
        </div>

             <div class="formRow control-group">			
                <label for="singlePremiumOccupancy">Is there a Premium  for single Occupancy</label>
                <div class="formRight">
                    <div name="singlePremiumOccupancy" class="distance distance-2">
                        <p>
                            <input type="radio" id="single-yes" class="load-entity" name="singlePremiumOccupancy"  value="1" data-resource="single-yes">
                            <label for="single-yes"><span></span>Yes</label>
                        </p>
                        <p>
                            <input type="radio" id="single-no" class="load-entity" name="singlePremiumOccupancy" checked="checked" value="0" data-resource="single-no">
                            <label for="single-no"><span></span>No</label>
                        </p>
                    </div>
                </div>
            </div>

            <div id="single-price">
            <div class="formRow control-group">
                <?php echo $this->formLabel($form->get('singlePriceNet')); ?>
                <div class="formRight">
                    <?php echo $this->formElement($form->get('singlePriceNet')->setAttribute('class', 'span input')
                                                                                ->setAttribute('id','singlePriceNet')); ?>
                    <?php echo $this->formElementErrors($form->get('singlePriceNet'), array('class' => 'help-inline')); ?>
                </div>
            </div>      

            <div class="formRow control-group">
                <?php echo $this->formLabel($form->get('singlePriceGross')); ?>
                <div class="formRight">
                    <?php echo $this->formElement($form->get('singlePriceGross')->setAttribute('class', 'span input')
                                                                                ->setAttribute('id','singlePriceGross')); ?>
                    <?php echo $this->formElementErrors($form->get('singlePriceGross'), array('class' => 'help-inline')); ?>
                </div>
            </div>
        </div>

            <div class="formRow control-group">			
                <label for="singleShare">Allow single to Share</label>
                <div class="formRight">
                    <div name="singleShare" class="distance distance-2">
                        <p>
                            <input type="radio" id="single-share-yes" class="load-entity" name="singleShare"  value="1" data-resource="single-share-yes">
                            <label for="single-share-yes"><span></span>Yes</label>
                        </p>
                        <p>
                            <input type="radio" id="single-share-no" class="load-entity" name="singleShare" checked="checked" value="0" data-resource="single-share-no">
                            <label for="single-share-no"><span></span>No</label>
                        </p>
                    </div>
                </div>
            </div>
        
        <div class="formRow control-group">
            <?php echo $this->formLabel($form->get('promo')); ?>
            <div class="formRight">
                <?php echo $this->formElement($form->get('promo')); ?>
                <?php echo $this->formElementErrors($form->get('promo'), array('class' => 'help-inline')); ?>
            </div>
        </div> 
        <div class="formRow control-group">
            <?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-info')) ?>
            <input id="resetbutton" class="btn btn-info" type="reset" value="Reset" name="reset"></input>
        </div>
        <div class="clearfix"></div>

    </div>
    <?php echo $this->form()->closeTag() ?>
</div>

<script>
    $(function() {
        $('.grid-content .formRow ul.help-inline').parents('.formRow').addClass('error');
        $('.error input').keyup(function() {
            $(this).parents('.formRow').removeClass('error');
            $(this).next('ul.help-inline').remove();
        });

        $("#triple_event").css("display", "none");
        $("#single-price").css("display", "none");
        $("#quad").css("display", "none");
    });
    $('#events').change(function() {
        var id = $(this).val();
        $.post('/admin/inventory/ajax/event/rooms/' + id, {id: id}, function(data) {
            $('#rooms').html(data);
            dateValid();

        });
    });

    $("input:radio[name=tripleOccupancyAllowed]").click(function() {
        var value = $(this).val();
        if (value == 1) {
            $("#triple_event").css("display", "block");
        } else {
            $("#triple_event").css("display", "none");
        }
    });
    
    $("input:radio[name=singlePremiumOccupancy]").click(function() {
        var value = $(this).val();
        if (value == 1) {
            $("#single-price").css("display", "block");
        } else {
            $("#single-price").css("display", "none");
            //remove all values if tripleOccupancyAllowed = No
            $("#singlePriceNet").val('');
            $("#singlePriceGross").val('');
        }
    });
    
    $("input:radio[name=quadOccupancy]").click(function() {
        var value = $(this).val();
        if (value == 1) {
            $("#quad").css("display", "block");
        } else {
            $("#quad").css("display", "none");
            //remove all values if tripleOccupancyAllowed = No
            $("#quad-price-female-net").val('');
            $("#quad-price-male-net").val('');
            $("#quad-price-female-gross").val('');
            $("#quad-price-male-gross").val('');
            
        }
    });
    
//    function dateValid(){
//        var start = $("#hid-start").val();
//        var end = $("#hid-end").val();
//        
//        $('input[name="dateFrom"]').val(start);
//        $('input[name="dateTo"]').val(end);
//
//       $('input[name="dateFrom"]').Zebra_DatePicker({
//              direction: [start.toString(),end.toString()],
//        })
//              $('input[name="dateTo"]').Zebra_DatePicker({
//              direction: [start.toString(),end.toString()],
//        })
//
//    }
    
    function dateValid(){
        var start = $("#hid-start").val();
        var end = $("#hid-end").val();
        
        $('input[name="dateFrom"]').val(start);
        $('input[name="dateTo"]').val(end);
        
        var from = start.split("-");
        var to =  end.split("-");
        var oneDay = 24*60*60*1000;
        
        var minNextDate = new Date(parseInt(from[0]), parseInt(from[1])-1, parseInt(from[2]));
        minNextDate = new Date(minNextDate.getTime() - (5 * oneDay));
        
        var day = (minNextDate.getDate().toString().length) < 2 ? ('0' + minNextDate.getDate()) : minNextDate.getDate();
        var month = ((minNextDate.getMonth() + 1).toString().length) < 2 ? ('0' + (minNextDate.getMonth() + 1)) : minNextDate.getMonth() + 1;
        
        minNextDate = minNextDate.getFullYear()+'-'+month+'-'+day;
        //alert(minNextDate);
        
        var maxNextDate = new Date(parseInt(to[0]), parseInt(to[1])-1, parseInt(to[2]));
        maxNextDate = new Date(maxNextDate.getTime() + (5 * oneDay));
        
        var day = (maxNextDate.getDate().toString().length) < 2 ? ('0' + maxNextDate.getDate()) : maxNextDate.getDate();
        var month = ((maxNextDate.getMonth() + 1).toString().length) < 2 ? ('0' + (maxNextDate.getMonth() + 1)) : maxNextDate.getMonth() + 1;
        
        maxNextDate = maxNextDate.getFullYear()+'-'+month+'-'+day;


       $('input[name="dateFrom"]').Zebra_DatePicker({
              direction: [minNextDate.toString(),maxNextDate.toString()],
        })
              $('input[name="dateTo"]').Zebra_DatePicker({
              direction: [minNextDate.toString(),maxNextDate.toString()],
        })

    }
    
</script>

<style>
    .toa label{margin-right: 50px !important;margin-top: -10px !important;}
</style>




