<?php 

$form = $this->form;

$form->prepare();
$form->setAttribute('action', $this->url(
		'inventory-event-rooms-add'
));

$form->setAttribute('method', 'post');


?>
<div class="grid">
	<div class="grid-title">
		<div class="pull-left">
			<div class="icon-title">
				<i class="icon-plus"></i>
			</div>
			<span>Add New Resort Room</span>
			<div class="clearfix"></div>
		</div>
		<div class="clearfix"></div>
	</div>
	<?php echo $this->form()->openTag($form); ?>
	<div class="grid-content">
                        
            <div class="formRow control-group">
                    <?php echo $this->formLabel($form->get('eventId')); ?>
                    <div class="formRight">
                            <?php echo $this->formElement($form->get('eventId')->setAttribute('class', 'chzn-select chosen_select width-100')); ?>
                    <?php echo $this->formElementErrors($form->get('eventId'), array('class' => 'help-inline')); ?>
                    </div>
            </div>
                        
            <div id="rooms" class="formRow control-group">                
                <?php echo $this->formElementErrors($form->get('roomId'), array('class' => 'help-inline')); ?>
            </div>
                                  
            <div class="formRow control-group">
                    <?php echo $this->formLabel($form->get('totalAvailable')); ?>
                    <div class="formRight">
                            <?php echo $this->formElement($form->get('totalAvailable')->setAttribute('class', 'span input')->setAttribute('required', 'required')); ?>
                    <?php echo $this->formElementErrors($form->get('totalAvailable'), array('class' => 'help-inline')); ?>
                    </div>
            </div>            
            <div class="formRow control-group">
                    <?php echo $this->formLabel($form->get('dateFrom')); ?>
                    <div class="formRight">
                            <?php echo $this->formElement($form->get('dateFrom')->setAttribute('class', 'span input')); ?>
                    <?php echo $this->formElementErrors($form->get('dateFrom'), array('class' => 'help-inline')); ?>
                    </div>
            </div>            
            <div class="formRow control-group">
                    <?php echo $this->formLabel($form->get('dateTo')); ?>
                    <div class="formRight">
                            <?php echo $this->formElement($form->get('dateTo')->setAttribute('class', 'span input')); ?>
                    <?php echo $this->formElementErrors($form->get('dateTo'), array('class' => 'help-inline')); ?>
                    </div>
            </div>            
            <div class="formRow control-group">
                    <?php echo $this->formLabel($form->get('netPrice')); ?>
                    <div class="formRight">
                            <?php echo $this->formElement($form->get('netPrice')->setAttribute('class', 'span input')); ?>
                    <?php echo $this->formElementErrors($form->get('netPrice'), array('class' => 'help-inline')); ?>
                    </div>
            </div>            
            <div class="formRow control-group">
                    <?php echo $this->formLabel($form->get('grossPrice')); ?>
                    <div class="formRight">
                            <?php echo $this->formElement($form->get('grossPrice')->setAttribute('class', 'span input')); ?>
                    <?php echo $this->formElementErrors($form->get('grossPrice'), array('class' => 'help-inline')); ?>
                    </div>
            </div>
            <div class="formRow control-group">
                    <?php echo $this->formLabel($form->get('promo')); ?>
                    <div class="formRight">
                            <?php echo $this->formElement($form->get('promo')); ?>
                    <?php echo $this->formElementErrors($form->get('promo'), array('class' => 'help-inline')); ?>
                    </div>
            </div> 
            <div class="formRow control-group">
                    <?php echo $this->formSubmit( $form->get('submit')->setAttribute('class', 'btn btn-info')) ?>
                    <input id="resetbutton" class="btn btn-info" type="reset" value="Reset" name="reset"></input>
            </div>
            <div class="clearfix"></div>

	</div>
	<?php echo $this->form()->closeTag() ?>
</div>

<script>				
$(function(){
            $('.grid-content .formRow ul.help-inline').parents('.formRow').addClass('error');
            $('.error input').keyup(function(){
                                    $(this).parents('.formRow').removeClass('error');
                                    $(this).next('ul.help-inline').remove();
            });


    });
    $('#events').change(function(){        
        var id = $(this).val();        
        $.post('/admin/inventory/ajax/event/rooms/'+id, {id:id}, function(data){            
            $('#rooms').html(data); 
            
    });         
});
</script>



