<?php
$form = $this->form;

$form->prepare();
$form->setAttribute('action', $this->url(
                'inventory-event-rooms-add'
));

$form->setAttribute('method', 'post');
?>
<div class="grid">
    <div class="grid-title">
        <div class="pull-left">
            <div class="icon-title">
                <i class="icon-plus"></i>
            </div>
            <span>Add New Event Room</span>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
    <?php echo $this->form()->openTag($form); ?>
    <div class="grid-content">
        
<!--        <div class="formRow control-group">
                    <?php //echo $this->formLabel($form->get('name')); ?>
                    <div class="formRight">
                            <?php //echo $this->formElement($form->get('name')->setAttribute('class', 'span input')); ?>
                    <?php //echo $this->formElementErrors($form->get('name'), array('class' => 'help-inline')); ?>
                    </div>
            </div>-->
        
        <div class="formRow control-group">
            <?php echo $this->formLabel($form->get('eventId')); ?>
            <div class="formRight">
                <?php echo $this->formElement($form->get('eventId')->setAttribute('class', 'chzn-select chosen_select width-100')); ?>
                <?php echo $this->formElementErrors($form->get('eventId'), array('class' => 'help-inline')); ?>
            </div>
        </div>

        <div id="rooms" class="formRow control-group">                
            <?php echo $this->formElementErrors($form->get('roomId'), array('class' => 'help-inline')); ?>
        </div>

        <div class="formRow control-group">
            <?php echo $this->formLabel($form->get('totalAvailable')); ?>
            <div class="formRight">
                <?php echo $this->formElement($form->get('totalAvailable')->setAttribute('class', 'span input')->setAttribute('required', 'required')); ?>
                <?php echo $this->formElementErrors($form->get('totalAvailable'), array('class' => 'help-inline')); ?>
            </div>
        </div>            
        <div class="formRow control-group">
            <?php echo $this->formLabel($form->get('dateFrom')); ?>
            <div class="formRight">
                <?php echo $this->formElement($form->get('dateFrom')->setAttribute('class', 'span input')); ?>
                <?php echo $this->formElementErrors($form->get('dateFrom'), array('class' => 'help-inline')); ?>
            </div>
        </div>            
        <div class="formRow control-group">
            <?php echo $this->formLabel($form->get('dateTo')); ?>
            <div class="formRight">
                <?php echo $this->formElement($form->get('dateTo')->setAttribute('class', 'span input')); ?>
                <?php echo $this->formElementErrors($form->get('dateTo'), array('class' => 'help-inline')); ?>
            </div>
        </div> 

<!--        <div class="formRow control-group">
            <?php //echo $this->formLabel($form->get('pricePer')); ?>
            <div class="formRight toa">
                <?php //echo $this->formElement($form->get('pricePer')->setAttribute('class', 'span input')); ?>
                <?php //echo $this->formElementErrors($form->get('pricePer'), array('class' => 'help-inline')); ?>
            </div>
        </div> 

        <div class="formRow control-group">
            <?php //echo $this->formLabel($form->get('tripleOccupancyAllowed')); ?>
            <div class="formRight toa">
                <?php //echo $this->formElement($form->get('tripleOccupancyAllowed')->setAttribute('class', 'span input')); ?>
                <?php //echo $this->formElementErrors($form->get('tripleOccupancyAllowed'), array('class' => 'help-inline')); ?>
            </div>
        </div>-->
        

            <div class="formRow control-group">			
                <label for="pricePer">Price Per</label>
                <div class="formRight">
                    <div name="pricePer" class="distance distance-2">
                        <p>
                            <input type="radio" id="person" class="load-entity" name="pricePer" checked="checked" value="1" data-resource="person">
                            <label for="person"><span></span>Person</label>
                        </p>
                        <p>
                            <input type="radio" id="room" class="load-entity" name="pricePer" value="2" data-resource="room">
                            <label for="room"><span></span>Room</label>
                        </p>
                    </div>
                </div>
            </div>

            <div class="formRow control-group">			
                <label for="tripleOccupancyAllowed"> Triple Occupancy Allowed</label>
                <div class="formRight">
                    <div name="pricePer" class="distance distance-2">
                        <p>
                            <input type="radio" id="yes" class="load-entity" name="tripleOccupancyAllowed"  value="1" data-resource="yes">
                            <label for="yes"><span></span>Yes</label>
                        </p>
                        <p>
                            <input type="radio" id="no" class="load-entity" name="tripleOccupancyAllowed" checked="checked" value="0" data-resource="no">
                            <label for="no"><span></span>No</label>
                        </p>
                    </div>
                </div>
            </div>
        
            <div id="triple_event">
            <div class="formRow control-group">
                <?php echo $this->formLabel($form->get('extraPriceNet')); ?>
                <div class="formRight">
                    <?php echo $this->formElement($form->get('extraPriceNet')->setAttribute('class', 'span input')); ?>
                    <?php echo $this->formElementErrors($form->get('extraPriceNet'), array('class' => 'help-inline')); ?>
                </div>
            </div>      

            <div class="formRow control-group">
                <?php echo $this->formLabel($form->get('extraPriceGross')); ?>
                <div class="formRight">
                    <?php echo $this->formElement($form->get('extraPriceGross')->setAttribute('class', 'span input')); ?>
                    <?php echo $this->formElementErrors($form->get('extraPriceGross'), array('class' => 'help-inline')); ?>
                </div>
            </div>

            <div class="formRow control-group">
                <?php echo $this->formLabel($form->get('femalesCount')); ?>
                <div class="formRight">
                    <?php echo $this->formElement($form->get('femalesCount')->setAttribute('class', 'span input')); ?>
                    <?php echo $this->formElementErrors($form->get('femalesCount'), array('class' => 'help-inline')); ?>
                </div>
            </div>

            <div class="formRow control-group">
                <?php echo $this->formLabel($form->get('malesCount')); ?>
                <div class="formRight">
                    <?php echo $this->formElement($form->get('malesCount')->setAttribute('class', 'span input')); ?>
                    <?php echo $this->formElementErrors($form->get('malesCount'), array('class' => 'help-inline')); ?>
                </div>
            </div>
        </div>
        <div class="formRow control-group">
            <?php echo $this->formLabel($form->get('netPrice')); ?>
            <div class="formRight">
                <?php echo $this->formElement($form->get('netPrice')->setAttribute('class', 'span input')); ?>
                <?php echo $this->formElementErrors($form->get('netPrice'), array('class' => 'help-inline')); ?>
            </div>
        </div>            
        <div class="formRow control-group">
            <?php echo $this->formLabel($form->get('grossPrice')); ?>
            <div class="formRight">
                <?php echo $this->formElement($form->get('grossPrice')->setAttribute('class', 'span input')); ?>
                <?php echo $this->formElementErrors($form->get('grossPrice'), array('class' => 'help-inline')); ?>
            </div>
        </div>
        <div class="formRow control-group">
            <?php echo $this->formLabel($form->get('promo')); ?>
            <div class="formRight">
                <?php echo $this->formElement($form->get('promo')); ?>
                <?php echo $this->formElementErrors($form->get('promo'), array('class' => 'help-inline')); ?>
            </div>
        </div> 
        <div class="formRow control-group">
            <?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-info')) ?>
            <input id="resetbutton" class="btn btn-info" type="reset" value="Reset" name="reset"></input>
        </div>
        <div class="clearfix"></div>

    </div>
    <?php echo $this->form()->closeTag() ?>
</div>

<script>
    $(function() {
        $('.grid-content .formRow ul.help-inline').parents('.formRow').addClass('error');
        $('.error input').keyup(function() {
            $(this).parents('.formRow').removeClass('error');
            $(this).next('ul.help-inline').remove();
        });

        $("#triple_event").css("display", "none");
    });
    $('#events').change(function() {
        var id = $(this).val();
        $.post('/admin/inventory/ajax/event/rooms/' + id, {id: id}, function(data) {
            $('#rooms').html(data);
            dateValid();

        });
    });

    $("input:radio[name=tripleOccupancyAllowed]").click(function() {
        var value = $(this).val();
        if (value == 1) {
            $("#triple_event").css("display", "block");
        } else {
            $("#triple_event").css("display", "none");
        }
    });
    
    function dateValid(){
        var start = $("#hid-start").val();
        var end = $("#hid-end").val();
        
        $('input[name="dateFrom"]').val(start);
        $('input[name="dateTo"]').val(end);

       $('input[name="dateFrom"]').Zebra_DatePicker({
              direction: [start.toString(),end.toString()],
        })
              $('input[name="dateTo"]').Zebra_DatePicker({
              direction: [start.toString(),end.toString()],
        })

    }
    
</script>

<style>
    .toa label{margin-right: 50px !important;margin-top: -10px !important;}
</style>




