<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Settings\Module'                        => __DIR__ . '/Module.php',
    'Settings\Controller\SettingsController' => __DIR__ . '/src/Settings/Controller/SettingsController.php',
);
