<div class="formRow control-group">
    <h4>Notes</h4>
    <hr />
</div>
<div class="formRow control-group">
    <label for="adminNotes">Admin Notes</label>
    <div class="formRight">
        <textarea type="text" name="adminNotes" class="span input same-height-1" rows="4"></textarea>
    </div>
</div>
<div class="formRow control-group">
    <label for="returnTo">Client Notes</label>
    <div class="formRight">
        <textarea type="text" name="clientNotes" class="span input same-height-1" rows="4"></textarea>
    </div>
</div>