<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url(
                'orders-draft-edit',array("id"=>$data->getId())
));
$form->setAttribute('method', 'post');
//d($this->collection);
?>
<div class="grid">
    <div class="grid-title">
        <div class="pull-left">
            <div class="icon-title">
                <i class="icon-plus"></i>
            </div>
            <span>Update Reservation</span>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
    <?php echo $this->form()->openTag($form); ?>
    <div class="grid-content">
        <div class="formRow control-group">                        
            <!-- select item -->
            <div class="formRow control-group">			
                <label for="reservationType" class="required">Reservation Type</label>
                <div class="formRight">
                    <div name="reservationType" class="distance distance-2">

                        <p>
                            <input type="radio" id="fit" class="load-entity" name="type" <?php
                            if ($data->getType() == 1) {
                                echo "checked='checked'";
                            }
                            ?> checked="checked" value="1" data-resource="resorts">
                            <label for="fit"><span></span>Resort (FIT)</label>
                        </p>
                        <p>
                            <input type="radio" id="event" <?php
                            if ($data->getType() == 2) {
                                echo "checked='checked'";
                            }
                            ?> class="load-entity" name="type" value="2" data-resource="events">
                            <label for="event"><span></span> Event (Group)</label>
                        </p>
                        <p>
                            <input type="radio" id="cruise" class="load-entity" name="type" <?php
                            if ($data->getType() == 3) {
                                echo "checked='checked'";
                            }
                            ?> value="3" data-resource="cruises">
                            <label for="cruise"><span></span> Cruise</label>
                        </p>   
                    </div>
                </div>
            </div>


            <div id="entity-details">
                <div id="ajax-where" class="formRow control-group">
                    <?php if ($data->getType() == 1) { ?>
                        <label for="resortId" class="required">Hotel Name</label>                    
                        <div class="formRight">    
                            <select data-resource="resort/rooms/" id="resorts" name="resortId" required="required" class="chzn-select chosen_select width-100 entity-items">                
                                <option value="">please select hotel...</option>
                                <?php foreach ($this->typeData as $item): ?>                
                                    <option value="<?php echo $item->getId(); ?>" <?php
                                    if ($this->collection['reservation']['hotelId'] == $item->getId()) {
                                        echo "selected='selected'";
                                    }
                                    ?>><?php echo $item->getTitle(); ?></option>
                                        <?php endforeach; ?>    
                            </select> 
                        </div>
                    <?php } elseif ($data->getType() == 3) { ?>
                        <label for="cruiseId" class="required">Cruise Name</label>                    
                        <div class="formRight">    
                            <select data-resource="cruise/cabins/" id="cruises" name="cruiseId" required="required" class="chzn-select chosen_select width-100 entity-items">                
                                <option value="">please select cruise...</option>
                                <?php foreach ($this->typeData as $item): ?>                
                                    <option value="<?php echo $item->getId(); ?>" <?php
                                    if ($this->collection['reservation']['hotelId'] == $item->getId()) {
                                        echo "selected='selected'";
                                    }
                                    ?>><?php echo $item->getTitle(); ?></option>
                                        <?php endforeach; ?>    
                            </select> 
                        </div>
                    <?php } else { ?>
                        <label for="eventId" class="required">Event Name</label>                    
                        <div class="formRight">    
                            <select data-resource="event/rooms/" id="events" name="eventId" required="required" class="chzn-select chosen_select width-100 entity-items">                
                                <option value="">please select event...</option>
                                <?php foreach ($this->typeData as $item): ?>                
                                    <option value="<?php echo $item->getId(); ?>" <?php
                                    if ($this->collection['reservation']['hotelId'] == $item->getId()) {
                                        echo "selected='selected'";
                                    }
                                    ?>><?php echo $item->getTitle(); ?></option>
                                        <?php endforeach; ?>    
                            </select> 
                        </div>
                    <?php } ?>
                </div>
                <div id="dates">    
                    <div class="formRow control-group">
                        <?php echo $this->formLabel($form->get('travelFrom')); ?>
                        <div class="formRight">
                            <?php
                            echo $this->formElement($form->get('travelFrom')
                                            ->setAttribute('id', 'dateFrom')
                                            ->setAttribute('class', 'span input'));
                            ?>
<?php echo $this->formElementErrors($form->get('travelFrom'), array('class' => 'help-inline')); ?>
                        </div>
                    </div>
                    <div class="formRow control-group">
                            <?php echo $this->formLabel($form->get('travelTo')); ?>
                        <div class="formRight">
                            <?php
                            echo $this->formElement($form->get('travelTo')
                                            ->setAttribute('id', 'dateTo')
                                            ->setAttribute('class', 'span input'));
                            ?>
                <?php echo $this->formElementErrors($form->get('travelTo'), array('class' => 'help-inline')); ?>
                        </div>
                    </div>
                </div>
                
                <div id="ajax-what" class="formRow control-group">
                    <?php if ($data->getType() == 1) { ?>
                        <label for="roomCategory" class="required">Room Category</label>                    
                        <div class="formRight">    
                            <select data-extra-type="<?php echo \Inventory\Model\Items::LINKED_TO_RESORT_NAME; ?>" data-type="<?php echo \Orders\Controller\AjaxController::RESORT_ROOMS; ?>" id="resort-rooms" name="roomCategory" required="required" class="chzn-select chosen_select width-100 load-item">                
                                <option value="">please select room category...</option>
                                <?php foreach ($this->roomsData as $item): ?>                
                                    <option value="<?php echo $item->getId(); ?>" resortid="<?php echo $item->getResortId(); ?>" roomid="<?php echo $item->getRoomId(); ?>" <?php if ($this->collection['reservation']['roomId'] == $item->getId()) {
                                echo "selected='selected'";
                            } ?>><?php echo $item->getRoomCategory() ?></option>
                        <?php endforeach; ?>    
                            </select> 
                        </div>
<? } ?>
<?php if ($data->getType() == 2) { ?>
                        <label for="roomCategory" class="required">Room Category</label>                    
                        <div class="formRight">    
                            <select data-extra-type="<?php echo \Inventory\Model\Items::LINKED_TO_EVENT_NAME; ?>" data-type="<?php echo \Orders\Controller\AjaxController::EVENT_ROOMS; ?>"  id="event-rooms" data-url="/event/room/" name="roomCategory" required="required" class="chzn-select chosen_select width-100 load-item">                
                                <option value="">please select room category...</option>
                                <?php foreach ($this->roomsData as $item): ?>                
                                    <option value="<?php echo $item->getId(); ?>" <?php if ($this->collection['reservation']['roomId'] == $item->getId()) {
                                echo "selected='selected'";
                            } ?>><?php echo $item->getRoomCategory() . ' ($' . $item->getGrossPrice() . ')'; ?></option>
                        <?php endforeach; ?>    
                            </select> 
                        </div>
<?php } ?>

                            <?php if ($data->getType() == 3) { ?>
                        <label for="suiteName" class="required">Suite Name</label>                    
                        <div class="formRight">    
                            <select data-extra-type="<?php echo \Inventory\Model\Items::LINKED_TO_CRUISE_NAME; ?>" data-type="<?php echo \Orders\Controller\AjaxController::CRUISE_CABINS; ?>" id="cruise-cabins" name="suiteName" required="required" class="chzn-select chosen_select width-100 load-item">                
                                <option value="">please select room category...</option>
                        <?php foreach ($this->roomsData as $item): ?>                
                                    <option value="<?php echo $item->getId(); ?>" <?php if ($this->collection['reservation']['roomId'] == $item->getId()) {
                        echo "selected='selected'";
                    } ?> ><?php echo $item->getSuiteName() . ' ($' . $item->getGrossPrice() . ')' . ' (Deck Number: ' . $item->getDeckNumber() . ')'; ?></option>
    <?php endforeach; ?>    
                            </select> 
                        </div>
                        <?php } ?>


                </div>
                
                <div id="entity-item-details">
<!--                    <div class="formRow control-group">
                            <?php echo $this->formLabel($form->get('travelFrom')); ?>
                        <div class="formRight">
<?php
echo $this->formElement($form->get('travelFrom')
                ->setAttribute('id', 'dateFrom')
                ->setAttribute('class', 'span input'));
?>
                            <?php echo $this->formElementErrors($form->get('travelFrom'), array('class' => 'help-inline')); ?>
                        </div>
                    </div>
                    <div class="formRow control-group">
                            <?php echo $this->formLabel($form->get('travelTo')); ?>
                        <div class="formRight">
<?php
echo $this->formElement($form->get('travelTo')
                ->setAttribute('id', 'dateTo')
                ->setAttribute('class', 'span input'));
?>
                            <?php echo $this->formElementErrors($form->get('travelTo'), array('class' => 'help-inline')); ?>
                        </div>
                    </div>-->
                    <div class="formRow control-group">
                        <?php echo $this->formLabel($form->get('noOfDays')); ?>
                        <div class="formRight">
<?php echo $this->formElement($form->get('noOfDays')->setAttribute('class', 'span input')); ?>
                            <?php echo $this->formElementErrors($form->get('noOfDays'), array('class' => 'help-inline')); ?>
                        </div>
                    </div>
                    <div class="formRow control-group">
                            <?php echo $this->formLabel($form->get('roomRate')); ?>
                        <div class="formRight input-prepend">
                            <span class="add-on">$</span>
<?php
echo $this->formElement($form->get('roomRate')
                ->setAttribute('id', 'grossPrice')
                ->setAttribute('class', 'span8 input'));
?>
<?php echo $this->formElementErrors($form->get('roomRate'), array('class' => 'help-inline')); ?>
                        </div>
                    </div>
                    <div class="formRow control-group" style="display:none;">
                        <label for="inv_room_avail">Rooms Available</label>
                        <div class="formRight">
                            <span id="inventory_room_available"></span>
                        </div>
                    </div>
                    <div class="formRow control-group">
<?php echo $this->formLabel($form->get('roomRequired')); ?>
                        <div class="formRight">
<?php echo $this->formElement($form->get('roomRequired')->setAttribute('class', 'span input')); ?>
<?php echo $this->formElementErrors($form->get('roomRequired'), array('class' => 'help-inline')); ?>
                        </div>
                    </div>
                </div>
            </div>

            <style>
                #inventory_room_available{color:green;}
            </style>

                <?php echo $this->partial('partial/orders_form/traveller_details_edit'); ?> 

<?php echo $this->partial('partial/orders_form/flight_details_edit'); ?>

            <div id="ajax-items" class="formRow control-group">
<?php
if ($this->addons['items']):
    ?>
                    <div class="formRow control-group">
                        <h4>Items</h4>
                        <hr />
                    </div>
                    <label for="items">Select Items</label>    
                    <div class="formRight multicheckbox">
                        <div class="distance distance-2">
    <?php $i = 0; ?>
    <?php foreach ($this->addons['items'] as $item): 
        $check = in_array($item->getId(), $this->collection['reservation']['items']);
        ?>
                                <label>
                                    <input type="checkbox" name="items[]" <?php if($check){echo "checked='checked'"; }?> class="span input" value="<?php echo $item->getId(); ?>" netprice="<?php echo $item->getNetPrice(); ?>" grossprice="<?php echo $item->getGrossPrice(); ?>"><?php echo $item->getName() . ' ($' . $item->getGrossPrice() . ')'; ?>
                                </label>                
    <?php endforeach; ?>
                        </div>
                </div>
                <div class="formRow control-group">
                    <label for="itemsCost">Items Cost</label>                
                    <div class="formRight">    
                        <input name="itemsCost" type="number" min="0" readonly="readonly" class="span input" value="<?php echo $data->getItemCost(); ?>">                                    
                    </div>
                </div>
            <?php endif; ?>

        </div>
        <div id="ajax-excursion" class="formRow control-group">
<?php
if ($this->addons['excursions']):
    //d($this->collection);die;
    ?>
                <div class="formRow control-group">
                    <h4>Excursions</h4>
                    <hr />
                </div>
                <label>Select Excursions</label>    
                <div class="formRight multicheckbox">
                    <div class="distance distance-2">
    <?php $i = 0; ?>
    <?php foreach ($this->addons['excursions'] as $item): 
        $check = in_array($item->getId(), $this->collection['reservation']['excursions']);
        ?>
                            <label>
                                <input type="checkbox" name="excursions[]" <?php if($check){echo "checked='checked'"; }?> class="span input" value="<?php echo $item->getId(); ?>" netprice="<?php echo $item->getNetPrice(); ?>" grossprice="<?php echo $item->getGrossPrice(); ?>"><?php echo $item->getExcursionName() . ' ($' . $item->getGrossPrice() . ')'; ?>
                            </label>                
    <?php endforeach; ?>
                    </div>
            </div>
            <div class="formRow control-group">
                <label for="excursionsCost">Excursions Cost</label>                
                <div class="formRight">    
                    <input name="excursionsCost" type="number" min="0" readonly="readonly" class="span input" value="<?php echo $data->getExcursionCost(); ?>">                                    
                </div>
            </div>
        <?php endif; ?> 

    </div>
    <div id="ajax-transfer" class="formRow control-group">
<?php
if ($this->addons['transfers']):
    //d($this->collection);die;
    ?>
            <div class="formRow control-group">
                <h4>Transfers</h4>
                <hr />
            </div>
            <label>Select Transfers</label>    
            <div class="formRight multicheckbox">
                <div class="distance distance-2">
    <?php $i = 0; ?>
    <?php foreach ($this->addons['transfers'] as $item): 
        $check = in_array($item->getId(), $this->collection['reservation']['transfers']);
        ?>
                        <label>
                            <input type="checkbox" name="transfers[]" <?php if($check){echo "checked='checked'"; }?> class="span input" value="<?php echo $item->getId(); ?>" netprice="<?php echo $item->getNetPrice(); ?>" grossprice="<?php echo $item->getGrossPrice(); ?>"><?php echo $item->getTransferName() . ' ($' . $item->getGrossPrice() . ')'; ?>
                        </label>                
    <?php endforeach; ?>
                </div>
        </div>
        <div class="formRow control-group">
            <label for="transfersCost">Transfers Cost</label>                
            <div class="formRight">    
                <input name="transfersCost" type="number" min="0" readonly="readonly" class="span input" value="<?php echo $data->getTransferCost(); ?>">                                    
            </div>
        </div>
<?php endif; ?>

</div>
<?php echo $this->partial('partial/orders_form/cost_part'); ?>

<?php echo $this->partial('partial/orders_form/notes'); ?>

    <?php echo $this->partial('partial/orders_form/payment', array('form' => $form)); ?>
<div class="formRow control-group"> 
    <label for="Status" class="required">Status</label>                    
    <div class="formRight">    
        <select  id="status" name="status" required="required" class="chzn-select chosen_select width-100">                
            <option value="">please select</option>
            <option value="1" <?php if($data->getStatus() == 1):echo "selected='selected'"; endif;?> >Open</option>
            <option value="2" <?php if($data->getStatus() == 2):echo "selected='selected'"; endif;?>>Closed</option>
            <option value="0" <?php if($data->getStatus() == 0):echo "selected='selected'"; endif;?> >Cancelled</option>
        </select> 
    </div>
</div>

<input type="hidden" id="today" value="<?php echo date('Y-m-d'); ?>">
<input type="hidden" name="id" value="<?php echo $data->getId(); ?>">

<div class="formRow control-group">
<?php //echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-info'))    ?>
    <a data-toggle="modal-preview" class="btn btn-info" href="<?php echo $this->url('orders-ajax-reservation'); ?>" data-target=".bs-example-modal-lg">
        Preview
    </a> 
<!--    <a data-toggle="modal-preview" class="btn btn-info" href="#<?php //echo $this->url('orders-ajax-reservation');    ?>" data-target=".bs-example-modal-lg">
        Email as Quote
    </a>-->
    <button id="creat_pay" class="btn btn-success" type="submit"  name="submit" onclick=''>Proceed To Billing</button>
<!--    <button id="creat" class="btn btn-success" type="submit"  name="submit" onclick=''>Save As Draft</button>-->
    <button id="resetbutton" class="btn btn-warning" type="reset"  name="reset" >Reset</button>                                

</div>
<div id="ajax-script"></div>
<div class="clearfix"></div>

</div>
<?php echo $this->form()->closeTag() ?>
</div>
    
</div>
<?php echo $this->partial('orders/ajax/modal.phtml'); ?>
<script src="/js/date-formater.js"></script>
<script src="/js/reservation.js"></script>
<script>
    Reservation.init();
    $(function() {
        $('.grid-content .formRow ul.help-inline').parents('.formRow').addClass('error');
        $('.error input').keyup(function() {
            $(this).parents('.formRow').removeClass('error');
            $(this).next('ul.help-inline').remove();
        });




    });



</script>
<script>
// Make sure the DOM elements are loaded and accounted for


    $(document).ready(function() {
        $('a[data-toggle="modal-preview"]').click(function() {
            var remote_content = $(this).attr('href');
            //console.log(remote_content);            
            var modal = $('.bs-example-modal-lg');
            var modalBody = $('.bs-example-modal-lg .modal-body');
            var data = $("#orders").serialize();

            $.post(remote_content, {data: data}, function(data) {
                modalBody.html(data);
                modal.modal();
            });

            return false;
        });
        $('input[name="noOfPersons"]').val(<?php echo $data->getNoOfPersons(); ?>);
    });

</script>



