<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Accounts\Module'                        => __DIR__ . '/Module.php',
    'Accounts\Controller\AccountsController' => __DIR__ . '/src/Accounts/Controller/AccountsController.php',
);
