<?php 

$form = $this->form;

$form->prepare();
$form->setAttribute('action', $this->url(
		'cabins-edit', array('id' => $form->get('id')->getValue())
));

$form->setAttribute('method', 'post');
$form->setAttribute('enctype', 'multipart/form-data');

?>
<div class="grid">
	<div class="grid-title">
		<div class="pull-left">
			<div class="icon-title">
				<i class="icon-edit"></i>
			</div>
			<span>Edit Cabin</span>
			<div class="clearfix"></div>
		</div>
		<div class="clearfix"></div>
	</div>
	<?php echo $this->form()->openTag($form); ?>
	<?php echo $this->formElement($form->get('id')); ?>
	<div class="grid-content">
	
		<div class="formRow control-group">
			<?php echo $this->formLabel($form->get('cruiseId')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('cruiseId')->setAttribute('class', 'chzn-select chosen_select width-100')->setAttribute('required', 'required')); ?>
	        	<?php echo $this->formElementErrors($form->get('cruiseId'), array('class' => 'help-inline')); ?>
			</div>
		</div>	
            
                <div class="formRow control-group">
			<?php echo $this->formLabel($form->get('deckNumber')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('deckNumber')->setAttribute('class', 'chzn-select chosen_select width-100')->setAttribute('required', 'required')); ?>
	        	<?php echo $this->formElementErrors($form->get('deckNumber'), array('class' => 'help-inline')); ?>
			</div>
		</div>	
            
                <div class="formRow control-group">
			<?php echo $this->formLabel($form->get('deckName')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('deckName')->setAttribute('class', 'span input')->setAttribute('required', 'required')); ?>
	        	<?php echo $this->formElementErrors($form->get('deckName'), array('class' => 'help-inline')); ?>
			</div>
		</div>
            
                <div class="formRow control-group">
			<?php echo $this->formLabel($form->get('deckImageUrl')); ?>
			<div class="formRight">
                                <img src="<?php echo $this->image; ?>" alt=""> OR Change Image 
				<?php echo $this->formElement($form->get('deckImageUrl')); ?>
                                <?php echo $this->formElementErrors($form->get('deckImageUrl'), array('class' => 'help-inline')); ?>
			</div>
                </div>
		
		<div class="formRow control-group">
			<?php echo $this->formLabel($form->get('description')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('description')->setAttribute('class', 'span input same-height-1')->setAttribute('rows', '3')); ?>
	        	<?php echo $this->formElementErrors($form->get('description'), array('class' => 'help-inline')); ?>
			</div>
		</div>
            
                <div class="formRow control-group">
                            <?php echo $this->formLabel($form->get('price')); ?>
                            <div class="formRight">
                                    <?php echo $this->formElement($form->get('price')); ?>
                            <?php echo $this->formElementErrors($form->get('price'), array('class' => 'help-inline')); ?>
                            </div>
                </div>

<!--                <div class="formRow control-group">
                            <?php echo $this->formLabel($form->get('inStock')); ?>
                            <div class="formRight">
                                    <?php echo $this->formElement($form->get('inStock')); ?>
                            <?php echo $this->formElementErrors($form->get('inStock'), array('class' => 'help-inline')); ?>
                            </div>
                </div>-->
		
		<div class="formRow control-group">
			<?php echo $this->formSubmit( $form->get('submit')->setAttribute('class', 'btn btn-info')) ?>
		</div>
										
		<div class="clearfix"></div>																
										
		<div class="clearfix"></div>

	</div>
	<?php echo $this->form()->closeTag() ?>
</div>

<script>

				
	$(function(){
		$('.grid-content .formRow ul.help-inline').parents('.formRow').addClass('error');
		$('.error input').keyup(function(){
					$(this).parents('.formRow').removeClass('error');
					$(this).next('ul.help-inline').remove();
		});

		
	});				
</script>


