<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Sales\Module'                        => __DIR__ . '/Module.php',
    'Sales\Controller\PromosController' => __DIR__ . '/src/Sales/Controller/PromosController.php',
    'SalesTest\Framework\TestCase'        => __DIR__ . '/tests/Sales/Framework/TestCase.php',
    'SalesTest\SampleTest'                => __DIR__ . '/tests/Sales/SampleTest.php',
);
