<?php 
  //echo "<pre>";

  //   print_r($collection);
//die;
 ?>

<script>
    function printPage(id) 
    {
        var mywindow = window.open('<?php echo $this->url('print-invoice')?>'+id, 'Advanced Communication Skills', 'left=10,top=10,height=700,width=700,scrollbars=1,resizable=1');
    }
</script>

<div class="grid">
	<div class="grid-title">
		<div class="pull-left">
			<div class="icon-title">
                            <i class="icon-list"></i>
                        </div> 
			<span>View Invoices</span>
			<div class="clearfix"></div>
		</div>
		<div class="clearfix"></div>
	</div>
	
	
	
	
</div>
<div class="grid">    
    <div class="grid-content overflow">

        <table class="table table-bordered table-mod-2" id="datatable_3">
            <thead>
                <tr>                    
                    <th class="hidden-mobile">Invoice No.</th>
		    <th class="hidden-mobile">Client Name</th>
		     <th class="hidden-mobile">Status</th>
                    <th class="hidden-mobile">Created On</th>
                    <th class="hidden-mobile">Actions</th>
                </tr>
            </thead>
            <tbody>
                <?php                
                foreach ($this->collection as $item): 

		   $invoiceid = $item['id'];
                   $dateadded = $item['dateadded'];
                   $travellers = $item['travellers'][0]['clientName'];
		   $totalamount = $item['travellers'][0]['totalamount']; 
		   $amountpaid = $item['amountpaid'];

 
		   if(!empty($travellers)){ 

			?>
                    <tr>
                        <td class="hidden-mobile"><?php  echo $invoiceid; ?></td>     
		        <td class="hidden-mobile"><?php echo  $travellers; ?></td> 

		<?php	if($totalamount==$amountpaid){
				$status="Paid";

			}else{ $status="<p style='color:red;'>Due</p>"; } ?>
			<td class="hidden-mobile"><?php echo $status ; ?></td>  
                        <td class="hidden-mobile"><?php  echo  $dateadded->format('M d, Y');//echo $dateadded; ?></td>                        
                  

                        
                                                                        
                        <td class="action-table">

			    <a href="<?php echo $this->url('invoice-view', array('id' => $invoiceid)); ?>" title="View">
                                <img src="/images/icon/table_view.png" alt="View">
                            </a>

			      <a title="Print" href="javascript:printPage(<?php echo $invoiceid ; ?>)">
                                <i class="icon-print"></i>
                            </a>

                            
                    <!--        <a href="javascript:alert('In Progress...')" title="Print Invoice">
                                <i class="icon-print"></i>
                            </a>
                             <a href="javascript:alert('In Progress...')" title="Mail Invoice">
                                <i class="icon-envelope"></i>
                             </a>
                            <a href="javascript:alert('In Progress...')" title="Payment Receipts">
                                <i class="icon-user"></i>
                             </a>
                            <a href="javascript:alert('In Progress...')" title="Make Payment">
                                <i class="icon-money"></i>
                             </a>
-->                            <a href="javascript:alert('In Progress...')<?php //echo $this->url('invoice-edit', array('id' => $item->getId())); ?>">
                                <img src="/images/icon/table_edit.png" title="Edit Invoice">
                            </a>
                            <a href="javascript:alert('In Progress...')<?php //echo $this->url('invoice-delete', array('id' => $item->getId())); ?>"
                               data-confirm="Are you sure?">
                                <img src="/images/icon/table_del.png" title="Delete Invoice">
                            </a> 
                        </td>
                        
                    </tr>                    
                <?php } endforeach; ?>
            </tbody>
        </table>
        <div class="clearfix"></div>
    </div>
</div>
