<?php
//echo "<pre>";

//print_r($this->collection);
//die;
?>

<script>
    function printPage(id) 
    {
        var mywindow = window.open('<?php echo $this->url('print-reservation')?>'+id, 'Advanced Communication Skills', 'left=10,top=10,height=700,width=700,scrollbars=1,resizable=1');
    }
</script>
<div class="grid">
	<div class="grid-title">
		<div class="pull-left">
			<div class="icon-title">
                            <i class="icon-list"></i>
                        </div> 
			<span>Reservations</span>
			<div class="clearfix"></div>
		</div>
		<div class="clearfix"></div>
	</div>
	
	
	
	
</div>
<div class="grid">    
    <div class="grid-content overflow">

        <table class="table table-bordered table-mod-2" id="datatable_3">
            <thead>
                <tr>                    
                    <th class="hidden-mobile">Reservation No.</th>
                    <th class="hidden-mobile">Clients Name</th>
                    <th class="hidden-mobile">Type</th>
                    <th class="hidden-mobile">RoomName</th>
                    <th class="hidden-mobile">Status</th>
                    <th class="hidden-mobile">Actions</th>
                    					
                </tr>
            </thead>
            <tbody>
                <?php                
                    foreach ($this->collection as $item): 
                     
		    
                    $type = $item['type'];
                    $roomName = $item['roomName'];
                    $travellers = $item['travellers'];
                    $reservation = $item['reservation'];
                    $status = $item['status'];

		//    echo $type;


		    if($type=="Group"){

?>                  
                
                    <tr>
                        <td class="hidden-mobile"><?php echo $reservation->getId(); ?></td>                        
                        <td class="hidden-mobile"><?php  
                                foreach ($travellers as $traveller){
                                    echo $traveller.', ';
                                }
                        
                        ?></td>
                        <td class="hidden-mobile"><?php echo $type; ?></td> 
                        <td class="hidden-mobile"><?php echo $roomName; ?></td>
                        <td class="hidden-mobile"><?php echo $status; ?></td> 
                        <td class="action-table">                            
                            <a href="<?php echo $this->url('orders-view', array('id' => $reservation->getId())); ?>" title="View">
                                <img src="/images/icon/table_view.png" alt="View">
                            </a>
                            <a href="javascript:alert('In Progress...')" title="Update">
                                <img src="/images/icon/table_edit.png" alt="Update">
                            </a>
                            <a href="/admin/reservation/cancel/<?php echo $item['id'] ; ?>" title="Cancel">
                                <img src="/images/icon/table_del.png" alt="Cancel">
                            </a>
                            <a title="Print" href="javascript:printPage(<?php echo $item['id'] ; ?>)">
                                <i class="icon-print"></i>
                            </a>
                            <a title="Reinstate" href="javascript:alert('In Progress...')">
                                <i class="icon-resend"></i>
                            </a>
                        </td>
                         
                    </tr>                    
                <?php } endforeach; ?>
            </tbody>
        </table>
        <div class="clearfix"></div>
    </div>
</div>