<?php 

$form = $this->form;

$form->prepare();
$form->setAttribute('action', $this->url(
		'sendmail-add'
));

$form->setAttribute('method', 'post');

?>
<div class="grid">
	<div class="grid-title">
		<div class="pull-left">
			<div class="icon-title">
				<i class="icon-plus"></i>
			</div>
			<span>Add Email Template</span>
			<div class="clearfix"></div>
		</div>
		<div class="clearfix"></div>
	</div>	
	<?php echo $this->form()->openTag($form); ?>
	<div class="grid-content">
		
		<div class="formRow control-group">
			<?php echo $this->formLabel($form->get('name')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('name')->setAttribute('class', 'span input')->setAttribute('required', 'required')); ?>
	        	<?php echo $this->formElementErrors($form->get('name'), array('class' => 'help-inline')); ?>
			</div>
		</div>
            
                <div class="formRow control-group">
                        <?php echo $this->formLabel($form->get('template')); ?>
                        <div class="formRight">
                                <?php echo $this->formElement($form->get('template')->setAttribute('class', 'chzn-select chosen_select width-100')); ?>
                        <?php echo $this->formElementErrors($form->get('template'), array('class' => 'help-inline')); ?>
                        </div>
                </div>
            
                <div class="formRow control-group">        
                        <?php echo $this->formLabel($form->get('action')); ?>
                        <div class="formRight multicheckbox">
                                <?php echo $this->formElement($form->get('action')->setAttribute('class', 'chzn-select chosen_select width-100')); ?>
                        <?php echo $this->formElementErrors($form->get('action'), array('class' => 'help-inline')); ?>
                        </div>
                </div>
		
		<div class="formRow control-group">
			<?php echo $this->formLabel($form->get('header')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('header')->setAttribute('class', 'ckeditor')); ?>
	        	<?php echo $this->formElementErrors($form->get('header'), array('class' => 'help-inline')); ?>
			</div>
		</div>
		
		<div class="formRow control-group">
			<?php echo $this->formLabel($form->get('footer')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('footer')->setAttribute('class', 'ckeditor')); ?>
	        	<?php echo $this->formElementErrors($form->get('footer'), array('class' => 'help-inline')); ?>
			</div>
		</div>
		
		<div class="formRow control-group">
			<?php echo $this->formLabel($form->get('message')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('message')->setAttribute('class', 'ckeditor')); ?>
	        	<?php echo $this->formElementErrors($form->get('message'), array('class' => 'help-inline')); ?>
			</div>
		</div>

                <div class="formRow control-group">
			<?php echo $this->formSubmit( $form->get('submit')->setAttribute('class', 'btn btn-info')) ?>                        
		</div>
		<div class="clearfix"></div>

	</div>
	<?php echo $this->form()->closeTag() ?>
</div>

<script>
				
	$(function(){
		$('.grid-content .formRow ul.help-inline').parents('.formRow').addClass('error');
		$('.error input').keyup(function(){
					$(this).parents('.formRow').removeClass('error');
					$(this).next('ul.help-inline').remove();
		});

	});				
</script>


