<?php
use Sendmail\Model\Plugin\SendMailHelper;

if (!is_null($this->message)):
    if ($this->message):
        ?>		
        <div class="alert alert-dismissable alert-<?php echo $this->message[0]['type']; ?>">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <ul>
                <li><?php echo $this->message[0]['message']; ?></li>        
            </ul>
        </div>
        <?php
    endif;
endif;
?>

<div class="grid">
    <div class="grid-title">
        <div class="pull-left">
            <div class="icon-title">
                <i class="icon-list"></i>
            </div>
            <span>Email Templates</span>

            <div class="clearfix"></div>
        </div>
        <div class="pull-right">
            <div class="icon-title">
                <a href="<?php echo $this->url('sendmail-add'); ?>"><i class="icon-plus-sign"></i></a>
            </div>
        </div>
        <!--		<div class="pull-right">
                                <div class="icon-title">
                                        <a href="javascript:void(0);"><i class="icon-refresh"></i></a>
                                </div>
                                <div class="icon-title">
                                        <a href="javascript:void(0);"><i class="icon-cog"></i></a>
                                </div>
                        </div>-->
        <div class="clearfix"></div>
    </div>




    <div class="grid-content overflow">

        <table class="table table-bordered table-mod-2" id="datatable_3">
            <thead>
                <tr>					
                    <th class="hidden-mobile">Name</th>
                    <th class="hidden-mobile">Header</th>
                    <th class="hidden-mobile">Footer</th>
                    <th class="hidden-mobile">Message</th>                    
                    <th class="hidden-mobile">Template</th>
                    <th class="hidden-mobile">On Action</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <?php $i = 1;
                foreach ($this->collection as $item):
                    ?>
                    <tr>					
                        <td class="hidden-mobile"><?php echo $item->getName(); ?></td>										
                        <td class="hidden-mobile"><?php echo substr(strip_tags(htmlspecialchars_decode($item->getHeader())), 0, 50) . '...'; ?></td>
                        <td class="hidden-mobile"><?php echo substr(strip_tags(htmlspecialchars_decode($item->getFooter())), 0, 50) . '...'; ?></td>
                        <td class="hidden-mobile"><?php echo substr(strip_tags(htmlspecialchars_decode($item->getMessage())), 0, 50) . '...'; ?></td>
                        <td class="hidden-mobile"><?php echo basename($item->getTemplate(),".phtml"); ?></td>
                        <td class="hidden-mobile">
                            <span class="s_<?php echo $item->getAction() ? 'green' : 'gray'; ?>">
                                <?php 
                                    $actions = SendMailHelper::getActions(); 
									$index = $item->getAction();                                    
                                    echo $actions[$index];                                                                                                                                    
                                ?>
                            </span>
                        </td>
                        <td class="action-table">
                            <a data-toggle="modal" href="<?php echo $this->url('sendmail-item', array('id' => $item->getId()));?>" data-target=".bs-example-modal-lg">
                                <img src="/images/icon/table_view.png" alt="">
                            </a>
                            <a href="<?php echo $this->url('sendmail-edit', array('id' => $item->getId())); ?>">
                                <img src="/images/icon/table_edit.png" alt="">
                            </a>
                            <a href="<?php echo $this->url('sendmail-delete', array('id' => $item->getId())); ?>"						
                               data-confirm="Are you sure?">
                                <img src="/images/icon/table_del.png" alt="">
                            </a>
                        </td>
                    </tr>
                    <?php $i++; ?>
<?php endforeach; ?>
            </tbody>
        </table>

        <div class="clearfix"></div>
    </div>
</div>
<?php echo $this->partial('sendmail/ajax/modal.phtml');?>