<?php
$collection=$this->collection['collection']['affiliate'];
$form = $this->form;

$form->prepare();
$form->setAttribute('action', $this->url(
                'affiliate-edit', array('id' =>$collection->getId())
));

$form->setAttribute('method', 'post');
$form->setAttribute('enctype', 'multipart/form-data');

$collection=$this->collection['collection']['affiliate'];

$email = $collection->getEmail();
$companyname =$collection->getCompanyName();
$address =$collection->getAddressLine1();
$country=$collection->getCountryId();
$phone=$collection->getPhone();
$city=$collection->getCity();
$state=$collection->getState();
?>
<div class="grid">
    <div class="grid-title">
        <div class="pull-left">
            <div class="icon-title">
                <i class="icon-edit"></i>
            </div>
            <span>Edit User</span>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
    <?php echo $this->form()->openTag($form); ?>
    <?php echo $this->formElement($form->get('id')->setAttribute('value',$collection->getUserId()->getId())); ?>
    <input type="hidden" value=<?php echo $collection->getId(); ?> name='affiliateid'>
    <div class="grid-content">



        <div class="formRow control-group">
            <?php echo $this->formLabel($form->get('firstName')); ?>
            <div class="formRight">
                <?php echo $this->formElement($form->get('firstName')->setAttribute('value',$collection->getName())->setAttribute('class', 'span input')); ?>
                <?php echo $this->formElementErrors($form->get('firstName'), array('class' => 'help-inline')); ?>
            </div>
        </div>

       
        <div class="formRow control-group">
            <?php echo $this->formLabel($form->get('email')); ?>
            <div class="formRight">
                <?php echo $this->formElement($form->get('email')->setAttribute('value',$email)->setAttribute('class', 'span input')); ?>
                <?php echo $this->formElementErrors($form->get('email'), array('class' => 'help-inline')); ?>
            </div>
        </div>

          
         <div class="formRow control-group">
            <?php echo $this->formLabel($form->get('companyName')); ?>
            <div class="formRight">
                <?php echo $this->formElement($form->get('companyName')->setAttribute('value',$companyname)->setAttribute('class', 'span input')); ?>
                <?php echo $this->formElementErrors($form->get('companyName'), array('class' => 'help-inline')); ?>
            </div>
        </div>


        <div class="formRow control-group">
            <?php echo $this->formLabel($form->get('phone')); ?>
            <div class="formRight">
                <?php echo $this->formElement($form->get('phone')->setAttribute('value',$phone)->setAttribute('class', 'span input')); ?>
                <?php echo $this->formElementErrors($form->get('phone'), array('class' => 'help-inline')); ?>
            </div>
        </div>

        <div class="formRow control-group">
            <?php echo $this->formLabel($form->get('address')); ?>
            <div class="formRight">
                <?php echo $this->formElement($form->get('address')->setAttribute('value',$address)->setAttribute('class', 'span input same-height-1')->setAttribute('rows', '3')); ?>
                <?php echo $this->formElementErrors($form->get('address'), array('class' => 'help-inline')); ?>
            </div>
        </div>  

        <div class="formRow control-group">
            <?php //echo $this->formLabel($form->get('suite')); ?>
            <div class="formRight">
                <?php // echo $this->formElement($form->get('suite')->setAttribute('class', 'span input')); ?>
                <?php //echo $this->formElementErrors($form->get('suite'), array('class' => 'help-inline')); ?>
            </div>
        </div>

        <div class="formRow control-group">
            <?php echo $this->formLabel($form->get('city')); ?>
            <div class="formRight">
                <?php echo $this->formElement($form->get('city')->setAttribute('value',$city)->setAttribute('class', 'span input')); ?>
                <?php echo $this->formElementErrors($form->get('city'), array('class' => 'help-inline')); ?>
            </div>
        </div>


        <div class="formRow control-group">
            <?php echo $this->formLabel($form->get('state')); ?>
            <div class="formRight">
                <?php echo $this->formElement($form->get('state')->setAttribute('value',$state)->setAttribute('class', 'span input')); ?>
                <?php echo $this->formElementErrors($form->get('state'), array('class' => 'help-inline')); ?>
            </div>
        </div>


        <div class="formRow control-group">
            <?php echo $this->formLabel($form->get('country')); ?>
            <div class="formRight">
                <?php echo $this->formElement($form->get('country')->setAttribute('value',$country)->setAttribute('class', 'chzn-select chosen_select width-100')); ?>
                <?php echo $this->formElementErrors($form->get('country'), array('class' => 'help-inline')); ?>
            </div>
        </div>






        <div class="formRow control-group password"  style="display:none">
            <?php echo $this->formLabel($form->get('password')); ?>
            <div class="formRight">
                <?php
                echo $this->formElement($form->get('password')
                                ->setAttribute('class', 'span input')
                                ->setAttribute('id', 'pass1')
                                ->setAttribute('require', 'require')
                );
                ?>
                <?php echo $this->formElementErrors($form->get('password'), array('class' => 'help-inline')); ?>
            </div>
        </div>		
        <div class="formRow control-group password" style="display:none">
            <?php echo $this->formLabel($form->get('repassword')); ?>
            <div class="formRight">
                <?php
                echo $this->formElement($form->get('repassword')
                                ->setAttribute('class', 'span input')
                                ->setAttribute('id', 'pass2')
                                ->setAttribute('require', 'require')
                                ->setValue($form->get('password')->getValue())
                );
                ?>
                <?php echo $this->formElementErrors($form->get('repassword'), array('class' => 'help-inline')); ?>
            </div>
        </div>



        <div class="formRow control-group">
            <?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-info')) ?>
            <div class="formRight">
                <button type="button" id="changePswd" class="btn btn-warning">Change Password</button>
            </div>
        </div>
        <div class="clearfix"></div>

    </div>
    <?php echo $this->form()->closeTag() ?>
</div>

<script>

    function checkPass() {

        var pass = $('#pass1').val();
        var repass = $('#pass2').val();

        console.log(pass !== repass && pass == '');

        if (pass !== repass || pass == '' || repass == '') {
            $('#pass1, #pass2').parents('.formRow').addClass('error');//.append('<ul class="help-inline"><li>Password does not match the confirm password</li></ul>')
            $('#submitbutton').attr('disabled', 'disabled');
        } else {
            $('#pass1, #pass2').parents('.formRow').removeClass('error').addClass('success');
            $('#submitbutton').removeAttr('disabled');
        }
    }
    ;

    function changePass() {
        $('.password').show();
        $('.password input[type=password]').val('');
        $('#submitbutton').attr('disabled', 'disabled');
    }

    $(function() {
        $('.grid-content .formRow ul.help-inline').parents('.formRow').addClass('error');
        $('.error input').keyup(function() {
            $(this).parents('.formRow').removeClass('error');
            $(this).next('ul.help-inline').remove();
        });

        $('#pass1, #pass2').keyup(checkPass);
        $('#changePswd').click(changePass);
    });
</script>


