<?php
$date = date('Y-m-d');

?>

<script>
    $(function() {
        $('#myselect option[value=<?php
if (!empty($this->paymenttyp)) {
    echo $this->paymenttyp;
} else {
    echo '';
}
?>]').attr('selected', 'selected');
    });
</script> 
<?php if (!is_null($this->message)):
    
   // d($this->message);
    if ($this->message):
        ?>		
        <div class="alert alert-dismissable alert-<?php echo $this->message[0]['type']; ?>">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <ul>
                <li><?php echo $this->message[0]['message']; ?></li>        
            </ul>
        </div>
        <?php
    endif;
endif;
?>

<div class="grid">
    <div class="grid-title">
        <div class="pull-left">
            <div class="icon-title">
                <i class="icon-list"></i>
            </div> 
            <span>Event Feature</span>
            <div class="clearfix"></div>
        </div>
        <div class="pull-right">
            <div class="icon-title">
                <a href="<?php echo $this->url('affiliate-event-feature-add',array('id' => $this->id)); ?>"><i class="icon-plus-sign"></i></a>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>




</div>
<div class="grid">    
    <div class="grid-content overflow">

     

        <table class="table table-bordered table-mod-2" id="datatable_3">
            <thead>
                <tr>                    
                 <!--   <th class="hidden-mobile">Reservation No.</th> -->
                    <th class="hidden-mobile">Image</th>
                    <th class="hidden-mobile">Title</th>
                    <th class="hidden-mobile">Description</th>
                    <th class="hidden-mobile">Date Added</th>
                    <th class="hidden-mobile">Action</th>

                </tr>
            </thead>
            <tbody>
                <?php
                $total = 0;
                $i = 0;
                $totalreceived = 0;
                $totaldue = 0;
                foreach ($this->collection as $item):

                    ?>                  

                    <tr>

                        <td class="hidden-mobile"><img width="135" height="35" src="http://192.155.246.146:9084/app/webroot/img/user_uploads/eventfeatures/<?php echo $item->getImage(); ?>" alt=""> </td>    
                        <td class="hidden-mobile"><?php echo $item->getTitle()   ?></td>
                        <td class="hidden-mobile"><?php echo $item->getDescription() ? substr(strip_tags($item->getDescription()), 0, 50) . '...' : '-' ?></td>
                        <td class="hidden-mobile"><?php echo $item->getAddedOn()->format('Y-m-d'); ?> </td>
                        
                        <td class="action-table">  
                            
                            
                            <a href="<?php  echo $this->url('affiliate-event-feature-edit', array('id' => $item->getId())); ?>" >
                                <img src="/images/icon/table_edit.png" alt="">
                            </a>
                        
                            <a href="<?php  echo $this->url('affiliate-event-feature-delete', array('id' => $item->getId())); ?>"  data-confirm="Are you sure?">
                                <img src="/images/icon/table_del.png" alt="">
                            </a>
                        
                        </td>



                    </tr>                    
                <?php endforeach; ?>
            </tbody>
        </table>


        <div class="clearfix"></div>
    </div>
</div>