<?php
$date = date('Y-m-d');
//d($this->collection);
?>

<script>
    $(function() {
        $('#myselect option[value=<?php
if (!empty($this->paymenttyp)) {
    echo $this->paymenttyp;
} else {
    echo '';
}
?>]').attr('selected', 'selected');
    });
</script> 
<?php if (!is_null($this->message)):
    
   // d($this->message);
    if ($this->message):
        ?>		
        <div class="alert alert-dismissable alert-<?php echo $this->message[0]['type']; ?>">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <ul>
                <li><?php echo $this->message[0]['message']; ?></li>        
            </ul>
        </div>
        <?php
    endif;
endif;
?>

<div class="grid">
    <div class="grid-title">
        <div class="pull-left">
            <div class="icon-title">
                <i class="icon-list"></i>
            </div> 
            <span>Event Rooms</span>
            <div class="clearfix"></div>
        </div>
        <div class="pull-right">
            <div class="icon-title">
                <a href="<?php echo $this->url('affiliate-event-rooms-add',array('id' => $this->id)); ?>"><i class="icon-plus-sign"></i></a>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>




</div>
<div class="grid">    
    <div class="grid-content overflow">

     

        <table class="table table-bordered table-mod-2" id="datatable_3">
            <thead>
                <tr>                    
                 <!--   <th class="hidden-mobile">Reservation No.</th> -->
                    <th class="hidden-mobile">Room Category</th>
                    <th class="hidden-mobile">Room Price(USD)</th>
                    <th class="hidden-mobile">Room Price(CAD)</th>
                    <th class="hidden-mobile">Availability</th>
                    <th class="hidden-mobile">Action</th>

                </tr>
            </thead>
            <tbody>
                <?php
           
                foreach ($this->collection as $item):                 
                   $status = $item->getStatus()==1 ? 'Available' :'Sold Out';  ;   ?> 
                    <tr>

                        <td class="hidden-mobile"><?php echo $item->getRoomCategory(); ?></td>    
                        <td class="hidden-mobile"><?php echo $item->getRoomPrice();   ?></td>
                        <td class="hidden-mobile"><?php echo $item->getRoomPriceCad() ?></td>
                        <td class="action-table"><?php echo $status;?></td>  
                            
                         <td class="action-table">    
                            <a href="<?php  echo $this->url('affiliate-event-rooms-edit', array('id' => $item->getId())); ?>" >
                                <img src="/images/icon/table_edit.png" alt="">
                            </a>
                        
                            <a href="<?php  echo $this->url('affiliate-event-rooms-delete', array('id' => $item->getId())); ?>"  data-confirm="Are you sure?">
                                <img src="/images/icon/table_del.png" alt="">
                            </a>
                        
                        </td>



                    </tr>                    
                <?php endforeach; ?>
            </tbody>
        </table>


        <div class="clearfix"></div>
    </div>
</div>