<link rel="stylesheet" href="/css/jquery.ui.timepicker.css">
<script type="text/javascript" src="/js/jquery.ui.timepicker.js"></script>
<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url(
                'affiliate-event-itinerary-edit', array('id' =>$this->id)
));
$form->setAttribute('method', 'post');
$form->setAttribute('enctype', 'multipart/form-data');
//d($form->get('time')->getValue()->format('H:i:s'));
if ($form->get('time')->getValue() instanceof DateTime)
    $form->get('time')->setValue($form->get('time')->getValue()->format('H:i:s')); // DateTime to str fix;
?>
<script type="text/javascript">
    $(document).ready(function() {

        $('.time_picker').timepicker({'timeFormat': 'H:i:s'});
    });
</script>
<div class="grid">
    <div class="grid-title">
        <div class="pull-left">
            <div class="icon-title">
                <i class="icon-edit"></i>
            </div>
            <span>Edit Itineraries</span>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
    <?php echo $this->form()->openTag($form); ?>
    <?php echo $this->formElement($form->get('id')); ?>
   <!-- <input type="hidden" value=<?php //echo $this->eventid; ?> name="event_id" > -->
    <div class="grid-content">

        
        
        <div class="formRow control-group">
            <?php echo $this->formLabel($form->get('time')); ?>
            <div class="formRight">
                <?php echo $this->formElement($form->get('time')->setAttribute('class', 'time_picker')->setAttribute('required', 'required')); ?>
                <?php echo $this->formElementErrors($form->get('time'), array('class' => 'help-inline')); ?>
            </div>
        </div>	

       

        <div class="formRow control-group">Description
            <?php //echo $this->formLabel($form->get('title')); ?>
            <div class="formRight">
                <?php echo $this->formElement($form->get('title')->setAttribute('type', 'textarea')->setAttribute('class', 'ckeditor')); ?>
                <?php echo $this->formElementErrors($form->get('title'), array('class' => 'help-inline')); ?>
            </div>
        </div>	
        
       


      

        <div class="formRow control-group">
            <?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-info')) ?>
        </div>

        <div class="clearfix"></div>

    </div>
    <?php echo $this->form()->closeTag() ?>
</div>

<script>


    $(function() {
        $('.grid-content .formRow ul.help-inline').parents('.formRow').addClass('error');
        $('.error input').keyup(function() {
            $(this).parents('.formRow').removeClass('error');
            $(this).next('ul.help-inline').remove();
        });


    });
</script>


