<link rel="stylesheet" href="/css/jquery.ui.timepicker.css">
<script type="text/javascript" src="/js/jquery.ui.timepicker.js"></script>


<script type="text/javascript">
    $(document).ready(function() {

        $('.time_picker').timepicker({'timeFormat': 'H:i:s'});
    });
</script>

<div class="grid">
    <div class="grid-title">
        <div class="pull-left">
            <div class="icon-title">
                <i class="icon-edit"></i>
            </div>
            <span>Add Itineraries</span>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>

    <div class="grid-content">
        <?php
        //d($this->data);

        $date = $this->data->getStartDate()->format('Y-m-d');
        // End date
        $end_date = $this->data->getEndDate()->format('Y-m-d');


        $i = 0;
        for ($i; strtotime($date) <= strtotime($end_date); $i++) {

            $newTime = date('F jS Y', $date);
            ?>  


            <?php
            $form = $this->form;

            $form->prepare();
            $form->setAttribute('action', $this->url(
                            'affiliate-event-itinerary-add', array('id' => $this->id)
            ));

            $form->setAttribute('method', 'post');
            $form->setAttribute('enctype', 'multipart/form-data');

//d($form->get('id')->getValue());
            ?>   

            <?php echo $this->form()->openTag($form); ?>
            <?php echo $this->formElement($form->get('id')->setValue($this->id)); ?>

            <div class="formRow control-group">
                <?php echo date("l jS M, Y", strtotime($date)); ?>
                <?php //echo $newTime;  ?>
                <div class="formRight">
                </div>
            </div>	

            <?php //echo $this->partial('partial/orders_form/promos_part');  ?>
            <div class="formRow control-group">Time
                <?php //echo $this->formLabel($form->get('time'));  ?>
                <div class="formRight">
                    <input type='text' name="time" id="time.<?php echo $i; ?>>" class="time_picker" required="required">
                 </div>
            </div>	



            <div class="formRow control-group">
                Description
                <div class="formRight">
                    <?php echo $this->formElement($form->get('title')->setAttribute('type','textarea')->setAttribute('required','')->setAttribute('class', 'ckeditor'));  ?>
                    <?php echo $this->formElementErrors($form->get('title'), array('class' => 'help-inline'));  ?>
                </div>
            </div>
        
             <input type='hidden' name="eventid" value=<?php echo $this->data->getId(); ?> >
             <input type='hidden' name="date" value=<?php echo $date; ?> >
            <div class="formRow control-group">
                <?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-info')) ?>
            </div>

              <?php echo $this->form()->closeTag() ?>


            <?php
            //  echo "$date\n";

            $date = date("Y-m-d", strtotime("+1 day", strtotime($date)));
            //  $i+1;
        }
        ?>


        <div class="clearfix"></div>

    </div>
  
</div>

<script>


    $(function() {
        $('.grid-content .formRow ul.help-inline').parents('.formRow').addClass('error');
        $('.error input').keyup(function() {
            $(this).parents('.formRow').removeClass('error');
            $(this).next('ul.help-inline').remove();
        });


    });
</script>


