<link rel="stylesheet" href="/css/jquery.ui.timepicker.css">
<script type="text/javascript" src="/js/jquery.ui.timepicker.js"></script>
<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url(
                'affiliate-event-rooms-edit', array('id' =>$this->id)
));
$form->setAttribute('method', 'post');
$form->setAttribute('enctype', 'multipart/form-data');?>
<div class="grid">
    <div class="grid-title">
        <div class="pull-left">
            <div class="icon-title">
                <i class="icon-edit"></i>
            </div>
            <span>Edit Itineraries</span>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
    <?php echo $this->form()->openTag($form); ?>
    <?php echo $this->formElement($form->get('id')); ?>
   <!-- <input type="hidden" value=<?php //echo $this->eventid; ?> name="event_id" > -->
    <div class="grid-content">

        
        
          <div class="formRow control-group">
                <?php echo $this->formLabel($form->get('roomPrice')); ?>
                <div class="formRight">
                    <?php echo $this->formElement($form->get('roomPrice')->setAttribute('placeholder','numeric value only')->setAttribute('required','required')->setAttribute('class', 'span input'));  ?>
                    <?php echo $this->formElementErrors($form->get('roomPrice'), array('class' => 'help-inline'));  ?>
                </div>
          </div>
        
        
          <div class="formRow control-group">
                <?php echo $this->formLabel($form->get('roomPriceCad')); ?>
                <div class="formRight">
                    <?php echo $this->formElement($form->get('roomPriceCad')->setAttribute('id','cad'.$i)->setAttribute('placeholder','numeric value only')->setAttribute('required','required')->setAttribute('class', 'span input'));  ?>
                    <?php echo $this->formElementErrors($form->get('roomPriceCad'), array('class' => 'help-inline'));  ?>
                </div>
          </div>
        
        <div class="formRow control-group">
                <?php echo $this->formLabel($form->get('status')); ?>
                <div class="formRight">
                    <?php echo $this->formElement($form->get('status')
                                    ->setAttribute('class', 'span input')
                                    ->setAttribute('options',array(
                                        '0' => 'Out of stock',
                                        '1' => 'Available',
                                    ))
                            );  ?>
                    <?php echo $this->formElementErrors($form->get('status'), array('class' => 'help-inline'));  ?>
                </div>
          </div>
       
         
        <div class="formRow control-group">
                <?php echo $this->formLabel($form->get('roomCategory')); ?>
                <div class="formRight">
                    <?php echo $this->formElement($form->get('roomCategory')
                                    ->setAttribute('class', 'span input')
                                    );  ?>
                    <?php echo $this->formElementErrors($form->get('roomCategory'), array('class' => 'help-inline'));  ?>
                </div>
          </div>
        
       


      

        <div class="formRow control-group">
            <?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-info')) ?>
        </div>

        <div class="clearfix"></div>

    </div>
    <?php echo $this->form()->closeTag() ?>
</div>

<script>


    $(function() {
        $('.grid-content .formRow ul.help-inline').parents('.formRow').addClass('error');
        $('.error input').keyup(function() {
            $(this).parents('.formRow').removeClass('error');
            $(this).next('ul.help-inline').remove();
        });


    });
</script>


