<?php
$form = $this->form;

$form->prepare();
$form->setAttribute('action', $this->url(
                'affiliate-gallery-add', array('id' =>$this->id)
));

$form->setAttribute('method', 'post');
$form->setAttribute('enctype', 'multipart/form-data');

//d($form->get('id')->getValue());
?>   

<div class="grid">
    <div class="grid-title">
        <div class="pull-left">
            <div class="icon-title">
                <i class="icon-edit"></i>
            </div>
            <span>Add Image</span>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
    <?php echo $this->form()->openTag($form); ?>
    <?php echo $this->formElement($form->get('id')->setValue($this->id)); ?>
    <div class="grid-content">

        
         <div class="formRow control-group">
            <?php echo $this->formLabel($form->get('title')); ?>
            <div class="formRight">
                <?php echo $this->formElement($form->get('title')->setAttribute('class', 'span input')->setAttribute('required', 'required')); ?>
                <?php echo $this->formElementErrors($form->get('title'), array('class' => 'help-inline')); ?>
            </div>
        </div>	
        
        <div class="formRow control-group">
            <?php echo $this->formLabel($form->get('image')); ?>
            <div class="formRight">
                <?php echo $this->formElement($form->get('image')->setAttribute('required','required')); ?>
                <?php echo $this->formElementErrors($form->get('image'), array('class' => 'help-inline')); ?>
            </div>
        </div>

      
       

        
        <div class="formRow control-group">
            <?php echo $this->formSubmit($form->get('submit')->setAttribute('class', 'btn btn-info')) ?>
        </div>

        <div class="clearfix"></div>

    </div>
    <?php echo $this->form()->closeTag() ?>
</div>

<script>


    $(function() {
        $('.grid-content .formRow ul.help-inline').parents('.formRow').addClass('error');
        $('.error input').keyup(function() {
            $(this).parents('.formRow').removeClass('error');
            $(this).next('ul.help-inline').remove();
        });


    });
</script>


