<?php
$date = date('Y-m-d');
?>
<?php if (!is_null($this->message)):
    
   // d($this->message);
    if ($this->message):
        ?>		
        <div class="alert alert-dismissable alert-<?php echo $this->message[0]['type']; ?>">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <ul>
                <li><?php echo $this->message[0]['message']; ?></li>        
            </ul>
        </div>
        <?php
    endif;
endif;
?>

<div class="grid">
    <div class="grid-title">
        <div class="pull-left">
            <div class="icon-title">
                <i class="icon-list"></i>
            </div> 
            <span>Resort Rooms</span>
            <div class="clearfix"></div>
        </div>
        <div class="pull-right">
<!--            <div class="icon-title">
                <a href="<?php //echo $this->url('affiliate-resort-rooms-add',array('id' => $this->id)); ?>"><i class="icon-plus-sign"></i></a>
            </div>-->
        </div>
        <div class="clearfix"></div>
    </div>




</div>
<div class="grid">    
    <div class="grid-content overflow">

     

        <table class="table table-bordered table-mod-2" id="datatable_3">
            <thead>
                <tr>                    
                 <!--   <th class="hidden-mobile">Reservation No.</th> -->
                    <th class="hidden-mobile">Image</th>
                    <th class="hidden-mobile">Resort Title</th>
                    <th class="hidden-mobile">Title</th>
<!--                    <th class="hidden-mobile">Price</th>-->
<!--                    <th class="hidden-mobile">Action</th>-->

                </tr>
            </thead>
            <tbody>
                <?php $i = 1;
                foreach ($this->collection as $item): 
                    ?>
                    <tr>
<!--                        <td class="t_center">
                            <input type="checkbox" id="c<?php echo $i; ?>" name="cc" />
                            <label for="c<?php echo $i; ?>"><span></span></label>
                        </td>-->

                        <td class="hidden-mobile"><img src="<?php echo $this->imagePath .$item->getImage(); ?>" alt=""></td>

                        <td class="hidden-mobile">
                            <a  data-toggle="modal" href="<?php echo $this->url('ajax-resorts-item', array('id' => $item->getResortId()->getId()));?>" data-target=".bs-example-modal-lg">
                                <?php echo $item->getResortId()->getTitle(); ?>
                            </a>
                        </td>
                        <td class="hidden-mobile"><?php echo $item->getTitle();?></td>
<!--                        <td class="hidden-mobile"><?php echo $item->getPrice(); ?></td>-->

<!--                        <td class="action-table">
                            
                            <a href="<?php echo $this->url('rooms-edit', array('id' => $item->getId())); ?>">
                                <img src="/images/icon/table_edit.png" alt="">
                            </a>
                            <a href="<?php echo $this->url('rooms-delete', array('id' => $item->getId())); ?>"
                               data-confirm="Are you sure?">
                                <img src="/images/icon/table_del.png" alt="">
                            </a>
                        </td>-->
                    </tr>
                    <?php $i++; ?>
                <?php endforeach; ?>
            </tbody>
        </table>


        <div class="clearfix"></div>
    </div>
</div>