<label for="cruiseId" class="required">Cruise Name</label>                    
<div class="formRight">    
    <select data-resource="cruise/cabins/" id="cruises" name="cruiseId" required="required" class="chzn-select chosen_select width-100 entity-items">                
        <option value="">please select cruise...</option>
        <?php foreach ($this->collection as $item):?>                
            <option value="<?php echo $item->getId();?>"><?php echo $item->getTitle();?></option>
        <?php endforeach;?>    
    </select> 
</div>
