    
<div class="grid">
    <div class="grid-title">
        <div class="pull-left">
            <div class="icon-title"></div>
            <span>Video</span>
            <div class="clearfix"></div>
        </div>        
        <div class="clearfix"></div>
    </div>
    <div class="grid-content overflow">
        <div st>
        <video width="400" height="200" controls>
                        <source src="/img/user_uploads/userdocvideos/<?php echo $video->getFile(); ?>" type="video/mp4">
<!--                        <source src="/files/video_file/<?php echo $v[0] . '.webm'; ?>" type="video/webm">-->
        </video>
        </div>    
        <div class="clearfix"></div>
   </div>
</div>

