<label for="eventCategoryId" class="required">Event Category</label>                    
<div class="formRight">    
    <select name="eventCategoryId" required="required" class="chzn-select chosen_select width-100">                
        <?php foreach ($this->collection as $item):?>                
            <option value="<?php echo $item->getId();?>"><?php echo $item->getName();?></option>
        <?php endforeach;?>    
    </select> 
</div>
<script>
    $('.chzn-select').chosen();
</script>