<?php
$date = date('Y-m-d');
//d($this->collection); die; //echo $date; die;
?>

<script>
    $(function() {
        $('#myselect option[value=<?php
if (!empty($this->paymenttyp)) {
    echo $this->paymenttyp;
} else {
    echo '';
}
?>]').attr('selected', 'selected');
    });
</script>    

<?php if (!is_null($this->message)):
    
   // d($this->message);
    if ($this->message):
        ?>		
        <div class="alert alert-dismissable alert-<?php echo $this->message[0]['type']; ?>">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <ul>
                <li><?php echo $this->message[0]['message']; ?></li>        
            </ul>
        </div>
        <?php
    endif;
endif;
?>

<div class="grid">
    <div class="grid-title">
        <div class="pull-left">
            <div class="icon-title">
                <i class="icon-list"></i>
            </div> 
            <span>Reseller Cruise</span>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>




</div>
<div class="grid">    
    <div class="grid-content overflow">

     

        <table class="table table-bordered table-mod-2" id="datatable_3">
            <thead>
                <tr>                    
                 <!--   <th class="hidden-mobile">Reservation No.</th> -->
                    <th class="hidden-mobile">Cruise Name</th>
                    <th class="hidden-mobile">Date Added</th>
                    <th class="hidden-mobile">Added By</th>
                    <th class="hidden-mobile">Status</th>
                    <!--<th class="hidden-mobile">Approval</th>-->
                    <th class="hidden-mobile">Action</th>

                </tr>
            </thead>
            <tbody>
                <?php
                $total = 0;
                $i = 0;
                $totalreceived = 0;
                $totaldue = 0;
                foreach ($this->collection as $items):
                    
//                      $item=$items['events'];
//                      $setfeature=$items['eventfeature'];
//                   //   d($setfeature);
                      $status = $items->getStatus()==1 ? 'Enabled' :'Disabled';  
//                      $approval = $items->getApproved()==1 ? 'Approved' :'Pending';  
                    ?>                  

                    <tr>

                        <td class="hidden-mobile"><?php echo $items->getTitle(); ?></td>    

                        <td class="hidden-mobile"><?php echo $items->getAddedOn()->format('Y-m-d'); ?> </td>
                        <td class="hidden-mobile"> <?php echo  $items->getUserId()->getFirstName().' '. $items->getUserId()->getLastName(); ?></td>				

                        <td class="hidden-mobile"><?php echo $status   ?></td>
                          <!--<td class="hidden-mobile"><?php echo $approval   ?></td>-->
                        
                        <td class="action-table">   
                            
                            <a href="<?php echo $this->url('affiliate-cruise-view-all',array('id'=>$items->getId())); ?>">
                                View Details
                            </a>
                            
                        
                           <a href="<?php echo $this->url('affiliate-cruise-gallery',array('id'=>$items->getId())); ?>">
                                Gallery
                           </a>
                          
<!--                            <a class="btn btn-info" href="<?php echo $this->url('affiliate-cruise-cabins',array('id'=>$items->getId())); ?>">
                                Cabins
                            
                            </a>
                                
                            <a class="btn btn-warning" href="#">
                                Add Video
                            </a>-->
                            
                              <a href="<?php echo $this->url('affiliate-cruise-delete',array('id'=>$items->getId())); ?>" data-confirm="Are you sure?">
                                Delete
                            </a>
                           
                        </td>



                    </tr>                    
                <?php endforeach; ?>
            </tbody>
        </table>


        <div class="clearfix"></div>
    </div>
</div>

