<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Payments\Module'                        => __DIR__ . '/Module.php',
    'Payments\Controller\LeadsController' => __DIR__ . '/src/Payments/Controller/PaymentsController.php',
);
