<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Leads\Module'                        => __DIR__ . '/Module.php',
    'Leads\Controller\LeadsController' => __DIR__ . '/src/Leads/Controller/LeadsController.php',
);
