<?php 

$form = $this->form;

$form->prepare();
$form->setAttribute('action', $this->url(
		'cruises-edit', array('id' => $form->get('id')->getValue())
));

$form->setAttribute('method', 'post');
$form->setAttribute('enctype', 'multipart/form-data');

if($form->get('tourStartDate')->getValue() instanceof DateTime)
	$form->get('tourStartDate')->setValue($form->get('tourStartDate')->getValue()->format('Y-m-d')); // DateTime to str fix;
if($form->get('tourEndDate')->getValue() instanceof DateTime)
	$form->get('tourEndDate')->setValue($form->get('tourEndDate')->getValue()->format('Y-m-d')); // DateTime to str fix;


?>
<div class="grid">
	<div class="grid-title">
		<div class="pull-left">
			<div class="icon-title">
				<i class="icon-edit"></i>
			</div>
			<span>Edit Cruise</span>
			<div class="clearfix"></div>
		</div>
		<div class="clearfix"></div>
	</div>
	<?php echo $this->form()->openTag($form); ?>
	<?php echo $this->formElement($form->get('id')); ?>
	<div class="grid-content">
                
                <div class="formRow control-group">
			<?php echo $this->formLabel($form->get('image')); ?>
			<div class="formRight">
                                <img src="<?php echo $this->image; ?>" alt=""> OR Change Image 
				<?php echo $this->formElement($form->get('image')); ?>
                                <?php echo $this->formElementErrors($form->get('image'), array('class' => 'help-inline')); ?>
			</div>
		</div>
		<div class="formRow control-group">
			<?php echo $this->formLabel($form->get('title')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('title')->setAttribute('class', 'span input')->setAttribute('required', 'required')); ?>
	        	<?php echo $this->formElementErrors($form->get('title'), array('class' => 'help-inline')); ?>
			</div>
		</div>		
		<div class="formRow control-group">
			<?php echo $this->formLabel($form->get('pageHeading')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('pageHeading')->setAttribute('class', 'span input')); ?>
	        	<?php echo $this->formElementErrors($form->get('pageHeading'), array('class' => 'help-inline')); ?>
			</div>
		</div>
		
		<div class="formRow control-group">
			<?php echo $this->formLabel($form->get('overview')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('overview')->setAttribute('class', 'ckeditor')->setAttribute('rows', '3')); ?>
	        	<?php echo $this->formElementErrors($form->get('overview'), array('class' => 'help-inline')); ?>
			</div>
		</div>				
		
		<div class="formRow control-group">
			<?php echo $this->formLabel($form->get('tourStartDate')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('tourStartDate')->setAttribute('class', 'span input')->setAttribute('required', 'required')); ?>
	        	<?php echo $this->formElementErrors($form->get('tourStartDate'), array('class' => 'help-inline')); ?>
			</div>
		</div>
	
		<div class="formRow control-group">
			<?php echo $this->formLabel($form->get('tourEndDate')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('tourEndDate')->setAttribute('class', 'span input')->setAttribute('required', 'required')); ?>
	        	<?php echo $this->formElementErrors($form->get('tourEndDate'), array('class' => 'help-inline')); ?>
			</div>
		</div>
	
                <div class="formRow control-group">
			<?php echo $this->formLabel($form->get('categoryId')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('categoryId')->setAttribute('class', 'chzn-select chosen_select width-100')); ?>
	        	<?php echo $this->formElementErrors($form->get('categoryId'), array('class' => 'help-inline')); ?>
			</div>
		</div>		
		<div class="formRow control-group">
			<?php echo $this->formLabel($form->get('countryId')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('countryId')->setAttribute('class', 'chzn-select chosen_select width-100')); ?>
	        	<?php echo $this->formElementErrors($form->get('countryId'), array('class' => 'help-inline')); ?>
			</div>
		</div>
            
                <div class="formRow control-group">
			<?php echo $this->formLabel($form->get('status')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('status')->setAttribute('class', 'chzn-select chosen_select width-100')); ?>
	        	<?php echo $this->formElementErrors($form->get('status'), array('class' => 'help-inline')); ?>
			</div>
		</div>
		
                <div class="formRow control-group">
			<h4>SEO Information</h4>
			<hr />
		</div>
		<div class="formRow control-group">
			<?php echo $this->formLabel($form->get('metaTitle')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('metaTitle')->setAttribute('class', 'span input')); ?>
	        	<?php echo $this->formElementErrors($form->get('metaTitle'), array('class' => 'help-inline')); ?>
			</div>
		</div>
		<div class="formRow control-group">
			<?php echo $this->formLabel($form->get('metaDescription')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('metaDescription')->setAttribute('class', 'span input same-height-1')->setAttribute('rows', '3')); ?>
	        	<?php echo $this->formElementErrors($form->get('metaDescription'), array('class' => 'help-inline')); ?>
			</div>
		</div>
		<div class="formRow control-group">
			<?php echo $this->formLabel($form->get('metaKeywords')); ?>
			<div class="formRight">
				<?php echo $this->formElement($form->get('metaKeywords')->setAttribute('class', 'span input')); ?>
	        	<?php echo $this->formElementErrors($form->get('metaKeywords'), array('class' => 'help-inline')); ?>
			</div>
		</div>			
		
		<div class="formRow control-group">
			<?php echo $this->formSubmit( $form->get('submit')->setAttribute('class', 'btn btn-info')) ?>
		</div>
										
		<div class="clearfix"></div>																
										
		<div class="clearfix"></div>

	</div>
	<?php echo $this->form()->closeTag() ?>
</div>

<script>

				
	$(function(){
		$('.grid-content .formRow ul.help-inline').parents('.formRow').addClass('error');
		$('.error input').keyup(function(){
					$(this).parents('.formRow').removeClass('error');
					$(this).next('ul.help-inline').remove();
		});

		
	});				
</script>


