
<div class="grid">
    <div class="grid-title">
        <div class="pull-left">
            <div class="icon-title">
                <i class="icon-edit"></i>
            </div>
            <span>Edit Role</span>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="grid-content">

        <form action="" method="post">
         <div class="formRow control-group">
             <input type="hidden" name="id" value="<?php echo $this->collection['0']->getId(); ?>">
             <label>
                 Title </label>
            <div class="formRight">
                <input type="text" name="name" class="span input" value="<?php echo $this->collection['0']->getRoleName(); ?>" required>
            </div>
        </div>	
     

        
        <div class="formRow control-group">
            <input type="submit" value="Submit" class="btn btn-info">
        </div>
            </form>
        <div class="clearfix"></div>

    </div>

</div>




