<?php
$date = date('Y-m-d');
//d($this->collection); die; //echo $date; die;
?>

<script>
    $(function() {
        $('#myselect option[value=<?php
if (!empty($this->paymenttyp)) {
    echo $this->paymenttyp;
} else {
    echo '';
}
?>]').attr('selected', 'selected');
    });
</script>    

<?php if (!is_null($this->message)):
    
   // d($this->message);
    if ($this->message):
        ?>		
        <div class="alert alert-dismissable alert-<?php echo $this->message[0]['type']; ?>">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <ul>
                <li><?php echo $this->message[0]['message']; ?></li>        
            </ul>
        </div>
        <?php
    endif;
endif;
?>

<div class="grid">
    <div class="grid-title">
        <div class="pull-left">
            <div class="icon-title">
                <i class="icon-list"></i>
            </div> 
            <span>Reseller Roles Activity</span>
            <div class="clearfix"></div>
        </div>
        <div class="pull-right">
            <div class="icon-title">
                <a title="Add Role Activity" href="<?php echo $this->url('affiliate-roles-add-activity'); ?>"><i class="icon-plus-sign"></i></a>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>




</div>
<div class="grid">    
    <div class="grid-content overflow">

     
        <table class="table table-bordered table-mod-2" id="datatable_3">
            <thead>
                <tr>                    
                    <th class="hidden-mobile">Activity Name</th> 
                    <th class="hidden-mobile">Role Name</th>
                    <th class="hidden-mobile">Status</th>
                    <th class="hidden-mobile">Action</th>

                </tr>
            </thead>
            <tbody>
                <?php foreach($this->collection as $item){ ?>
                <?php $role=$item->getResellerRoleId(); 
                
                ?>
                    <tr>

                        <td class="hidden-mobile"><?php echo $item->getName(); ?></td>    
                        <td class="hidden-mobile"><?php echo $role->getRoleName(); ?></td>    
                        <td class="hidden-mobile"><?php echo ($item->getStatus())?'<span class="s_green">Active</span>':'<span class="s_gray">InActive</span>'; ?></td>    

                        <td class="action-table">   
                            
                            <a href="<?php echo $this->url('affiliate-roles-activity-edit',array('id'=>$item->getId())); ?>" title="Update">
                                
                                <img alt="Update" src="/images/icon/table_edit.png" height="18" width="18">
                            </a>
                            <a data-confirm="Are You Sure.?" href="<?php echo $this->url('affiliate-roles-activity-delete',array('id'=>$item->getId())); ?>" title="Delete">
                                
                                <img alt="Delete" src="/images/icon/table_del.png" height="18" width="18">
                            </a>
                        </td>



                    </tr>    
                <?php } ?>
            </tbody>
        </table>
<br><br><br>
    
        <div class="clearfix"></div>
    </div>
</div>

