<!DOCTYPE html>
<html>
 <head>
  <meta charset="utf-8">
  <title>##title##</title>
 </head> 
 <body>
  <div style="background: #CDC9C9;text-align: center;font-size: 24px; color: white;padding: 6px;">
    ##header##
  </div>
  <div style="background: #FFFAF0;padding: 12px;">
    ##message##  
    <table>
        <tr>
            <td>Profile: </td>
            <td><a href="##profile##">link</a></td>
        </tr>
        <tr>
            <td>Login: </td>
            <td>##email##<td>
        </tr>
        <tr>
            <td>Password: </td>
            <td>##password##</td>
        </tr>
    </table>
  </div>
  <div style="background: #CDC9C9; text-align: center; font-size: 14px; color: white;padding: 4px;">
    ##footer##
  </div>
 </body> 
</html>