

<table width="690" border="0" cellspacing="0" cellpadding="0" style="background:#fff url(/images/template/mainBg.jpg) repeat-x bottom left; margin:0 auto; font-family:Century Gothic; font-size:14px;">
    <tr>
        <td>
            <?php echo $this->data;?>
        </td>
    </tr>
<!--  <tr>
    <td width="20">&nbsp;</td>
    <td colspan="2">&nbsp;</td>
    <td width="20">&nbsp;</td>
    <td>&nbsp;</td>
    <td width="20">&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td rowspan="3" valign="top" style="background:#fdcc0a; padding:20px; font-size:12px;" width="270">
    <p style="margin:0; padding:0; color:#fff;">Agent<br />
      Order No.000000<br />
      Res No.000000<br />
    Date:June 23/2014</p>
    
    <p style="margin:10px 0; padding:0; color:#333;">Congratulations on successfully completing your reservations for Event 1 at Hedonism II, In Negril Jamaica. This document as you invoice and reserv Below you will find all the information relevant you vacation. Please call the attached number if you have any questions</p>
    
    <p style="margin:10px 0; padding:0; color:#333;"><strong style="font-size:20px; letter-spacing:-2px;">GUEST TRAVELLING:2</strong><br>
      John Brown<br>
      Mary Brown</p>
    <p style="margin:10px 0; padding:0; color:#333;"><strong style="font-size:20px; letter-spacing:-2px;">WHERE YOU WILL BE STAYING</strong><br>
      Hotel: Hedonism II<br>
      Location: Negril Jamaica<br>
      Board: All exclusive</p>
    <p style="margin:10px 0; padding:0; color:#333;"><strong style="font-size:20px; letter-spacing:-2px;">ACCOMODATIONS</strong><br>
      Room Cat: Hedoism II<br>
      Stay: June 15th - June20th 2015<br>
      Cost:150 person nightly</p>
    <p style="margin:10px 0; padding:0; color:#333;"><strong style="font-size:20px; letter-spacing:-2px;">FLIGHT</strong><br>
      Roundtrip from YYZ to MBJ<br>
      Total: $1000</p>
    <p style="margin:10px 0; padding:0; color:#333;"><strong style="font-size:20px; letter-spacing:-2px;">EXTRAS</strong><br>
      Tramsfers: $80<br>
      Trip insurance: $120<br>
      Excursion: $100<br>
      Total: $320</p>
    <p style="margin:10px 0; padding:0; color:#333;"><strong style="font-size:20px; letter-spacing:-2px;">COST</strong><br>
      Total: $2800<br>
      Discount:-$100<br>
      Merchant Fee: $90<br>
      New Total: $2790</p>
    <p style="margin:10px 0; padding:0; color:#333;"><strong style="font-size:20px; letter-spacing:-2px;">NOTES</strong><br>
    No notes were recorded for this reservation</p></td>
    <td rowspan="3" valign="bottom" style="background:#fdcc0a; padding:0 " width="31"><img src="/images/template/vertclTxt.png" width="31" height="397" alt=""></td> 
    leftpanel ends
    
    
    
    <td>&nbsp;</td>
    <td rowspan="3" valign="top" align="right" style="width:300px;"><table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td align="right"><img src="/images/template/logo.jpg" width="267" height="116" alt="" /></td>
      </tr>
      <tr>
        <td align="right" style="color:#a1a2a4; font-size:10px;">Sunset Destination and Adults Tours Inc.<br />
          Tico Reg#:<br />
          IATA#:<br />
          30 Eglinton Ave.West.Suite C-12<br />
          Mississauga ON<br />
          Canada L5R 3E7<br />
          Phone: 1800 458 2099<br />
          Email: reservations@vacationparties.com</td>
      </tr>
      <tr>
        <td><br>
          <br>
          <br></td>
      </tr>
      <tr>
        <td align="right" style="font-size:14px;">Client Name:<br>
          Address:<br>
          City State:<br>
          Country/Zip:<br>
          Phone:<br>
          Email:</td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>
        <span style="display:block; background:url(/images/template/greenBgStrp.png) no-repeat top left; padding:10px 20px; color:#fff; font-weight: bold; font-size:18px; margin:5px 0;">PAYMENTS</span>
        
        
        
      <span style="display:block; background:url(/images/template/greenBgStrp.png) no-repeat top left; padding:12px 20px; color:#fff; margin:5px 0; font-size:15px;">Dposit Rcdv: $50</span>
      <span style="display:block; background:url(/images/template/greenBgStrp.png) no-repeat top left; padding:12px 20px; color:#fff; margin:5px 0; font-size:15px;">Balance after deposit: $22</span>
      <span style="display:block; background:url(/images/template/greenBgStrp.png) no-repeat top left; padding:12px 20px; color:#fff; margin:5px 0; font-size:15px;">Next Pymnt: $1145 (Due 02.10.2014)</span>
      <span style="display:block; background:url(/images/template/greenBgStrp.png) no-repeat top left; padding:12px 20px; color:#fff; margin:5px 0; font-size:15px;">Final Pymnt: $1145 (Due 03.10.2014)</span>
        
        
        
        </td>
      </tr>
        <tr>
        <td>&nbsp;</td>
      </tr>
        <tr>
        <td><h2 style="font-size:20px; color:#000; font-weight:normal; margin:0;
        padding:0;">TERM OF BOOKING</h2>
        
        <p style="font-size:12px; color:#87887e; margin:0; padding:0; text-align:justify">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod   tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim   veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea   commodo consequat. Duis aute irure dolor in reprehenderit in voluptate   velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint   occaecat cupidatat non proident, sunt in culpa qui officia deserunt   mollit anim id est laborum.</p>
        </td>
      </tr>
    </table></td>rightpanel ends
    
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td colspan="2">&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>-->
</table>
