<?php //d($this->affiliatename);

$reservation=$this->data['reservation'];
$affiliate=$reservation->getAffiliateId();

$type=$reservation->getType();

$paymentDue=$this->data['paymentDues'];

//d($reservation);
$reservationdate = ($reservation->getCreatedAt() instanceof \DateTime) ? $reservation->getCreatedAt()->format('M jS/Y') : $reservation->getCreatedAt();
$travelfromdate = ($reservation->getDateFrom() instanceof \DateTime) ? $reservation->getDateFrom()->format('M jS') : $reservation->getDateFrom();
$traveltodate = ($reservation->getDateTo() instanceof \DateTime) ? $reservation->getDateTo()->format('M jS Y') : $reservation->getDateTo();
$transfer=$reservation->getTransferCost();
$excursion=$reservation->getExcursionCost();
$item =$reservation->getItemCost();
$totalcost=$reservation->getTotalCost();
$finalcost=$reservation->getfinalCost();
$discount=$reservation->getAppliDiscount();
$merchantfee=$reservation->getMerchantFee();  
$notes=$reservation->getAdminNotes();

$depositeamount=$reservation->getDepositAmoun();
$balance=$reservation->getBalansAfterDeposit();

$clientdetail=$this->clientdetail;
$clientname=$clientdetail->getName();
$clientaddress=$clientdetail->getAddress();
$clientcity=$clientdetail->getCity();
$clientstate=$clientdetail->getState();
$clientcountry=$clientdetail->getCountry();
$clientzip=$clientdetail->getZip();
$clientphone=$clientdetail->getPhone();
$clientemail=$clientdetail->getEmail();


$invoice=$this->invoice;
//d($invoice);
if($reservation->getType()!=3){

$itemname=$this->itemname;
$hotelName=$itemname->getHotelName();
$roomcategory=$itemname->getRoomCategory();
$grossprice=$itemname->getGrossPrice();
$country=$this->country;

}else{
    
$itemname=$this->itemname;
//d($this->$itemname);

$hotelName=$itemname->getCruiseName();
$roomcategory=$itemname->getSuiteName();
$grossprice=$itemname->getGrossPrice();
$country=$this->country;
    
    
}
?>
<table width="690" border="0" cellspacing="0" cellpadding="0" style="background:#fff url(/images/template/mainBg.jpg) repeat-x bottom left; margin:0 auto; font-family:Century Gothic; font-size:14px;">
  <tr>
    <td width="20">&nbsp;</td>
    <td colspan="2">&nbsp;</td>
    <td width="20">&nbsp;</td>
    <td>&nbsp;</td>
    <td width="20">&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td rowspan="3" valign="top" style="background:#fdcc0a; padding:20px; font-size:12px;" width="270">
    <p style="margin:0; padding:0; color:#fff;"><?php if($this->affliatename){ echo $this->affliatename;}else{ echo 'Agent';}?><br />
      Order No.<?php echo $invoice->getId();?><br />
      Res No.  <?php echo $reservation->getReferenceNumber();?><br/>
      Date:<?php echo $reservationdate;?></p>
    
    <p style="margin:10px 0; padding:0; color:#333;">Congratulations on successfully completing your reservations <?php if($type==2){?>for <?php echo $this->data['hotelName'];}?> at <?php echo $hotelName;?>, In <?php echo $country;?>. This document as you invoice and reserv Below you will find all the information relevant you vacation. Please call the attached number if you have any questions</p>
    
    <p style="margin:10px 0; padding:0; color:#333;"><strong style="font-size:20px; letter-spacing:-2px;">GUEST TRAVELLING: <?php echo count($this->data['travellers']);?></strong><br>
      <?php  foreach($this->data['travellers'] as $traveller){
                            echo $traveller.'<br>';
              }
       ?>     
    </p>
    <p style="margin:10px 0; padding:0; color:#333;"><strong style="font-size:20px; letter-spacing:-2px;">WHERE YOU WILL BE STAYING</strong><br>
    <?php if($type==3){ echo 'Cruise';}else{ echo 'Hotel';}?>:  <?php echo $hotelName;?><br>
      Location:<?php echo $country;?><br>
      Board: All exclusive</p>
    <p style="margin:10px 0; padding:0; color:#333;"><strong style="font-size:20px; letter-spacing:-2px;">ACCOMODATIONS</strong><br>
      Room Cat: <?php echo $roomcategory;?><br>
      Stay:<?php echo $travelfromdate.' - '. $traveltodate  ?><br>
      Cost:<?php echo $grossprice;?> person nightly</p>
    <p style="margin:10px 0; padding:0; color:#333;"><strong style="font-size:20px; letter-spacing:-2px;">FLIGHT</strong><br>
      <?php if($reservation->getFlight()==1){?>  
      Roundtrip from <?php echo $reservation->getReturnFrom()?> to <?php echo $reservation->getReturnTo()?><br>
      Total: $<?php echo $reservation->getFlightTotalCost(); ?></p>
      <?php }else{
          
          echo "No flight Details Available";
      } ?>
    <p style="margin:10px 0; padding:0; color:#333;"><strong style="font-size:20px; letter-spacing:-2px;">EXTRAS</strong><br>
      
      Transfers: $<?php echo $transfer;?><br>
      Trip insurance: $120<br>
      Excursion: $<?php echo $excursion; ?><br>
      Items:$<?php echo $item;?><br>
      Total: $<?php echo ($transfer+$excursion+$item);?></p>
    <p style="margin:10px 0; padding:0; color:#333;"><strong style="font-size:20px; letter-spacing:-2px;">COST</strong><br>
     
 
    <?php if(!empty($discount)||!empty($merchantfee)){ ?>  
      Total: $<?php echo $finalcost;?><br>
      Discount:-$<?php echo $discount;?><br>
      Merchant Fee: $<?php echo $merchantfee;?><br>
      New Total: $<?php echo ($finalcost-($discount+$merchantfee))?>
    <?php }else{?>
       Total: $<?php echo $finalcost;?><br>
    <?php }?> 
    
    </p>
    
    
    <p style="margin:10px 0; padding:0; color:#333;"><strong style="font-size:20px; letter-spacing:-2px;">NOTES</strong><br>
   
    <?php if($notes) {
      echo  $notes;
    }else{ ?>   
    No notes were recorded for this reservation</p></td>
    <?php } ?>
    <td rowspan="3" valign="bottom" style="background:#fdcc0a; padding:0 " width="31"><img src="/images/template/vertclTxt.png" width="31" height="397" alt=""></td> 
    <!--leftpanel ends-->
    
    
    
    <td>&nbsp;</td>
    <td rowspan="3" valign="top" align="right" style="width:300px;"><table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td align="right"><img src="/images/template/logo.jpg" width="267" height="116" alt="" /></td>
      </tr>
      <tr>
        <td align="right" style="color:#a1a2a4; font-size:10px;">Sunset Destination and Adults Tours Inc.<br />
          Tico Reg#:<br />
          IATA#:<br />
          30 Eglinton Ave.West.Suite C-12<br />
          Mississauga ON<br />
          Canada L5R 3E7<br />
          Phone: 1800 458 2099<br />
          Email: reservations@vacationparties.com</td>
      </tr>
      <tr>
        <td><br>
          <br>
          <br></td>
      </tr>
      <tr>
        <td align="right" style="font-size:14px;">Client Name:<?php echo $clientname;?><br>
          Address:<?php echo $clientaddress;?><br>
          City :<?php echo $clientcity;?><br>
          State:<?php echo $clientstate;?><br>
          Country:<?php echo $clientcountry;?><br>
          Zip:<?php echo $clientzip;?><br>
          Phone:<?php echo $clientphone?><br>
          Email:<?php echo $clientemail?></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td>
        <span style="display:block; background:url(/images/template/greenBgStrp.png) no-repeat top left; padding:10px 20px; color:#fff; font-weight: bold; font-size:18px; margin:5px 0;">PAYMENTS</span>
    
      <span style="display:block; background:url(/images/template/greenBgStrp.png) no-repeat top left; padding:12px 20px; color:#fff; margin:5px 0; font-size:15px;">Deposit Recevied: $<?php echo $depositeamount;?></span>
      <span style="display:block; background:url(/images/template/greenBgStrp.png) no-repeat top left; padding:12px 20px; color:#fff; margin:5px 0; font-size:15px;">Balance after deposit: $<?php echo $balance;?></span>
     
        <?php       $i=1;
                    if(count($paymentDue) > 0):
                    foreach($paymentDue as $rows): 
                    
      
                   $duedate=($rows['DueDate'] instanceof \DateTime)?$rows['DueDate']->format('m.d.Y'): $rows['DueDate']; ?>				
                     
                   <span style="display:block; background:url(/images/template/greenBgStrp.png) no-repeat top left; padding:12px 20px; color:#fff; margin:5px 0; font-size:15px;">Payment <?php echo $i.': $'.$rows['nextDueAmount'].'(Due'.$duedate.')'?></span>
      
      
                    <?php $i++; endforeach; ?>

                <?php endif; ?>
      
       
        </td>
      </tr>
        <tr>
        <td>&nbsp;</td>
      </tr>
        <tr>
        <td><h2 style="font-size:20px; color:#000; font-weight:normal; margin:0;
        padding:0;">TERM OF BOOKING</h2>
        
        <p style="font-size:12px; color:#87887e; margin:0; padding:0; text-align:justify">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod   tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim   veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea   commodo consequat. Duis aute irure dolor in reprehenderit in voluptate   velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint   occaecat cupidatat non proident, sunt in culpa qui officia deserunt   mollit anim id est laborum.</p>
        </td>
      </tr>
    </table></td><!--rightpanel ends-->
    
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td colspan="2">&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
</table>

 <?php /*if(isset($this->link)):?>
      <p>
          <a href="<?php echo isset($this->link)? $this->link:'#';?>"><?php echo isset($this->linkName)? $this->linkName:'link';?></a>
      </p>        
 <?php endif; */?>
<?php //die;?>