<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'UserClients\Module'                        => __DIR__ . '/Module.php',
    'UserClients\Controller\UserClientsController' => __DIR__ . '/src/UserClients/Controller/UserClientsController.php',
);
