<?php 

$form = $this->form;

$form->prepare();
$form->setAttribute('action', $this->url(
		'inventory-deposits-add'
));

$form->setAttribute('method', 'post');

?>

<div class="grid">
    <div class="grid-title">
        <div class="pull-left">
            <div class="icon-title">
                <i class="icon-list"></i>
            </div>
            <span>Add Deposit</span>
            <div class="clearfix"></div>
        </div>
        <div class="pull-right">
            <div class="icon-title">
                <a href="<?php //echo $this->url('inventory-promos-add'); ?>"><i class="icon-plus-sign"></i></a>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="grid-content overflow">
       
        <?php echo $this->form()->openTag($form); ?>

            
            <div class="formRow control-group">
                    <?php echo $this->formLabel($form->get('depositName')); ?>
                    <div class="formRight">
                            <?php echo $this->formElement($form->get('depositName')->setAttribute('class', 'span input')); ?>
                    <?php echo $this->formElementErrors($form->get('depositName'), array('class' => 'help-inline')); ?>
                    </div>
            </div>  
            <div class="formRow control-group">
                 <?php echo $this->formLabel($form->get('linkedTo')); ?>
                    <div class="formRight">
                            <?php echo $this->formElement($form->get('linkedTo')->setAttribute('class', 'span input width-100')); ?>
                    <?php echo $this->formElementErrors($form->get('linkedTo'), array('class' => 'help-inline')); ?>
                    </div>
            </div>
            <div class="formRow control-group">
                <span id="users" style="width:80%; float: right;"></span>
            </div>
            <div class="formRow control-group">
                   <?php echo $this->formLabel($form->get('type')); ?>
                    <div class="formRight">
                            <?php echo $this->formElement($form->get('type')->setAttribute('class', 'span input width-100')); ?>
                    <?php echo $this->formElementErrors($form->get('type'), array('class' => 'help-inline')); ?>
                    </div>
            </div>
            <div class="formRow control-group">
                    <?php echo $this->formLabel($form->get('amount')); ?>
                    <div class="formRight">
                            <?php echo $this->formElement($form->get('amount')->setAttribute('class', 'span input')); ?>
                    <?php echo $this->formElementErrors($form->get('amount'), array('class' => 'help-inline')); ?>
                    </div>
            </div>
            <div class="formRow control-group">
                    <?php echo $this->formLabel($form->get('dateFrom')); ?>
                    <div class="formRight">
                            <?php echo $this->formElement($form->get('dateFrom')->setAttribute('class', 'span input')); ?>
                    <?php echo $this->formElementErrors($form->get('dateFrom'), array('class' => 'help-inline')); ?>
                    </div>
            </div>
            <div class="formRow control-group">
                    <?php echo $this->formLabel($form->get('dateTo')); ?>
                    <div class="formRight">
                            <?php echo $this->formElement($form->get('dateTo')->setAttribute('class', 'span input')); ?>
                    <?php echo $this->formElementErrors($form->get('dateTo'), array('class' => 'help-inline')); ?>
                    </div>
            </div>
        
        <div class="formRow control-group">
                    <?php echo $this->formSubmit( $form->get('submit')->setAttribute('class', 'btn btn-info')) ?>
                    <input id="resetbutton" class="btn btn-info" type="reset" value="Reset" name="reset"></input>
            </div>
        
        <?php echo $this->form()->closeTag() ?>
        
        <div class="clearfix"></div>
    </div>
</div>

<script>
   
  $('#myselect').change(function(){        
        var id = $(this).val();        
      //  alert(id);
        $.post('/admin/inventory/ajax/type/'+id, {id:id}, function(data){
            
//            alert(data);
            $('#users').html(data); 
        });        
    });
    
   
 </script>   