<div class="grid">
    <div class="grid-title">
        <div class="pull-left">
            <div class="icon-title">
                <i class="icon-list"></i>
            </div>
            <span>View Deposit</span>
            <div class="clearfix"></div>
        </div>
        <div class="pull-right">
            <div class="icon-title">
                <a href="<?php //echo $this->url('inventory-promos-add'); ?>"><i class="icon-plus-sign"></i></a>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="grid-content overflow">
        <table class="table table-bordered table-mod-2" id="datatable_3">
            <tr>
                <td>Name</td><td><?php echo $this->data->getdepositName();?></td></tr>
               <tr> <td>Linked To</td>
                <td>
                    <?php $link=$this->data->getlinkedTo();
                    if($link==4){
                        echo "Resorts";
                    }elseif($link==5){
                        echo "Events";
                    }else{
                        echo "Cruises";
                    }
                    ?>
                </td></tr>
               <tr>
                   <td>Event Names</td>
                   <td>
                       <?php 
//                       $dis="";
                       foreach($this->typenames as $name){
                           echo $name."<br>";
                       }
//                       echo rtrim($dis,',');
                       ?>
                   </td>
               </tr>
               <tr> <td>Type</td>
                <td>
                    <?php $type=$this->data->getdepositName();
                    if($type==1){
                        echo "Percent(%)";
                    }else{
                        echo "Fixed($)";
                    }
                    
                    ?>
                </td></tr>
               <tr> <td>Amount</td><td><?php echo $this->data->getamount();?></td></tr>
                
                 <?php $dateFrom = ($this->data->getdateFrom() instanceof \DateTime) ? $this->data->getdateFrom()->format('Y-m-d') : $this->data->getdateFrom();   ?>
                <tr><td>Date From</td><td><?php echo $dateFrom;?></td></tr>
                <?php $dateTo = ($this->data->getdateTo() instanceof \DateTime) ? $this->data->getdateTo()->format('Y-m-d') : $this->data->getdateTo();   ?>
                <tr><td>Date To</td><td><?php echo $dateTo;?></td></tr>
            
            
        </table>
        
        <a class="btn btn-info" href="<?php echo $this->url('inventory-deposits'); ?>">Back</a>
        <a class="btn btn-success" href="<?php echo $this->url('inventory-deposits-update', array('id' => $this->data->getId())); ?>">Edit</a>
        <a class="btn btn-danger" href="<?php echo $this->url('inventory-deposits-delete', array('id' => $this->data->getId())); ?>">Delete</a>
         <div class="clearfix"></div>
    </div>
</div>