<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Resources\Module'                        => __DIR__ . '/Module.php',
    'Resources\Controller\ResourcesController' => __DIR__ . '/src/Resources/Controller/ResourcesController.php',
    'ResourcesTest\Framework\TestCase'        => __DIR__ . '/tests/Resources/Framework/TestCase.php',
    'ResourcesTest\SampleTest'                => __DIR__ . '/tests/Resources/SampleTest.php',
);
