<div class="formRow control-group">
                <h4>Reminder</h4>
                <hr />
</div>
<div class="formRow control-group">
    <div class="formRight">
        <div class="distance distance-2">
            <p>
                <input type="checkbox" id="reminder" name="reminder">
                <label for="flight"><span></span> Flight</label>
            </p>
        </div>
    </div>

</div>
<div class="flight" style="display:none">
    <div class="formRow control-group">
        <?php echo $this->formLabel($form->get('flightGoingAway')); ?>
        <div class="formRight">
            <?php echo $this->formElement($form->get('flightGoingAway')->setAttribute('class', 'span input')); ?>
            <?php echo $this->formElementErrors($form->get('flightGoingAway'), array('class' => 'help-inline')); ?>
        </div>
    </div>
    <div class="formRow control-group">
        <?php echo $this->formLabel($form->get('flightReturnHome')); ?>
        <div class="formRight">
            <?php echo $this->formElement($form->get('flightReturnHome')->setAttribute('class', 'span input')); ?>
            <?php echo $this->formElementErrors($form->get('flightReturnHome'), array('class' => 'help-inline')); ?>
        </div>
    </div>
    <div class="formRow control-group">
        <label for="returnFrom">Return From</label>
        <div class="formRight">
            <input type="text" name="returnFrom" class="span input"/>
        </div>
    </div>
    <div class="formRow control-group">
        <label for="returnTo">Return To</label>
        <div class="formRight">
            <input type="text" name="returnTo" class="span input"/>
        </div>
    </div>
    <div class="formRow control-group">
        <?php echo $this->formLabel($form->get('flightTotalCost')); ?>
        <div class="formRight">
            <?php echo $this->formElement($form->get('flightTotalCost')->setAttribute('class', 'span input')); ?>
            <?php echo $this->formElementErrors($form->get('flightTotalCost'), array('class' => 'help-inline')); ?>
        </div>
    </div>
</div>
<script>
$(function(){
    $('#reminder').click(function(){
        //console.log($(this).is(':checked'));
        if($(this).is(':checked')){
            $('.reminder').show();
        } else {
            $('.flight').hide();
            $('input[name="flightGoingAway"]').val('');
            $('input[name="flightReturnHome"]').val('');
            $('input[name="flightTotalCost"]').val(0);
        }
    });
});
</script>