<?php
$date = date('Y-m-d');
//d($this->collection); die; //echo $date; die;
?>

<script>
    $(function() {
        $('#myselect option[value=<?php
if (!empty($this->paymenttyp)) {
    echo $this->paymenttyp;
} else {
    echo '';
}
?>]').attr('selected', 'selected');
    });
</script>    

<?php if (!is_null($this->message)):
    
   // d($this->message);
    if ($this->message):
        ?>		
        <div class="alert alert-dismissable alert-<?php echo $this->message[0]['type']; ?>">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <ul>
                <li><?php echo $this->message[0]['message']; ?></li>        
            </ul>
        </div>
        <?php
    endif;
endif;
?>

<div class="grid">
    <div class="grid-title">
        <div class="pull-left">
            <div class="icon-title">
                <i class="icon-list"></i>
            </div> 
            <span>Reseller Commission</span>
            <div class="clearfix"></div>
        </div>
        <div class="clearfix"></div>
    </div>




</div>
<div class="grid">    
    <div class="grid-content overflow">

     

        <table class="table table-bordered table-mod-2" id="datatable_3">
            <thead>
                <tr>                    
                 <!--   <th class="hidden-mobile">Reservation No.</th> -->
                    <th class="hidden-mobile">Reseller Name</th>
                    <th class="hidden-mobile">Total Gross Sales</th>
                    <th class="hidden-mobile">Total Commission</th>
                    <th class="hidden-mobile">Action</th>

                </tr>
            </thead>
            <tbody>
                <?php
		if(!empty($this->collection)){
                foreach ($this->collection as $items):
                    if($items['reservation']!=0){
                    ?>                  

                    <tr>

                        <td class="hidden-mobile"><?php echo $items['reseller']; ?></td>    

                        <td class="hidden-mobile">$<?php echo $items['reservation']; ?> </td>
                        <td class="hidden-mobile">$<?php echo  $items['commission']; ?></td>				

                        <td class="action-table">   
                            
                            <a href="#" onclick="view(<?php echo $items['id']; ?>)">
                                View Commission History
                            </a><br>
                            <a href="<?php echo $this->url('affiliate-commission-set', array('id'=>$items['id']));?>">
                                Set Commission
                            </a>
                           
                        </td>



                    </tr>                    
                    <?php } endforeach; }?>
            </tbody>
        </table>


        <div class="clearfix"></div>
    </div>
</div>

<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close">×</button>
    <h3 id="myModalLabel"></h3>
  </div>
  <div class="modal-body">
    <p></p>
  </div>
  <div class="modal-footer">
    <button class="btn close">Close</button>
  </div>
</div>


<script>
function view(aid){
    
    $.ajax({
                async:false,    
                url: '/admin/affiliate/commission/history/'+aid,
                beforeSend:function(){
                   $(".modal-body").html('<center><img src="/images/ajax-loader.gif" alt="Loading..."></center>');  
                    $("#myModalLabel").html('View Commission History');
                    $("#myModal").css({"display": "block"});
                    $("#myModal").modal();
                },
                success: function(data){
                    $(".modal-body").html(data)  
//                  $("#myModal").modal()  
                }
            });
}

$(function(){
    
    $('.close').click(function(){
        $("#itemModal").css({"display": "none"});
        $("#myModal").css({"display": "none"});
    });
    
});
</script>
