<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Reseller\Module'                        => __DIR__ . '/Module.php',
    'Reseller\Controller\ResellerController' => __DIR__ . '/src/Reseller/Controller/ResellerController.php',
);
